// AUTO-GENERATED by scripts/split-registry.cjs — DO NOT EDIT BY HAND.
// Per-category slice of the master CalculatorEntry registry.
// Re-run `node scripts/split-registry.cjs` after editing the master.

import type { CalculatorEntry } from "@/data/calculatorRegistry";

export const generalEntries: CalculatorEntry[] = [
  {
      slug: "daily-horoscope",
      title: "Daily Horoscope",
      category: "daily-quotes",
      subcategory: "general",
      description: "Your daily astrological forecast. Love, career, and lucky numbers updated every day.",
      loader: () => import("@/components/calculators/DailyQuotes/DailyHoroscopeCalculator"),
      urlStyle: "flat"
    }
];
