// AUTO-GENERATED by scripts/split-registry.cjs — DO NOT EDIT BY HAND.
// Per-category slice of the master CalculatorEntry registry.
// Re-run `node scripts/split-registry.cjs` after editing the master.

import type { CalculatorEntry } from "@/data/calculatorRegistry";

export const petsEntries: CalculatorEntry[] = [
  {
      slug: "dog-calorie-needs-rer-mer",
      title: "Dog Calorie Needs (RER/MER) Calculator",
      category: "pets",
      subcategory: "dogs-nutrition-weight",
      description: "Calculate your dog's **Resting Energy Requirement (RER)** and **Maintenance Energy Requirement (MER)** to determine daily calorie needs.",
      seoTitle: "Dog Calorie Calculator — Daily RER & MER by Weight & Activity",
      seoDescription: "Calculate your dog's exact daily calorie needs using the RER and MER method. Enter breed, weight, and activity level for accurate feeding recommendations from vets.",
      loader: () => import("@/components/calculators/Pets/DogCalorieNeedsRerMerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dog-weight-loss-planner",
      title: "Dog Weight Loss Planner",
      category: "pets",
      subcategory: "dogs-nutrition-weight",
      description: "Plan a safe and effective weight loss program for your dog. Calculates target calories and timeline for goal weight achievement.",
      loader: () => import("@/components/calculators/Pets/DogWeightLossPlannerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dog-ideal-weight-target-calories",
      title: "Dog Ideal Weight & Target Calories Calculator",
      category: "pets",
      subcategory: "dogs-nutrition-weight",
      description: "Determine your dog's ideal healthy weight and the specific calorie intake needed to maintain it based on breed and size.",
      loader: () => import("@/components/calculators/Pets/DogIdealWeightTargetCaloriesCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dog-treat-calories-daily-allowance",
      title: "Dog Treat Calories & Daily Allowance Calculator",
      category: "pets",
      subcategory: "dogs-nutrition-weight",
      description: "Calculate the calorie content of treats and the maximum safe daily treat allowance to prevent weight gain.",
      loader: () => import("@/components/calculators/Pets/DogTreatCaloriesDailyAllowanceCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dog-chocolate-toxicity",
      title: "Dog Chocolate Toxicity Calculator",
      category: "pets",
      subcategory: "dogs-toxicology-hazard",
      description: "Calculate the risk and severity of **chocolate poisoning** in dogs based on weight, type of chocolate consumed, and amount.",
      loader: () => import("@/components/calculators/Pets/DogChocolateToxicityCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dog-grape-raisin-exposure-risk",
      title: "Dog Grape/Raisin Exposure Risk Calculator",
      category: "pets",
      subcategory: "dogs-toxicology-hazard",
      description: "Assess the toxic risk following accidental ingestion of grapes or raisins. Provides immediate action guidelines.",
      loader: () => import("@/components/calculators/Pets/DogGrapeRaisinExposureRiskCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dog-onion-garlic-exposure-risk",
      title: "Dog Onion/Garlic (Allium) Exposure Risk Calculator",
      category: "pets",
      subcategory: "dogs-toxicology-hazard",
      description: "Determine the potential toxicity risk from consuming onions, garlic, chives, or leeks (Allium species).",
      loader: () => import("@/components/calculators/Pets/DogOnionGarlicExposureRiskCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dog-xylitol-exposure-risk",
      title: "Dog Xylitol Exposure Risk Calculator",
      category: "pets",
      subcategory: "dogs-toxicology-hazard",
      description: "Calculate the severe toxic risk posed by the artificial sweetener **Xylitol** based on dog weight and ingested amount.",
      loader: () => import("@/components/calculators/Pets/DogXylitolExposureRiskCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dog-caffeine-toxicity",
      title: "Dog Caffeine Toxicity Calculator",
      category: "pets",
      subcategory: "dogs-toxicology-hazard",
      description: "Estimate the toxic level risk from accidental ingestion of coffee, tea, or caffeine-containing products.",
      loader: () => import("@/components/calculators/Pets/DogCaffeineToxicityCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dog-macadamia-nut-toxicity",
      title: "Dog Macadamia Nut Toxicity Calculator",
      category: "pets",
      subcategory: "dogs-toxicology-hazard",
      description: "Assess the risk of macadamia nut poisoning, which causes severe weakness and elevated body temperature.",
      loader: () => import("@/components/calculators/Pets/DogMacadamiaNutToxicityCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dog-alcohol-ethanol-exposure-risk",
      title: "Dog Alcohol/Ethanol Exposure Risk Calculator",
      category: "pets",
      subcategory: "dogs-toxicology-hazard",
      description: "Calculate the toxic risk of ethanol/alcohol exposure based on concentration and dog's body weight.",
      loader: () => import("@/components/calculators/Pets/DogAlcoholEthanolExposureRiskCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dog-human-medication-exposure-alert",
      title: "Dog Human-Medication Exposure Alert (Ibuprofen/Acetaminophen)",
      category: "pets",
      subcategory: "dogs-toxicology-hazard",
      description: "Alert tool for accidental exposure to common human pain relievers like **Ibuprofen** or **Acetaminophen (Tylenol)**.",
      loader: () => import("@/components/calculators/Pets/DogHumanMedicationExposureAlertCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dog-benadryl-diphenhydramine-dose",
      title: "Benadryl (Diphenhydramine) Dose Calculator for Dogs",
      category: "pets",
      subcategory: "dogs-medication-dosing",
      description: "Calculate the safe, appropriate dosage of **Benadryl (Diphenhydramine)** for dogs based on body weight.",
      loader: () => import("@/components/calculators/Pets/DogBenadrylDiphenhydramineDoseCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dog-cephalexin-dose",
      title: "Cephalexin Dose Calculator for Dogs",
      category: "pets",
      subcategory: "dogs-medication-dosing",
      description: "Calculate the veterinarian-recommended dosage for the antibiotic **Cephalexin** in dogs based on body weight.",
      loader: () => import("@/components/calculators/Pets/DogCephalexinDoseCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dog-meloxicam-metacam-dose",
      title: "Meloxicam/Metacam Dose Calculator for Dogs",
      category: "pets",
      subcategory: "dogs-medication-dosing",
      description: "Calculate the safe initial and maintenance dosages for the NSAID **Meloxicam (Metacam)** for pain relief in dogs.",
      loader: () => import("@/components/calculators/Pets/DogMeloxicamMetacamDoseCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dog-gabapentin-dose",
      title: "Gabapentin Dose Calculator for Dogs",
      category: "pets",
      subcategory: "dogs-medication-dosing",
      description: "Calculate the proper dosage for the nerve pain and anxiety medication **Gabapentin** in dogs by weight.",
      loader: () => import("@/components/calculators/Pets/DogGabapentinDoseCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dog-prednisone-prednisolone-dose",
      title: "Prednisone/Prednisolone Dose Calculator for Dogs",
      category: "pets",
      subcategory: "dogs-medication-dosing",
      description: "Calculate the correct dosage for the anti-inflammatory and immunosuppressant steroid **Prednisone/Prednisolone**.",
      loader: () => import("@/components/calculators/Pets/DogPrednisonePrednisoloneDoseCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dog-tramadol-dose",
      title: "Tramadol Dose Calculator for Dogs",
      category: "pets",
      subcategory: "dogs-medication-dosing",
      description: "Calculate the appropriate pain relief dosage for **Tramadol** in dogs, considering weight and pain severity.",
      loader: () => import("@/components/calculators/Pets/DogTramadolDoseCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dog-omega-3-epa-dha-supplement",
      title: "Omega-3 (EPA/DHA) Supplement Calculator for Dogs",
      category: "pets",
      subcategory: "dogs-medication-dosing",
      description: "Determine the correct daily supplement dosage of **Omega-3 fatty acids (EPA/DHA)** for joint and skin health.",
      loader: () => import("@/components/calculators/Pets/DogOmega3EpaDhaSupplementCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "puppy-adult-size-predictor-weight-curve",
      title: "Puppy Adult Size Predictor (Weight Curve)",
      category: "pets",
      subcategory: "dogs-growth-body-measures",
      description: "Predict your puppy's final adult weight and size based on current age, weight, and breed growth curves.",
      loader: () => import("@/components/calculators/Pets/PuppyAdultSizePredictorWeightCurveCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dog-body-condition-score-bcs-target",
      title: "Dog Body Condition Score Helper (BCS → Target Plan)",
      category: "pets",
      subcategory: "dogs-growth-body-measures",
      description: "Use the **Body Condition Score (BCS)** system to assess your dog's fat level and create a target weight plan.",
      loader: () => import("@/components/calculators/Pets/DogBodyConditionScoreBcsTargetCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dog-bmi-body-index-educational",
      title: "Dog BMI/Body Index (educational)",
      category: "pets",
      subcategory: "dogs-growth-body-measures",
      description: "Educational tool to understand the concept of a body mass index tailored for canine anatomy and health.",
      loader: () => import("@/components/calculators/Pets/DogBmiBodyIndexEducationalCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dog-crate-size-finder",
      title: "Dog Crate Size Finder",
      category: "pets",
      subcategory: "dogs-growth-body-measures",
      description: "Find the correct and comfortable crate size for your dog based on their standing height and length.",
      loader: () => import("@/components/calculators/Pets/DogCrateSizeFinderCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dog-harness-size-fit-guide",
      title: "Dog Harness Size & Fit Guide",
      category: "pets",
      subcategory: "dogs-growth-body-measures",
      description: "Guide to measure and select the correct harness size and style for comfort and escape prevention.",
      loader: () => import("@/components/calculators/Pets/DogHarnessSizeFitGuideCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dog-walking-calories-burned",
      title: "Dog Walking Calories Burned Calculator",
      category: "pets",
      subcategory: "dogs-activity-fitness",
      description: "Estimate the number of calories your dog burns during walks based on distance, pace, and body weight.",
      loader: () => import("@/components/calculators/Pets/DogWalkingCaloriesBurnedCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dog-step-goal-activity-time-planner",
      title: "Dog Step-Goal & Activity Time Planner",
      category: "pets",
      subcategory: "dogs-activity-fitness",
      description: "Plan and track daily step goals and active play time to ensure adequate exercise for your dog's needs.",
      loader: () => import("@/components/calculators/Pets/DogStepGoalActivityTimePlannerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dog-heat-risk-walk-safety-window",
      title: "Heat Risk/Walk Safety Window (Temp & Humidity)",
      category: "pets",
      subcategory: "dogs-activity-fitness",
      description: "Calculates the **Heat Index Risk** based on ambient temperature and humidity to determine safe windows for dog walks.",
      loader: () => import("@/components/calculators/Pets/DogHeatRiskWalkSafetyWindowCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dog-age-human-years-breed-aware",
      title: "Dog Age in Human Years (Breed-Aware)",
      category: "pets",
      subcategory: "dogs-age-longevity",
      description: "Convert your dog's age to human years using a formula that accounts for their specific breed size and longevity.",
      loader: () => import("@/components/calculators/Pets/DogAgeHumanYearsBreedAwareCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dog-life-expectancy-estimator",
      title: "Dog Life Expectancy Estimator (lifestyle factors)",
      category: "pets",
      subcategory: "dogs-age-longevity",
      description: "Estimate a dog's life expectancy based on breed, size, diet, exercise habits, and spay/neuter status.",
      loader: () => import("@/components/calculators/Pets/DogLifeExpectancyEstimatorCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dog-pregnancy-gestation-due-date",
      title: "Dog Pregnancy (Gestation) Due-Date Calculator",
      category: "pets",
      subcategory: "dogs-reproduction",
      description: "Calculate the expected **due date** for a pregnant dog based on the date of first or last breeding.",
      loader: () => import("@/components/calculators/Pets/DogPregnancyGestationDueDateCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "puppy-calorie-needs-age-breed-size",
      title: "Puppy Calorie Needs by Age/Breed Size Calculator",
      category: "pets",
      subcategory: "dogs-nutrition-weight",
      description: "Calculate the specific energy needs for puppies based on their current age and predicted adult breed size for optimal growth.",
      loader: () => import("@/components/calculators/Pets/PuppyCalorieNeedsAgeBreedSizeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dog-protein-fat-intake-guide",
      title: "Dog Protein/Fat Intake Guide (by Goal)",
      category: "pets",
      subcategory: "dogs-nutrition-weight",
      description: "Guide for setting optimal **protein and fat ratios** in your dog's diet, tailored for growth, maintenance, or athletic performance.",
      loader: () => import("@/components/calculators/Pets/DogProteinFatIntakeGuideCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dog-daily-water-intake-checker",
      title: "Dog Daily Water Intake Checker",
      category: "pets",
      subcategory: "dogs-hydration",
      description: "Check if your dog is drinking enough water daily. Calculates the minimum required intake based on weight and diet type.",
      loader: () => import("@/components/calculators/Pets/DogDailyWaterIntakeCheckerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dog-dehydration-risk-estimator",
      title: "Dehydration Risk Estimator (Weight & Symptoms Aware)",
      category: "pets",
      subcategory: "dogs-hydration",
      description: "Estimate the risk of dehydration by inputting weight changes and physical symptoms for veterinary attention.",
      loader: () => import("@/components/calculators/Pets/DogDehydrationRiskEstimatorCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dog-whelping-countdown-stage-timeline",
      title: "Whelping Countdown & Stage Timeline",
      category: "pets",
      subcategory: "dogs-reproduction",
      description: "Track the countdown to whelping (birth) and estimate the timeline for each stage of labor.",
      loader: () => import("@/components/calculators/Pets/DogWhelpingCountdownStageTimelineCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-calorie-needs-rer-mer",
      title: "Cat Calorie Needs (RER/MER) Calculator",
      category: "pets",
      subcategory: "cats-nutrition-weight",
      description: "Calculate your cat's **Resting Energy Requirement (RER)** and **Maintenance Energy Requirement (MER)** for daily feeding.",
      loader: () => import("@/components/calculators/Pets/CatCalorieNeedsRerMerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-weight-loss-planner",
      title: "Cat Weight Loss Planner",
      category: "pets",
      subcategory: "cats-nutrition-weight",
      description: "Plan a tailored weight loss program for your cat, calculating target calories, weight reduction, and duration.",
      loader: () => import("@/components/calculators/Pets/CatWeightLossPlannerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-ideal-weight-target-calories",
      title: "Ideal Weight & Target Calories for Cats",
      category: "pets",
      subcategory: "cats-nutrition-weight",
      description: "Determine your cat's optimal weight and the necessary daily calorie intake for maintenance.",
      loader: () => import("@/components/calculators/Pets/CatIdealWeightTargetCaloriesCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "kitten-calorie-needs-age-size",
      title: "Kitten Calorie Needs by Age/Size",
      category: "pets",
      subcategory: "cats-nutrition-weight",
      description: "Calculate the high energy requirements for growing kittens based on their age and projected adult size.",
      loader: () => import("@/components/calculators/Pets/KittenCalorieNeedsAgeSizeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "senior-cat-nutrition-calorie-adjuster",
      title: "Senior Cat Nutrition & Calorie Adjuster",
      category: "pets",
      subcategory: "cats-nutrition-weight",
      description: "Adjust feeding plans and calorie targets for older cats, accounting for changes in metabolism and activity.",
      loader: () => import("@/components/calculators/Pets/SeniorCatNutritionCalorieAdjusterCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-treat-calories-daily-allowance",
      title: "Cat Treat Calories & Daily Allowance",
      category: "pets",
      subcategory: "cats-nutrition-weight",
      description: "Calculate the caloric contribution of cat treats and set a safe daily limit to prevent excess weight gain.",
      loader: () => import("@/components/calculators/Pets/CatTreatCaloriesDailyAllowanceCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-protein-fat-intake-guide",
      title: "Protein/Fat Intake Guide for Cats (by Goal)",
      category: "pets",
      subcategory: "cats-nutrition-weight",
      description: "Guide for ensuring your cat meets its high protein requirements, adjusting fat ratios for health goals.",
      loader: () => import("@/components/calculators/Pets/CatProteinFatIntakeGuideCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-daily-water-intake-checker",
      title: "Daily Water Intake Checker for Cats",
      category: "pets",
      subcategory: "cats-hydration",
      description: "Check if your cat is meeting its daily fluid requirement, crucial for kidney health, especially with dry food diets.",
      loader: () => import("@/components/calculators/Pets/CatDailyWaterIntakeCheckerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-dehydration-risk-estimator",
      title: "Dehydration Risk Estimator (Symptoms + Intake)",
      category: "pets",
      subcategory: "cats-hydration",
      description: "Estimate the risk of dehydration using clinical signs and tracking fluid intake, particularly in sick cats.",
      loader: () => import("@/components/calculators/Pets/CatDehydrationRiskEstimatorCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-chocolate-toxicity",
      title: "Cat Chocolate Toxicity Calculator",
      category: "pets",
      subcategory: "cats-toxicology-hazard",
      description: "Calculate the toxic dose of chocolate for cats (though less common than in dogs).",
      loader: () => import("@/components/calculators/Pets/CatChocolateToxicityCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-onion-garlic-toxicity",
      title: "Cat Onion/Garlic Toxicity Calculator",
      category: "pets",
      subcategory: "cats-toxicology-hazard",
      description: "Determine the potential risk of red blood cell damage from ingesting Allium species (onions, garlic).",
      loader: () => import("@/components/calculators/Pets/CatOnionGarlicToxicityCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-grape-raisin-exposure-risk",
      title: "Cat Grape/Raisin Exposure Risk (educational)",
      category: "pets",
      subcategory: "cats-toxicology-hazard",
      description: "Educational tool on the potential, though rare, kidney toxicity risk from grapes and raisins in cats.",
      loader: () => import("@/components/calculators/Pets/CatGrapeRaisinExposureRiskCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-xylitol-exposure-risk",
      title: "Xylitol Exposure Risk for Cats (rare but educational)",
      category: "pets",
      subcategory: "cats-toxicology-hazard",
      description: "Educational tool detailing the severe risk of Xylitol poisoning, even though cat exposure is less frequent.",
      loader: () => import("@/components/calculators/Pets/CatXylitolExposureRiskCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-caffeine-toxicity",
      title: "Caffeine Toxicity Risk for Cats",
      category: "pets",
      subcategory: "cats-toxicology-hazard",
      description: "Estimate the toxic exposure risk from caffeine in products like coffee grounds, tea, or energy drinks.",
      loader: () => import("@/components/calculators/Pets/CatCaffeineToxicityCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-essential-oils-exposure-risk",
      title: "Essential Oils Exposure Risk (diffuser/dermal)",
      category: "pets",
      subcategory: "cats-toxicology-hazard",
      description: "Assess the toxic risk from exposure to essential oils (e.g., concentrated tea tree oil) via diffusers or skin contact.",
      loader: () => import("@/components/calculators/Pets/CatEssentialOilsExposureRiskCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-lilies-poisoning-risk-guide",
      title: "Lilies Poisoning Risk Guide (cats)",
      category: "pets",
      subcategory: "cats-toxicology-hazard",
      description: "Guide to the extreme and potentially fatal kidney toxicity risk posed by exposure to various types of lilies.",
      loader: () => import("@/components/calculators/Pets/CatLiliesPoisoningRiskGuideCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-acetaminophen-ibuprofen-exposure-risk",
      title: "Acetaminophen/Ibuprofen Exposure Risk (human meds)",
      category: "pets",
      subcategory: "cats-toxicology-hazard",
      description: "Alert tool for accidental exposure to common human pain relievers, particularly dangerous **Acetaminophen (Tylenol)**.",
      loader: () => import("@/components/calculators/Pets/CatAcetaminophenIbuprofenExposureRiskCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-benadryl-diphenhydramine-dose",
      title: "Benadryl (Diphenhydramine) Dose Calculator for Cats",
      category: "pets",
      subcategory: "cats-medication-dosing",
      description: "Calculate the safe, appropriate dosage of **Benadryl (Diphenhydramine)** for cats based on body weight.",
      loader: () => import("@/components/calculators/Pets/CatBenadrylDiphenhydramineDoseCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-cephalexin-dose",
      title: "Cephalexin Dose Calculator for Cats",
      category: "pets",
      subcategory: "cats-medication-dosing",
      description: "Calculate the veterinarian-recommended dosage for the antibiotic **Cephalexin** in cats based on body weight.",
      loader: () => import("@/components/calculators/Pets/CatCephalexinDoseCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-meloxicam-dose",
      title: "Meloxicam Dose Calculator for Cats",
      category: "pets",
      subcategory: "cats-medication-dosing",
      description: "Calculate the short-term analgesic dose for the NSAID **Meloxicam** in cats.",
      loader: () => import("@/components/calculators/Pets/CatMeloxicamDoseCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-gabapentin-dose",
      title: "Gabapentin Dose Calculator for Cats",
      category: "pets",
      subcategory: "cats-medication-dosing",
      description: "Calculate the proper dosage for the nerve pain and sedation medication **Gabapentin** in cats by weight.",
      loader: () => import("@/components/calculators/Pets/CatGabapentinDoseCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-prednisolone-dose",
      title: "Prednisolone Dose Calculator for Cats",
      category: "pets",
      subcategory: "cats-medication-dosing",
      description: "Calculate the correct dosage for the anti-inflammatory steroid **Prednisolone** in cats.",
      loader: () => import("@/components/calculators/Pets/CatPrednisoloneDoseCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-omega-3-epa-dha-supplement",
      title: "Omega-3 (EPA/DHA) Supplement Calculator for Cats",
      category: "pets",
      subcategory: "cats-medication-dosing",
      description: "Determine the correct daily supplement dosage of **Omega-3 fatty acids (EPA/DHA)** for joint and skin health in cats.",
      loader: () => import("@/components/calculators/Pets/CatOmega3EpaDhaSupplementCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-insulin-starter-reference",
      title: "Insulin Starter Reference (info-only)",
      category: "pets",
      subcategory: "cats-medication-dosing",
      description: "Reference guide for starting and monitoring insulin therapy in diabetic cats (information-only, not a dose calculator).",
      loader: () => import("@/components/calculators/Pets/CatInsulinStarterReferenceCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "kitten-adult-weight-predictor",
      title: "Kitten Adult Weight Predictor",
      category: "pets",
      subcategory: "cats-growth-size-measures",
      description: "Predict your kitten's final adult weight and size based on current age, weight, and growth metrics.",
      loader: () => import("@/components/calculators/Pets/KittenAdultWeightPredictorCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-body-condition-score-bcs-target",
      title: "Cat Body Condition Score Helper (BCS → Target Plan)",
      category: "pets",
      subcategory: "cats-growth-size-measures",
      description: "Use the **Body Condition Score (BCS)** system to assess your cat's fat level and formulate a target weight plan.",
      loader: () => import("@/components/calculators/Pets/CatBodyConditionScoreBcsTargetCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-bmi-body-index-educational",
      title: "Cat BMI/Body Index (educational)",
      category: "pets",
      subcategory: "cats-growth-size-measures",
      description: "Educational tool to understand the concept of a feline body mass index for health tracking.",
      loader: () => import("@/components/calculators/Pets/CatBmiBodyIndexEducationalCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-carrier-size-fit-guide",
      title: "Cat Carrier Size & Fit Guide",
      category: "pets",
      subcategory: "cats-growth-size-measures",
      description: "Guide to select the proper carrier size for your cat, ensuring comfort and safety during travel.",
      loader: () => import("@/components/calculators/Pets/CatCarrierSizeFitGuideCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-harness-size-fit-guide",
      title: "Cat Harness Size & Fit Guide",
      category: "pets",
      subcategory: "cats-growth-size-measures",
      description: "Guide to measure and select the correct harness size and fit for walking or outdoor time.",
      loader: () => import("@/components/calculators/Pets/CatHarnessSizeFitGuideCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-activity-calorie-adjuster",
      title: "Indoor/Outdoor Activity Calorie Adjuster",
      category: "pets",
      subcategory: "cats-activity-lifestyle",
      description: "Adjust daily calorie targets based on whether your cat is strictly indoor or has outdoor access.",
      loader: () => import("@/components/calculators/Pets/CatActivityCalorieAdjusterCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-play-session-planner",
      title: "Play Session Planner (Feather/Chase Time Targets)",
      category: "pets",
      subcategory: "cats-activity-lifestyle",
      description: "Plan optimal daily playtime sessions (duration and intensity) to meet your cat's exercise and enrichment needs.",
      loader: () => import("@/components/calculators/Pets/CatPlaySessionPlannerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-resting-active-hours-balance-tracker",
      title: "Resting vs. Active Hours Balance Tracker (owner input)",
      category: "pets",
      subcategory: "cats-activity-lifestyle",
      description: "Tool for owners to track and assess the balance between their cat's resting and active hours.",
      loader: () => import("@/components/calculators/Pets/CatRestingActiveHoursBalanceTrackerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-age-human-years-breed-size-aware",
      title: "Cat Age in Human Years (Breed/Size Aware)",
      category: "pets",
      subcategory: "cats-age-longevity",
      description: "Convert your cat's age to human years using a method that accounts for life stage and size.",
      loader: () => import("@/components/calculators/Pets/CatAgeHumanYearsBreedSizeAwareCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "senior-cat-care-readiness-checklist",
      title: "Senior Cat Care Readiness Checklist (scored helper)",
      category: "pets",
      subcategory: "cats-age-longevity",
      description: "Scored checklist to evaluate readiness for senior cat care, covering diet, environment, and health monitoring.",
      loader: () => import("@/components/calculators/Pets/SeniorCatCareReadinessChecklistCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-life-expectancy-estimator",
      title: "Life Expectancy Estimator (lifestyle factors; educational)",
      category: "pets",
      subcategory: "cats-age-longevity",
      description: "Educational tool to estimate a cat's life expectancy based on diet, activity, and preventative care.",
      loader: () => import("@/components/calculators/Pets/CatLifeExpectancyEstimatorCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-litter-box-output-tracker",
      title: "Litter Box Output Tracker (Normal vs. Increased)",
      category: "pets",
      subcategory: "cats-urinary-kidney",
      description: "Tool to track and compare normal litter box output against potentially worrying increases or decreases in volume.",
      loader: () => import("@/components/calculators/Pets/CatLitterBoxOutputTrackerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-fluid-intake-urine-output-balance",
      title: "Fluid Intake vs. Urine Output Balance Checker",
      category: "pets",
      subcategory: "cats-urinary-kidney",
      description: "Check the balance between liquid consumed and liquid expelled, key for monitoring kidney function.",
      loader: () => import("@/components/calculators/Pets/CatFluidIntakeUrineOutputBalanceCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-phosphorus-per-meal-estimator",
      title: "Phosphorus per Meal Estimator (diet label helper)",
      category: "pets",
      subcategory: "cats-urinary-kidney",
      description: "Calculate the phosphorus content per meal from food labels, essential for cats with kidney disease.",
      loader: () => import("@/components/calculators/Pets/CatPhosphorusPerMealEstimatorCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-pregnancy-gestation-due-date",
      title: "Cat Pregnancy (Gestation) Due-Date Calculator",
      category: "pets",
      subcategory: "cats-reproduction",
      description: "Calculate the expected **due date** for a pregnant cat (queen) based on the date of breeding.",
      loader: () => import("@/components/calculators/Pets/CatPregnancyGestationDueDateCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "kitten-weaning-timeline-feeding-amounts",
      title: "Kitten Weaning Timeline & Feeding Amounts",
      category: "pets",
      subcategory: "cats-reproduction",
      description: "Planner for the transition from mother's milk to solid food, calculating appropriate feeding amounts at each stage.",
      loader: () => import("@/components/calculators/Pets/KittenWeaningTimelineFeedingAmountsCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-shedding-combing-time-planner",
      title: "Shedding & Combing Time Planner",
      category: "pets",
      subcategory: "cats-grooming-care",
      description: "Plan an optimal combing schedule to manage shedding based on coat type and season.",
      loader: () => import("@/components/calculators/Pets/CatSheddingCombingTimePlannerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-nail-trim-interval-planner",
      title: "Nail Trim Interval Planner (activity/surface based)",
      category: "pets",
      subcategory: "cats-grooming-care",
      description: "Determine the best frequency for nail trims based on the cat's activity level and available scratching surfaces.",
      loader: () => import("@/components/calculators/Pets/CatNailTrimIntervalPlannerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "multi-cat-litter-box-count-calculator",
      title: "Multi-Cat Litter Box Count Calculator",
      category: "pets",
      subcategory: "cats-behavior-environment",
      description: "Calculate the correct number of litter boxes needed for a multi-cat household to minimize stress and accidents.",
      loader: () => import("@/components/calculators/Pets/MultiCatLitterBoxCountCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-environmental-enrichment-planner",
      title: "Environmental Enrichment Planner (per room)",
      category: "pets",
      subcategory: "cats-behavior-environment",
      description: "Plan specific enrichment items (scratch posts, perches, toys) for each room to improve feline well-being.",
      loader: () => import("@/components/calculators/Pets/CatEnvironmentalEnrichmentPlannerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-stress-score-playtime-offset-planner",
      title: "Stress Score & Playtime Offset Planner (owner input)",
      category: "pets",
      subcategory: "cats-behavior-environment",
      description: "Tool to help owners assess their cat's stress levels and plan appropriate corrective playtime or environment changes.",
      loader: () => import("@/components/calculators/Pets/CatStressScorePlaytimeOffsetPlannerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "horse-calorie-energy-requirement-de-tdn",
      title: "Horse Calorie & Energy Requirement Calculator (DE / TDN)",
      category: "pets",
      subcategory: "horses-nutrition-weight",
      description: "Calculate a horse's daily **Digestible Energy (DE)** and **Total Digestible Nutrients (TDN)** requirements.",
      loader: () => import("@/components/calculators/Pets/HorseCalorieEnergyRequirementDeTdnCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "horse-weight-estimator-girth-length",
      title: "Horse Weight Estimator (Heart Girth & Length)",
      category: "pets",
      subcategory: "horses-nutrition-weight",
      description: "Estimate your horse's body weight accurately using heart girth circumference and body length measurements.",
      loader: () => import("@/components/calculators/Pets/HorseWeightEstimatorGirthLengthCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "bird-daily-calorie-needs-body-weight",
      title: "Daily Calorie Needs by Body Weight",
      category: "pets",
      subcategory: "birds-nutrition-weight",
      description: "Calculate the daily calorie and energy requirements for different species of birds based on body weight.",
      loader: () => import("@/components/calculators/Pets/BirdDailyCalorieNeedsBodyWeightCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "bird-seed-to-pellet-conversion-planner",
      title: "Seed-to-Pellet Conversion Planner",
      category: "pets",
      subcategory: "birds-nutrition-weight",
      description: "Plan a gradual conversion schedule from a seed-based diet to a healthier, complete pellet diet.",
      loader: () => import("@/components/calculators/Pets/BirdSeedToPelletConversionPlannerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "reptile-uvb-lighting-distance-duration",
      title: "UVB Lighting Distance & Duration Calculator",
      category: "pets",
      subcategory: "reptiles-nutrition-environment",
      description: "Calculate the correct distance and duration for **UVB lighting** to ensure proper Vitamin D3 synthesis.",
      loader: () => import("@/components/calculators/Pets/ReptileUvbLightingDistanceDurationCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "reptile-basking-temperature-gradient-planner",
      title: "Basking Temperature & Gradient Planner",
      category: "pets",
      subcategory: "reptiles-nutrition-environment",
      description: "Plan the ideal basking spot temperature and the necessary temperature gradient for a reptile enclosure.",
      loader: () => import("@/components/calculators/Pets/ReptileBaskingTemperatureGradientPlannerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "horse-feeding-rate-forage-concentrate",
      title: "Horse Feeding Rate Calculator (Forage + Concentrate)",
      category: "pets",
      subcategory: "horses-nutrition-weight",
      description: "Calculate the required daily feeding rate for both forage (hay/grass) and concentrated feeds.",
      loader: () => import("@/components/calculators/Pets/HorseFeedingRateForageConcentrateCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "horse-hay-intake-bodyweight-percent",
      title: "Horse Hay Intake Calculator (per body weight %)",
      category: "pets",
      subcategory: "horses-nutrition-weight",
      description: "Determine the recommended minimum and maximum hay intake as a percentage of the horse's body weight.",
      loader: () => import("@/components/calculators/Pets/HorseHayIntakeBodyweightPercentCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "horse-protein-lysine-requirement",
      title: "Horse Protein & Lysine Requirement Calculator",
      category: "pets",
      subcategory: "horses-nutrition-weight",
      description: "Calculate the daily requirements for crude protein and the essential amino acid **Lysine** for horses.",
      loader: () => import("@/components/calculators/Pets/HorseProteinLysineRequirementCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "horse-electrolyte-need-estimator",
      title: "Horse Electrolyte Need Estimator (Exercise & Heat)",
      category: "pets",
      subcategory: "horses-nutrition-weight",
      description: "Estimate necessary electrolyte supplementation based on ambient heat and intensity of exercise/sweating.",
      loader: () => import("@/components/calculators/Pets/HorseElectrolyteNeedEstimatorCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "horse-body-condition-score-henneke",
      title: "Horse Body Condition Score Helper (Henneke 1–9)",
      category: "pets",
      subcategory: "horses-nutrition-weight",
      description: "Use the **Henneke 1-9 scale** to assess a horse's fat reserves and plan nutritional adjustments.",
      loader: () => import("@/components/calculators/Pets/HorseBodyConditionScoreHennekeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "horse-water-intake-temperature-weight",
      title: "Horse Water Intake by Temperature & Weight",
      category: "pets",
      subcategory: "horses-hydration",
      description: "Estimate the minimum daily water intake required for a horse based on its weight and ambient air temperature.",
      loader: () => import("@/components/calculators/Pets/HorseWaterIntakeTemperatureWeightCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "horse-dehydration-risk-estimator",
      title: "Dehydration Risk Estimator (Skin Turgor + Mucous Check)",
      category: "pets",
      subcategory: "horses-hydration",
      description: "Assess dehydration risk using the skin pinch (turgor) test and capillary refill time (mucous checks).",
      loader: () => import("@/components/calculators/Pets/HorseDehydrationRiskEstimatorCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "horse-colic-risk-assessment",
      title: "Horse Colic Risk Assessment (Feeding & Management)",
      category: "pets",
      subcategory: "horses-health-toxicology",
      description: "Assess the risk of colic (abdominal pain) based on feeding practices, management, and health history.",
      loader: () => import("@/components/calculators/Pets/HorseColicRiskAssessmentCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "horse-laminitis-risk-index",
      title: "Laminitis Risk Index (BCS + NSC intake)",
      category: "pets",
      subcategory: "horses-health-toxicology",
      description: "Calculate the risk of **Laminitis (Founder)** based on Body Condition Score and non-structural carbohydrate (NSC) intake.",
      loader: () => import("@/components/calculators/Pets/HorseLaminitisRiskIndexCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "horse-toxic-plant-exposure-risk",
      title: "Horse Toxic Plant Exposure Risk (Ragwort, Yew, etc.)",
      category: "pets",
      subcategory: "horses-health-toxicology",
      description: "Tool to evaluate the poisoning risk from common toxic pasture plants like **Ragwort** or **Yew**.",
      loader: () => import("@/components/calculators/Pets/HorseToxicPlantExposureRiskCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "horse-nsaid-overdose-risk",
      title: "Horse NSAID Overdose Risk (Phenylbutazone)",
      category: "pets",
      subcategory: "horses-health-toxicology",
      description: "Assess the overdose and toxicity risk associated with common horse anti-inflammatories like **Phenylbutazone (Bute)**.",
      loader: () => import("@/components/calculators/Pets/HorseNsaidOverdoseRiskCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "horse-selenium-toxicity-threshold",
      title: "Horse Selenium Toxicity Threshold (ppm)",
      category: "pets",
      subcategory: "horses-health-toxicology",
      description: "Calculate the safe upper limit and potential toxicity risk of **Selenium** intake in parts per million (ppm).",
      loader: () => import("@/components/calculators/Pets/HorseSeleniumToxicityThresholdCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "horse-salt-mineral-balance-checker",
      title: "Horse Salt & Mineral Balance Checker",
      category: "pets",
      subcategory: "horses-health-toxicology",
      description: "Check the daily intake of salt and essential macro/micro-minerals against required nutritional levels.",
      loader: () => import("@/components/calculators/Pets/HorseSaltMineralBalanceCheckerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "horse-dewormer-dose-calculator",
      title: "Dewormer Dose Calculator (by Drug Class & Weight)",
      category: "pets",
      subcategory: "horses-medication-supplement",
      description: "Calculate the correct dosage for various types of dewormers (anthelmintics) based on drug class and horse weight.",
      loader: () => import("@/components/calculators/Pets/HorseDewormerDoseCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "horse-phenylbutazone-flunixin-dose",
      title: "Phenylbutazone / Flunixin Dose Calculator",
      category: "pets",
      subcategory: "horses-medication-supplement",
      description: "Calculate the safe dose for the NSAIDs **Phenylbutazone** and **Flunixin** for pain and fever management.",
      loader: () => import("@/components/calculators/Pets/HorsePhenylbutazoneFlunixinDoseCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "horse-electrolyte-powder-mixing",
      title: "Electrolyte Powder Mixing Calculator",
      category: "pets",
      subcategory: "horses-medication-supplement",
      description: "Determine the correct ratio for mixing electrolyte powders into water or feed for performance horses.",
      loader: () => import("@/components/calculators/Pets/HorseElectrolytePowderMixingCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "horse-omega-3-supplement-planner",
      title: "Omega-3 Supplement Planner (EPA/DHA per kg)",
      category: "pets",
      subcategory: "horses-medication-supplement",
      description: "Determine the required supplement dosage of Omega-3 fatty acids based on the horse's weight (kg).",
      loader: () => import("@/components/calculators/Pets/HorseOmega3SupplementPlannerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "horse-gestation-due-date",
      title: "Horse Gestation (Due Date) Calculator",
      category: "pets",
      subcategory: "horses-reproduction",
      description: "Calculate the expected **foaling (birth) date** for a pregnant mare.",
      loader: () => import("@/components/calculators/Pets/HorseGestationDueDateCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "horse-foaling-countdown-lactation-feed-planner",
      title: "Foaling Countdown & Lactation Feed Planner",
      category: "pets",
      subcategory: "horses-reproduction",
      description: "Track the final days before foaling and plan the increased feed/calorie requirements during the lactation period.",
      loader: () => import("@/components/calculators/Pets/HorseFoalingCountdownLactationFeedPlannerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "bird-hand-feeding-formula-amount-chicks",
      title: "Hand-Feeding Formula Amount (Chicks)",
      category: "pets",
      subcategory: "birds-nutrition-weight",
      description: "Calculate the correct volume and frequency for hand-feeding formula for baby chicks and fledglings.",
      loader: () => import("@/components/calculators/Pets/BirdHandFeedingFormulaAmountChicksCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "bird-vitamin-a-requirement",
      title: "Vitamin A Requirement Calculator",
      category: "pets",
      subcategory: "birds-nutrition-weight",
      description: "Calculate the required daily intake of Vitamin A, deficiency of which is common in seed-fed birds.",
      loader: () => import("@/components/calculators/Pets/BirdVitaminARequirementCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "bird-calcium-supplement-dosage-breeding-females",
      title: "Calcium Supplement Dosage (Breeding Females)",
      category: "pets",
      subcategory: "birds-nutrition-weight",
      description: "Determine the appropriate calcium supplement dose for egg-laying and breeding female birds.",
      loader: () => import("@/components/calculators/Pets/BirdCalciumSupplementDosageBreedingFemalesCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "bird-weight-trend-tracker-weekly",
      title: "Weight Trend Tracker (Weekly Log)",
      category: "pets",
      subcategory: "birds-nutrition-weight",
      description: "Tool to log and track a bird's weight weekly to catch subtle signs of illness or nutritional imbalance.",
      loader: () => import("@/components/calculators/Pets/BirdWeightTrendTrackerWeeklyCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "bird-toxic-foods-exposure-checker",
      title: "Toxic Foods Exposure Checker (Avocado, Chocolate, etc.)",
      category: "pets",
      subcategory: "birds-health-toxicology",
      description: "Check the toxicity of common human foods like **Avocado, Chocolate, and fruit seeds** for pet birds.",
      loader: () => import("@/components/calculators/Pets/BirdToxicFoodsExposureCheckerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "bird-heavy-metal-exposure-risk",
      title: "Heavy Metal (Lead/Zinc) Exposure Risk",
      category: "pets",
      subcategory: "birds-health-toxicology",
      description: "Assess the risk of poisoning from exposure to heavy metals like **lead or zinc** (e.g., from cages or toys).",
      loader: () => import("@/components/calculators/Pets/BirdHeavyMetalExposureRiskCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "bird-feather-plucking-stress-risk-index",
      title: "Feather Plucking & Stress Risk Index",
      category: "pets",
      subcategory: "birds-health-toxicology",
      description: "Index to assess the environmental and behavioral stress factors that may lead to feather plucking behavior.",
      loader: () => import("@/components/calculators/Pets/BirdFeatherPluckingStressRiskIndexCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "bird-egg-binding-risk-estimator",
      title: "Egg Binding Risk Estimator",
      category: "pets",
      subcategory: "birds-health-toxicology",
      description: "Estimate the risk of a female bird suffering from **egg binding** based on nutrition and reproductive history.",
      loader: () => import("@/components/calculators/Pets/BirdEggBindingRiskEstimatorCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "bird-ambient-temperature-safe-zone",
      title: "Ambient Temperature Safe Zone Calculator",
      category: "pets",
      subcategory: "birds-health-toxicology",
      description: "Determine the ideal ambient temperature range for the bird's enclosure to prevent heat stress or chill.",
      loader: () => import("@/components/calculators/Pets/BirdAmbientTemperatureSafeZoneCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "bird-daily-water-requirement-per-weight",
      title: "Daily Water Requirement per Weight",
      category: "pets",
      subcategory: "birds-hydration",
      description: "Calculate the minimum daily water volume needed for a bird based on its weight.",
      loader: () => import("@/components/calculators/Pets/BirdDailyWaterRequirementPerWeightCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "bird-dehydration-signs-estimator",
      title: "Dehydration Signs Estimator",
      category: "pets",
      subcategory: "birds-hydration",
      description: "Tool to help owners identify early signs of dehydration in birds, which can be subtle.",
      loader: () => import("@/components/calculators/Pets/BirdDehydrationSignsEstimatorCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "bird-antibiotic-dose-reference",
      title: "Antibiotic Dose Reference (mg/kg)",
      category: "pets",
      subcategory: "birds-medication",
      description: "Reference guide for common antibiotic dosages in birds by body weight (mg/kg).",
      loader: () => import("@/components/calculators/Pets/BirdAntibioticDoseReferenceCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "bird-omega-3-supplement-dose-parrots",
      title: "Omega-3 Supplement Dose (for parrots)",
      category: "pets",
      subcategory: "birds-medication",
      description: "Determine the correct daily supplement dosage of Omega-3s for parrots and other large pet birds.",
      loader: () => import("@/components/calculators/Pets/BirdOmega3SupplementDoseParrotsCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "bird-electrolyte-vitamin-c-water-mix",
      title: "Electrolyte & Vitamin C Water Mix Calculator",
      category: "pets",
      subcategory: "birds-medication",
      description: "Calculate the safe concentration for mixing electrolytes and Vitamin C into a bird's drinking water.",
      loader: () => import("@/components/calculators/Pets/BirdElectrolyteVitaminCWaterMixCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "reptile-daily-feeding-ratio-species-age",
      title: "Daily Feeding Ratio (by Species & Age)",
      category: "pets",
      subcategory: "reptiles-nutrition-environment",
      description: "Determine the optimal feeding frequency and ratio of prey/vegetables based on the reptile's species and age.",
      loader: () => import("@/components/calculators/Pets/ReptileDailyFeedingRatioSpeciesAgeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "reptile-calcium-to-phosphorus-ratio",
      title: "Calcium-to-Phosphorus Ratio Calculator",
      category: "pets",
      subcategory: "reptiles-nutrition-environment",
      description: "Calculate the vital **Calcium-to-Phosphorus ratio** of a reptile's diet, which should be maintained above 1:1.",
      loader: () => import("@/components/calculators/Pets/ReptileCalciumToPhosphorusRatioCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "reptile-vitamin-d3-requirement",
      title: "Vitamin D3 Requirement (Supplemental)",
      category: "pets",
      subcategory: "reptiles-nutrition-environment",
      description: "Determine the supplemental D3 dosage needed if UVB lighting is inadequate or unavailable.",
      loader: () => import("@/components/calculators/Pets/ReptileVitaminD3RequirementCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "reptile-feeder-insect-gut-loading-ratio",
      title: "Feeder Insect Gut-Loading Ratio",
      category: "pets",
      subcategory: "reptiles-nutrition-environment",
      description: "Calculate the necessary gut-loading time and nutritional ratio for feeder insects before feeding them to reptiles.",
      loader: () => import("@/components/calculators/Pets/ReptileFeederInsectGutLoadingRatioCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "reptile-dehydration-shedding-risk-index",
      title: "Dehydration & Shedding Risk Index",
      category: "pets",
      subcategory: "reptiles-health",
      description: "Assess the risk of dehydration-related issues, such as poor or stuck shedding.",
      loader: () => import("@/components/calculators/Pets/ReptileDehydrationSheddingRiskIndexCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "reptile-metabolic-bone-disease-risk",
      title: "Metabolic Bone Disease Risk Estimator",
      category: "pets",
      subcategory: "reptiles-health",
      description: "Estimate the risk of **Metabolic Bone Disease (MBD)** based on calcium/D3/UVB light availability.",
      loader: () => import("@/components/calculators/Pets/ReptileMetabolicBoneDiseaseRiskCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "reptile-ideal-humidity-range",
      title: "Ideal Humidity Range Calculator",
      category: "pets",
      subcategory: "reptiles-health",
      description: "Calculate and maintain the correct humidity percentage for a specific reptile species to ensure respiratory health.",
      loader: () => import("@/components/calculators/Pets/ReptileIdealHumidityRangeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "reptile-growth-curve-python-bearded-dragon-gecko",
      title: "Growth Curve by Species (Python, Bearded Dragon, Gecko)",
      category: "pets",
      subcategory: "reptiles-health",
      description: "Track and compare the reptile's growth against standard growth curves for species like Pythons, Bearded Dragons, and Geckos.",
      loader: () => import("@/components/calculators/Pets/ReptileGrowthCurvePythonBeardedDragonGeckoCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "reptile-thermal-gradient-maintenance-power",
      title: "Thermal Gradient Maintenance Power Estimator",
      category: "pets",
      subcategory: "reptiles-health",
      description: "Estimate the wattage (power) needed for heat lamps and heat mats to maintain the required thermal gradient.",
      loader: () => import("@/components/calculators/Pets/ReptileThermalGradientMaintenancePowerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "reptile-dewormer-antibiotic-dose-reference",
      title: "Dewormer & Antibiotic Dose Reference",
      category: "pets",
      subcategory: "reptiles-medication",
      description: "Reference guide for common dewormer and antibiotic dosages in reptiles by body weight.",
      loader: () => import("@/components/calculators/Pets/ReptileDewormerAntibioticDoseReferenceCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "reptile-calcium-d3-supplement",
      title: "Calcium + D3 Supplement Calculator",
      category: "pets",
      subcategory: "reptiles-medication",
      description: "Calculate the required dusting frequency and amount of Calcium and D3 supplement powder for feeders.",
      loader: () => import("@/components/calculators/Pets/ReptileCalciumD3SupplementCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "reptile-fluid-replacement-volume",
      title: "Fluid Replacement Volume Calculator",
      category: "pets",
      subcategory: "reptiles-medication",
      description: "Calculate the necessary volume of subcutaneous fluids for a dehydrated reptile based on its weight and severity.",
      loader: () => import("@/components/calculators/Pets/ReptileFluidReplacementVolumeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "aquarium-volume-rectangular-cylindrical-bowfront",
      title: "Aquarium Volume Calculator (Rectangular / Cylindrical / Bowfront)",
      category: "pets",
      subcategory: "fish-aquatic-volume-stocking",
      description: "Calculate the accurate volume (in Liters or Gallons) of rectangular, cylindrical, or bowfront aquariums.",
      loader: () => import("@/components/calculators/Pets/AquariumVolumeRectangularCylindricalBowfrontCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "aquarium-safe-stocking-density-fish-per-litre",
      title: "Safe Stocking Density (Fish/cm per Litre)",
      category: "pets",
      subcategory: "fish-aquatic-volume-stocking",
      description: "Determine the safe number or length of fish that can be kept in a tank, preventing overstocking and stress.",
      loader: () => import("@/components/calculators/Pets/AquariumSafeStockingDensityFishPerLitreCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "aquarium-filter-flow-rate",
      title: "Filter Flow Rate Calculator",
      category: "pets",
      subcategory: "fish-aquatic-volume-stocking",
      description: "Calculate the minimum required filter flow rate (LPH/GPH) to turn over the tank volume adequately.",
      loader: () => import("@/components/calculators/Pets/AquariumFilterFlowRateCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "aquarium-water-change-volume-planner",
      title: "Water Change Volume Planner",
      category: "pets",
      subcategory: "fish-aquatic-volume-stocking",
      description: "Plan the exact volume of water to be changed to achieve a target percentage reduction in nitrates or other parameters.",
      loader: () => import("@/components/calculators/Pets/AquariumWaterChangeVolumePlannerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "aquarium-heater-wattage-requirement",
      title: "Heater Wattage Requirement",
      category: "pets",
      subcategory: "fish-aquatic-volume-stocking",
      description: "Determine the correct wattage heater needed to maintain the desired water temperature based on tank volume and room temperature.",
      loader: () => import("@/components/calculators/Pets/AquariumHeaterWattageRequirementCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "aquarium-co2-injection-rate-planted-tank",
      title: "CO₂ Injection Rate Calculator (Planted Tank)",
      category: "pets",
      subcategory: "fish-aquatic-volume-stocking",
      description: "Calculate the target CO₂ bubble rate (BPS) and estimate the resulting CO₂ concentration (ppm) for planted aquariums.",
      loader: () => import("@/components/calculators/Pets/AquariumCo2InjectionRatePlantedTankCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "aquarium-ph-adjustment-buffer",
      title: "pH Adjustment (Acid/Base Buffer) Calculator",
      category: "pets",
      subcategory: "fish-aquatic-water-chemistry-nutrition",
      description: "Calculate the required amount of acid or base (buffer) needed to safely adjust the aquarium water's pH level.",
      loader: () => import("@/components/calculators/Pets/AquariumPhAdjustmentBufferCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "aquarium-ammonia-nitrite-cycle-time",
      title: "Ammonia-to-Nitrite Cycle Time Estimator",
      category: "pets",
      subcategory: "fish-aquatic-water-chemistry-nutrition",
      description: "Estimate the time needed for a new aquarium to complete its nitrogen cycle (converting ammonia to nitrite to nitrate).",
      loader: () => import("@/components/calculators/Pets/AquariumAmmoniaNitriteCycleTimeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "aquarium-salt-dosage-therapeutic",
      title: "Aquarium Salt Dosage Calculator (Therapeutic)",
      category: "pets",
      subcategory: "fish-aquatic-water-chemistry-nutrition",
      description: "Calculate the correct, safe dosage of aquarium salt for therapeutic treatment of fish diseases (e.g., Ich).",
      loader: () => import("@/components/calculators/Pets/AquariumSaltDosageTherapeuticCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "aquarium-nitrate-reduction-goal-planner",
      title: "Nitrate Reduction Goal Planner (ppm → water change %)",
      category: "pets",
      subcategory: "fish-aquatic-water-chemistry-nutrition",
      description: "Determine the necessary water change percentage to reduce nitrate levels from the current reading to a safe target level (ppm).",
      loader: () => import("@/components/calculators/Pets/AquariumNitrateReductionGoalPlannerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "fish-food-feeding-rate",
      title: "Fish Food Feeding Rate Calculator",
      category: "pets",
      subcategory: "fish-aquatic-water-chemistry-nutrition",
      description: "Calculate the optimal daily feeding amount based on the total biomass of fish in the tank.",
      loader: () => import("@/components/calculators/Pets/FishFoodFeedingRateCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "oxygen-solubility-vs-temperature-table",
      title: "Oxygen Solubility vs. Temperature Table",
      category: "pets",
      subcategory: "fish-aquatic-water-chemistry-nutrition",
      description: "Reference table showing how the maximum solubility of dissolved oxygen changes with water temperature.",
      loader: () => import("@/components/calculators/Pets/OxygenSolubilityVsTemperatureTableCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "pond-volume-liner-size",
      title: "Pond Volume & Liner Size Calculator",
      category: "pets",
      subcategory: "fish-aquatic-pond-breeding",
      description: "Calculate the volume of water in a pond and the minimum required liner size based on length, width, and depth.",
      loader: () => import("@/components/calculators/Pets/PondVolumeLinerSizeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "koi-feed-planner-temp-weight",
      title: "Koi Feed Planner (Temp + Weight)",
      category: "pets",
      subcategory: "fish-aquatic-pond-breeding",
      description: "Plan the optimal feeding rate for Koi fish based on their body weight and the current water temperature.",
      loader: () => import("@/components/calculators/Pets/KoiFeedPlannerTempWeightCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "breeding-tank-volume-planner",
      title: "Breeding Tank Volume Planner",
      category: "pets",
      subcategory: "fish-aquatic-pond-breeding",
      description: "Calculate the ideal volume and dimensions for a dedicated fish breeding or fry grow-out tank.",
      loader: () => import("@/components/calculators/Pets/BreedingTankVolumePlannerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "small-mammal-daily-calorie-needs",
      title: "Daily Calorie Needs (Species Specific)",
      category: "pets",
      subcategory: "small-mammals-nutrition-weight",
      description: "Calculate the specific daily calorie and energy requirements for species like rabbits, guinea pigs, and hamsters.",
      loader: () => import("@/components/calculators/Pets/SmallMammalDailyCalorieNeedsCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "small-mammal-weight-maintenance-gain-loss-planner",
      title: "Weight Maintenance vs. Gain/Loss Planner",
      category: "pets",
      subcategory: "small-mammals-nutrition-weight",
      description: "Plan calorie targets for weight maintenance, controlled weight gain, or safe weight loss for small mammals.",
      loader: () => import("@/components/calculators/Pets/SmallMammalWeightMaintenanceGainLossPlannerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "small-mammal-hay-pellet-intake",
      title: "Hay & Pellet Intake Calculator",
      category: "pets",
      subcategory: "small-mammals-nutrition-weight",
      description: "Calculate the ideal daily ratio and total amount of hay vs. pellets for herbivores like rabbits and guinea pigs.",
      loader: () => import("@/components/calculators/Pets/SmallMammalHayPelletIntakeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "small-mammal-fiber-protein-ratio",
      title: "Fiber & Protein Ratio Calculator",
      category: "pets",
      subcategory: "small-mammals-nutrition-weight",
      description: "Determine the appropriate ratio of fiber and protein in the diet, crucial for gut health in species like rabbits.",
      loader: () => import("@/components/calculators/Pets/SmallMammalFiberProteinRatioCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "guinea-pig-vitamin-c-requirement",
      title: "Vitamin C Requirement (Guinea Pig)",
      category: "pets",
      subcategory: "small-mammals-nutrition-weight",
      description: "Calculate the daily supplemental Vitamin C requirement, which guinea pigs cannot synthesize themselves.",
      loader: () => import("@/components/calculators/Pets/GuineaPigVitaminCRequirementCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "small-mammal-calcium-intake-limit",
      title: "Calcium Intake Limit (Bladder Stone Prevention)",
      category: "pets",
      subcategory: "small-mammals-nutrition-weight",
      description: "Determine the safe daily limit for calcium intake to reduce the risk of bladder stones in susceptible species.",
      loader: () => import("@/components/calculators/Pets/SmallMammalCalciumIntakeLimitCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "rabbit-treat-calories-safe-portion",
      title: "Rabbit Treat Calories & Safe Portion",
      category: "pets",
      subcategory: "small-mammals-nutrition-weight",
      description: "Calculate the calorie content of treats and the safe maximum portion size for rabbits.",
      loader: () => import("@/components/calculators/Pets/RabbitTreatCaloriesSafePortionCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "ferret-protein-fat-ratio-checker",
      title: "Ferret Protein/Fat Ratio Checker",
      category: "pets",
      subcategory: "small-mammals-nutrition-weight",
      description: "Check the diet to ensure it meets the high protein and fat requirements for obligate carnivores like ferrets.",
      loader: () => import("@/components/calculators/Pets/FerretProteinFatRatioCheckerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "rabbit-temperature-stress-risk-heatstroke",
      title: "Temperature Stress Risk (Rabbit Heatstroke)",
      category: "pets",
      subcategory: "small-mammals-health-toxicology",
      description: "Assess the risk of heatstroke in rabbits based on ambient temperature and humidity.",
      loader: () => import("@/components/calculators/Pets/RabbitTemperatureStressRiskHeatstrokeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "small-mammal-dehydration-risk-checker",
      title: "Dehydration Risk Checker",
      category: "pets",
      subcategory: "small-mammals-health-toxicology",
      description: "Tool to check for subtle signs of dehydration in small mammals, which can quickly become critical.",
      loader: () => import("@/components/calculators/Pets/SmallMammalDehydrationRiskCheckerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "small-mammal-common-toxic-foods-reference",
      title: "Common Toxic Foods Reference",
      category: "pets",
      subcategory: "small-mammals-health-toxicology",
      description: "Reference guide for common toxic or dangerous foods for small pets (e.g., certain seeds, nuts, or sugary items).",
      loader: () => import("@/components/calculators/Pets/SmallMammalCommonToxicFoodsReferenceCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "small-mammal-safe-vegetables-fruits-portion",
      title: "Safe Vegetables & Fruits Portion Calculator",
      category: "pets",
      subcategory: "small-mammals-health-toxicology",
      description: "Calculate the maximum safe daily portion of various vegetables and fruits to prevent digestive upset.",
      loader: () => import("@/components/calculators/Pets/SmallMammalSafeVegetablesFruitsPortionCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "small-mammal-parasite-treatment-dose-reference",
      title: "Parasite Treatment Dose Reference",
      category: "pets",
      subcategory: "small-mammals-health-toxicology",
      description: "Reference guide for common anti-parasitic medication dosages (e.g., for mites, fleas, or intestinal parasites).",
      loader: () => import("@/components/calculators/Pets/SmallMammalParasiteTreatmentDoseReferenceCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "small-mammal-cage-size-requirement",
      title: "Cage Size Requirement Calculator",
      category: "pets",
      subcategory: "small-mammals-behavior-care",
      description: "Calculate the minimum cage or enclosure size required for specific small mammal species (e.g., minimum cubic feet).",
      loader: () => import("@/components/calculators/Pets/SmallMammalCageSizeRequirementCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "small-mammal-exercise-time-planner",
      title: "Exercise Time Planner (Run Time per Day)",
      category: "pets",
      subcategory: "small-mammals-behavior-care",
      description: "Plan the necessary amount of daily free-roam or wheel/run time to ensure adequate exercise and enrichment.",
      loader: () => import("@/components/calculators/Pets/SmallMammalExerciseTimePlannerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "small-mammal-bedding-replacement-frequency",
      title: "Bedding Replacement Frequency Estimator",
      category: "pets",
      subcategory: "small-mammals-behavior-care",
      description: "Estimate how often bedding needs to be fully replaced to maintain hygiene and prevent ammonia buildup.",
      loader: () => import("@/components/calculators/Pets/SmallMammalBeddingReplacementFrequencyCalculator"),
      urlStyle: "flat"
    }
];
