// AUTO-GENERATED by scripts/split-registry.cjs — DO NOT EDIT BY HAND.
// Per-category slice of the master CalculatorEntry registry.
// Re-run `node scripts/split-registry.cjs` after editing the master.

import type { CalculatorEntry } from "@/data/calculatorRegistry";

export const healthEntries: CalculatorEntry[] = [
  {
      slug: "calorie-calculator",
      title: "Calorie Calculator",
      category: "health",
      subcategory: "general",
      description: "Determine your daily calorie needs for weight loss, maintenance, or weight gain based on your activity level and goals.",
      loader: () => import("@/components/calculators/Health/DailyCalorieNeedsGoalCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "bmi-calculator",
      title: "BMI Calculator",
      category: "health",
      subcategory: "general",
      description: "Calculate your Body Mass Index (BMI) and find out if you're at a healthy weight.",
      loader: () => import("@/components/calculators/Health/BmiBodyMassIndexCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "bmr-calculator",
      title: "BMR Calculator",
      category: "health",
      subcategory: "general",
      description: "Calculate your Basal Metabolic Rate (BMR) to understand how many calories your body burns at rest.",
      loader: () => import("@/components/calculators/Health/BmrMifflinStJeorCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "body-fat-calculator",
      title: "Body Fat Calculator",
      category: "health",
      subcategory: "general",
      description: "Estimate your body fat percentage using the U.S. Navy Method.",
      loader: () => import("@/components/calculators/Health/BodyFatUsNavy3SitesCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "ideal-weight-calculator",
      title: "Ideal Weight Calculator",
      category: "health",
      subcategory: "general",
      description: "Find your ideal body weight range based on various scientific formulas.",
      loader: () => import("@/components/calculators/Health/IdealWeightRangeHamwiDevineMillerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "tdee-daily-energy-expenditure",
      title: "TDEE — Total Daily Energy Expenditure Calculator",
      category: "health",
      subcategory: "body-metrics-weight-management",
      description: "Estimate your Total Daily Energy Expenditure (TDEE). Learn how many calories you need daily to maintain, lose, or gain weight.",
      loader: () => import("@/components/calculators/Health/TdeeDailyEnergyExpenditureCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "bmi-body-mass-index",
      title: "BMI — Body Mass Index Calculator",
      category: "health",
      subcategory: "body-metrics-weight-management",
      description: "Calculate your Body Mass Index (BMI) instantly. Determine if you are in a healthy weight range based on your height and weight.",
      loader: () => import("@/components/calculators/Health/BmiBodyMassIndexCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "bmr-mifflin-st-jeor",
      title: "BMR — Basal Metabolic Rate (Mifflin-St Jeor)",
      category: "health",
      subcategory: "body-metrics-weight-management",
      description: "Calculate your Basal Metabolic Rate (BMR) using the Mifflin-St Jeor equation. Find out exactly how many calories your body burns at rest.",
      loader: () => import("@/components/calculators/Health/BmrMifflinStJeorCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "body-fat-us-navy-3-sites",
      title: "Body Fat % (US Navy / 3-sites)",
      category: "health",
      subcategory: "body-metrics-weight-management",
      description: "Estimate your body fat percentage using the US Navy method. Track your body composition progress accurately without expensive equipment.",
      loader: () => import("@/components/calculators/Health/BodyFatUsNavy3SitesCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "ideal-weight-range-hamwi-devine-miller",
      title: "Ideal Weight Range (Hamwi/Devine/Miller)",
      category: "health",
      subcategory: "body-metrics-weight-management",
      description: "Discover your ideal weight range. Compare results from Hamwi, Devine, and Miller formulas to set realistic and healthy weight goals.",
      loader: () => import("@/components/calculators/Health/IdealWeightRangeHamwiDevineMillerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "waist-to-height-ratio",
      title: "Waist-to-Height Ratio Checker",
      category: "health",
      subcategory: "body-metrics-weight-management",
      description: "Calculate your Waist-to-Height Ratio (WHtR). Use this simple yet effective metric to assess central obesity and cardiovascular health risks.",
      loader: () => import("@/components/calculators/Health/WaistToHeightRatioCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "body-surface-area-bsa",
      title: "Body Surface Area (BSA) Calculator",
      category: "health",
      subcategory: "body-metrics-weight-management",
      description: "Calculate Body Surface Area (BSA) accurately. Essential for determining medical dosages and assessing metabolic parameters.",
      loader: () => import("@/components/calculators/Health/BodySurfaceAreaBsaCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "daily-calorie-needs-goal",
      title: "Daily Calorie Needs (Goal-based)",
      category: "health",
      subcategory: "body-metrics-weight-management",
      description: "Determine daily calorie needs for your specific goal. Create a personalized nutrition plan for weight loss, maintenance, or muscle gain.",
      loader: () => import("@/components/calculators/Health/DailyCalorieNeedsGoalCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "weight-loss-date-deficit-planner",
      title: "Weight Loss Date & Deficit Planner",
      category: "health",
      subcategory: "body-metrics-weight-management",
      description: "Plan your weight loss journey timeline. Calculate the exact date you will reach your target weight based on your daily calorie deficit.",
      loader: () => import("@/components/calculators/Health/WeightLossDateDeficitPlannerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "macro-split-planner",
      title: "Macro Split Planner (Protein/Carb/Fat)",
      category: "health",
      subcategory: "nutrition-macros",
      description: "Optimize your diet with a macro split planner. Calculate the perfect ratio of proteins, carbohydrates, and fats for your fitness goals.",
      loader: () => import("@/components/calculators/Health/MacroSplitPlannerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "protein-intake-by-goal",
      title: "Protein Intake by Goal (cut/bulk/maintain)",
      category: "health",
      subcategory: "nutrition-macros",
      description: "Calculate your optimal daily protein intake. Find out exactly how many grams you need to build muscle or preserve mass while dieting.",
      loader: () => import("@/components/calculators/Health/ProteinIntakeByGoalCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "carb-target-low-carb-keto",
      title: "Carb Target (incl. low-carb/keto ranges)",
      category: "health",
      subcategory: "nutrition-macros",
      description: "Set your daily carbohydrate target. Perfect for planning Low-Carb, Keto, or balanced diets to fuel your energy needs effectively.",
      loader: () => import("@/components/calculators/Health/CarbTargetLowCarbKetoCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "fat-intake-range-amdr",
      title: "Fat Intake Range (AMDR)",
      category: "health",
      subcategory: "nutrition-macros",
      description: "Determine healthy fat intake ranges based on AMDR. Ensure hormonal health and satiety by consuming the right amount of dietary fats.",
      loader: () => import("@/components/calculators/Health/FatIntakeRangeAmdrCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "fiber-intake-target",
      title: "Fiber Intake Target (by kcal/sexo)",
      category: "health",
      subcategory: "nutrition-macros",
      description: "Calculate your recommended daily fiber intake. Improve digestion and gut health by hitting accurate fiber goals based on calorie intake.",
      loader: () => import("@/components/calculators/Health/FiberIntakeTargetCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "water-intake-per-day",
      title: "Water Intake per Day (by weight/activity/climate)",
      category: "health",
      subcategory: "nutrition-macros",
      description: "Calculate your daily water intake requirements. Stay hydrated by adjusting for body weight, activity level, and climate conditions.",
      loader: () => import("@/components/calculators/Health/WaterIntakePerDayCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "meal-calories-split",
      title: "Meal Calories Split (breakfast/lunch/dinner/snacks)",
      category: "health",
      subcategory: "nutrition-macros",
      description: "Split your daily calories across meals efficiently. Plan balanced portions for breakfast, lunch, dinner, and snacks to control hunger.",
      loader: () => import("@/components/calculators/Health/MealCaloriesSplitCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "running-pace-speed-splits",
      title: "Running Pace, Speed & Split Calculator",
      category: "health",
      subcategory: "training-performance",
      description: "Calculate running pace, speed, and splits. An essential tool for runners to plan race times and monitor training performance.",
      loader: () => import("@/components/calculators/Health/RunningPaceSpeedSplitsCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "calories-burned-met",
      title: "Calories Burned by Activity (MET-based)",
      category: "health",
      subcategory: "training-performance",
      description: "Estimate calories burned during exercise. Use MET values to calculate energy expenditure for running, cycling, swimming, and more.",
      loader: () => import("@/components/calculators/Health/CaloriesBurnedMetCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "heart-rate-zones",
      title: "Heart Rate Zones (Karvonen/percentages)",
      category: "health",
      subcategory: "training-performance",
      description: "Calculate your training heart rate zones. Use the Karvonen method to find the optimal intensity for fat loss or cardio improvement.",
      loader: () => import("@/components/calculators/Health/HeartRateZonesCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "one-rep-max-1rm-epley-brzycki",
      title: "1RM — One-Rep Max (Epley/Brzycki)",
      category: "health",
      subcategory: "training-performance",
      description: "Calculate your One-Rep Max (1RM) safely. Estimate your maximum lifting strength using proven Epley and Brzycki formulas.",
      loader: () => import("@/components/calculators/Health/OneRepMax1rmEpleyBrzyckiCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "steps-distance-calories-converter",
      title: "Steps ↔ Distance ↔ Calories Converter",
      category: "health",
      subcategory: "training-performance",
      description: "Convert steps into distance and calories burned. Track your daily walking activity and visualize its impact on your fitness goals.",
      loader: () => import("@/components/calculators/Health/StepsDistanceCaloriesConverterCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "ovulation-fertile-window",
      title: "Ovulation & Fertile Window Estimator",
      category: "health",
      subcategory: "women-s-health",
      description: "Predict your ovulation and fertile window accurately. Maximize your chances of conception by tracking your most fertile days.",
      loader: () => import("@/components/calculators/Health/OvulationFertileWindowCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "pregnancy-due-date-naegele",
      title: "Pregnancy Due-Date (Naegele)",
      category: "health",
      subcategory: "women-s-health",
      description: "Calculate your pregnancy due date using Naegele's rule. Estimate the arrival of your baby based on your last menstrual period.",
      loader: () => import("@/components/calculators/Health/PregnancyDueDateNaegeleCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "pregnancy-weight-gain-range-bmi-aware",
      title: "Pregnancy Weight-Gain Range (BMI-aware)",
      category: "health",
      subcategory: "women-s-health",
      description: "Monitor healthy pregnancy weight gain. Get recommended weight ranges based on your pre-pregnancy BMI for a healthy baby and mom.",
      loader: () => import("@/components/calculators/Health/PregnancyWeightGainRangeBmiAwareCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "tdee-gestation-adjusted",
      title: "Gestational TDEE (educational)",
      category: "health",
      subcategory: "women-s-health",
      description: "Estimate energy needs during pregnancy. Calculate adjusted TDEE to ensure adequate nutrition for fetal development and maternal health.",
      loader: () => import("@/components/calculators/Health/TdeeGestationAdjustedCalculator"),
      urlStyle: "flat"
    }
];
