// AUTO-GENERATED by scripts/split-registry.cjs — DO NOT EDIT BY HAND.
// Per-category slice of the master CalculatorEntry registry.
// Re-run `node scripts/split-registry.cjs` after editing the master.

import type { CalculatorEntry } from "@/data/calculatorRegistry";

export const mathEntries: CalculatorEntry[] = [
  {
      slug: "percent-of-total",
      title: "Percent of Total Calculator",
      category: "math",
      subcategory: "percent-ratio-fractions",
      description: "Calculate the percentage of a total value. Quickly determine what part of the whole a specific number represents.",
      loader: () => import("@/components/calculators/Math/PercentOfTotalCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "gpa-calculator",
      title: "GPA Calculator",
      category: "math",
      subcategory: "grades-gpa",
      description: "Calculate your GPA using course credits and letter grades on a common 4.0 scale.",
      loader: () => import("@/components/calculators/Math/GpaCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "percent-increase-decrease",
      title: "Percent Increase/Decrease Calculator",
      category: "math",
      subcategory: "percent-ratio-fractions",
      description: "Calculate the percentage increase or decrease between two numbers. Essential for tracking growth, discounts, or price changes.",
      loader: () => import("@/components/calculators/Math/PercentIncreaseDecreaseCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "percent-change",
      title: "Percent Change Calculator",
      category: "math",
      subcategory: "percent-ratio-fractions",
      description: "Find the percent change between an old value and a new value. Useful for analyzing financial data, statistics, and performance metrics.",
      loader: () => import("@/components/calculators/Math/PercentChangeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "fraction-decimal-converter",
      title: "Fraction ⇄ Decimal Converter",
      category: "math",
      subcategory: "percent-ratio-fractions",
      description: "Convert fractions to decimals and vice versa. Instantly transform 1/4 to 0.25 or any decimal back into its simplest fraction form.",
      loader: () => import("@/components/calculators/Math/FractionDecimalConverterCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "fraction-reducer-simplifier",
      title: "Fraction Reducer / Simplifier",
      category: "math",
      subcategory: "percent-ratio-fractions",
      description: "Simplify fractions instantly. Reduce complex fractions to their lowest terms for easier math and clearer answers.",
      loader: () => import("@/components/calculators/Math/FractionReducerSimplifierCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "ratio-calculator",
      title: "Ratio Calculator (A:B = C:D)",
      category: "math",
      subcategory: "percent-ratio-fractions",
      description: "Solve ratio problems easily. Find the missing value in a proportion (A:B = C:D) to scale recipes, images, or designs.",
      loader: () => import("@/components/calculators/Math/RatioCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "percent-error-calculator",
      title: "Percent Error Calculator",
      category: "math",
      subcategory: "percent-ratio-fractions",
      description: "Calculate percent error in experimental measurements. Compare your observed value to the true theoretical value to check accuracy.",
      loader: () => import("@/components/calculators/Math/PercentErrorCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "proportion-solver",
      title: "Proportion Solver (Cross-Multiplication)",
      category: "math",
      subcategory: "percent-ratio-fractions",
      description: "Solve proportions using cross-multiplication. Find the value of X in any proportional equation quickly and accurately.",
      loader: () => import("@/components/calculators/Math/ProportionSolverCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "quadratic-equation-solver",
      title: "Quadratic Equation Solver (ax²+bx+c)",
      category: "math",
      subcategory: "algebra-equations",
      description: "Solve quadratic equations instantly. Find the roots (x-intercepts), discriminant, and vertex of any parabola using the quadratic formula.",
      loader: () => import("@/components/calculators/Math/QuadraticEquationSolverCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "linear-equation-solver-1-2-variables",
      title: "Linear Equation Solver (1–2 variables)",
      category: "math",
      subcategory: "algebra-equations",
      description: "Solve linear equations with one or two variables. Find the value of X (and Y) for simple algebraic problems and systems.",
      loader: () => import("@/components/calculators/Math/LinearEquationSolver12VariablesCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "system-of-equations-substitution-elimination",
      title: "System of Equations Solver (Substitution/Elimination)",
      category: "math",
      subcategory: "algebra-equations",
      description: "Solve systems of linear equations. Use substitution or elimination methods to find the intersection point of two lines.",
      loader: () => import("@/components/calculators/Math/SystemOfEquationsSubstitutionEliminationCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "exponent-power-calculator",
      title: "Exponent & Power Calculator",
      category: "math",
      subcategory: "algebra-equations",
      description: "Calculate exponents and powers. Raise any base number to a positive, negative, or fractional power instantly.",
      loader: () => import("@/components/calculators/Math/ExponentPowerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "log-antilog-base-10-e",
      title: "Log / Antilog (base 10/e) Calculator",
      category: "math",
      subcategory: "algebra-equations",
      description: "Calculate logarithms and antilogarithms. Solve for Log base 10 or Natural Log (ln) base e for advanced math and science.",
      loader: () => import("@/components/calculators/Math/LogAntilogBase10ECalculator"),
      urlStyle: "flat"
    },
  {
      slug: "scientific-notation-standard-form",
      title: "Scientific Notation ⇄ Standard Form",
      category: "math",
      subcategory: "algebra-equations",
      description: "Convert numbers to Scientific Notation. Transform very large or small numbers into standard exponential form (e.g., 1.5 x 10^6).",
      loader: () => import("@/components/calculators/Math/ScientificNotationStandardFormCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "polynomial-factorization-helper",
      title: "Polynomial Factorization Helper",
      category: "math",
      subcategory: "algebra-equations",
      description: "Factor polynomials efficiently. Break down algebraic expressions into their simplest factors to solve complex equations.",
      loader: () => import("@/components/calculators/Math/PolynomialFactorizationHelperCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "root-radical-simplifier",
      title: "Root/Radical Simplifier",
      category: "math",
      subcategory: "algebra-equations",
      description: "Simplify square roots and radicals. Convert unsimplified radicals into their simplest mixed radical form (e.g., √8 to 2√2).",
      loader: () => import("@/components/calculators/Math/RootRadicalSimplifierCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "gcf-gcd-calculator",
      title: "GCF / GCD Calculator",
      category: "math",
      subcategory: "number-theory-discrete",
      description: "Find the Greatest Common Factor (GCF) or Greatest Common Divisor (GCD). Identify the largest number that divides two or more integers.",
      loader: () => import("@/components/calculators/Math/GcfGcdCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "lcm-calculator",
      title: "LCM Calculator",
      category: "math",
      subcategory: "number-theory-discrete",
      description: "Calculate the Least Common Multiple (LCM). Find the smallest positive integer that is divisible by two or more numbers.",
      loader: () => import("@/components/calculators/Math/LcmCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "prime-factorization-tool",
      title: "Prime Factorization Tool",
      category: "math",
      subcategory: "number-theory-discrete",
      description: "Find the prime factorization of any number. Break down composite numbers into their prime components (e.g., 12 = 2² × 3).",
      loader: () => import("@/components/calculators/Math/PrimeFactorizationToolCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "modulo-remainder-calculator",
      title: "Modulo (Remainder) Calculator",
      category: "math",
      subcategory: "number-theory-discrete",
      description: "Calculate the modulo (remainder). Find the remainder of a division operation, essential for computer science and cryptography.",
      loader: () => import("@/components/calculators/Math/ModuloRemainderCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "permutations-combinations-npr-ncr",
      title: "Permutations & Combinations (nPr / nCr)",
      category: "math",
      subcategory: "number-theory-discrete",
      description: "Calculate permutations (nPr) and combinations (nCr). Determine the number of ways to arrange or select items from a set.",
      loader: () => import("@/components/calculators/Math/PermutationsCombinationsNprNcrCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "random-number-generator-ranges",
      title: "Random Number Generator (ranges)",
      category: "math",
      subcategory: "number-theory-discrete",
      description: "Generate random numbers within a specific range. Perfect for statistical sampling, games, or picking a random winner.",
      loader: () => import("@/components/calculators/Math/RandomNumberGeneratorRangesCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "triangle-solver-sss-sas-asa",
      title: "Triangle Solver (SSS/SAS/ASA)",
      category: "math",
      subcategory: "geometry-trig",
      description: "Solve triangles using SSS, SAS, or ASA methods. Calculate missing side lengths and angles using the Law of Sines and Cosines.",
      loader: () => import("@/components/calculators/Math/TriangleSolverSssSasAsaCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "circle-area-circumference",
      title: "Circle Area / Circumference Calculator",
      category: "math",
      subcategory: "geometry-trig",
      description: "Calculate circle metrics. Find the area, circumference, radius, and diameter of a circle instantly.",
      loader: () => import("@/components/calculators/Math/CircleAreaCircumferenceCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "rectangle-parallelogram-area",
      title: "Rectangle & Parallelogram Area Calculator",
      category: "math",
      subcategory: "geometry-trig",
      description: "Calculate the area of rectangles and parallelograms. Find the surface area and perimeter for construction or homework.",
      loader: () => import("@/components/calculators/Math/RectangleParallelogramAreaCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "pythagorean-theorem-solver",
      title: "Pythagorean Theorem Solver",
      category: "math",
      subcategory: "geometry-trig",
      description: "Solve for the hypotenuse or legs of a right triangle. Use a² + b² = c² to find missing distances easily.",
      loader: () => import("@/components/calculators/Math/PythagoreanTheoremSolverCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "trig-functions-angle-side-finder",
      title: "Trig Functions (sin/cos/tan) Angle/Side Finder",
      category: "math",
      subcategory: "geometry-trig",
      description: "Calculate Trigonometric functions. Find Sine, Cosine, and Tangent values to determine unknown angles and sides in right triangles.",
      loader: () => import("@/components/calculators/Math/TrigFunctionsAngleSideFinderCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "shapes-area-volume-pack",
      title: "2D/3D Shapes Area & Volume Pack",
      category: "math",
      subcategory: "geometry-trig",
      description: "Calculate area and volume for 2D and 3D shapes. Comprehensive tool for cubes, cylinders, spheres, cones, and more.",
      loader: () => import("@/components/calculators/Math/ShapesAreaVolumePackCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "angle-converter-deg-rad",
      title: "Angle Converter (deg ↔ rad)",
      category: "math",
      subcategory: "geometry-trig",
      description: "Convert angles between Degrees and Radians. Essential for calculus and trigonometry calculations.",
      loader: () => import("@/components/calculators/Math/AngleConverterDegRadCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "mean-median-mode",
      title: "Mean, Median, Mode Calculator",
      category: "math",
      subcategory: "statistics-probability",
      description: "Calculate Mean, Median, and Mode. Find the average, middle value, and most frequent number in any data set.",
      loader: () => import("@/components/calculators/Math/MeanMedianModeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "standard-deviation-variance-pop-sample",
      title: "Standard Deviation & Variance (pop/sample)",
      category: "math",
      subcategory: "statistics-probability",
      description: "Calculate Standard Deviation and Variance. Measure data dispersion and variability for population or sample datasets.",
      loader: () => import("@/components/calculators/Math/StandardDeviationVariancePopSampleCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "z-score-percentile-finder",
      title: "Z-Score & Percentile Finder",
      category: "math",
      subcategory: "statistics-probability",
      description: "Find Z-Scores and Percentiles. Standardize data points to understand their position relative to the mean in a normal distribution.",
      loader: () => import("@/components/calculators/Math/ZScorePercentileFinderCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "linear-interpolation-extrapolation",
      title: "Linear Interpolation / Extrapolation",
      category: "math",
      subcategory: "statistics-probability",
      description: "Perform Linear Interpolation. Estimate unknown values that fall between two known data points on a line.",
      loader: () => import("@/components/calculators/Math/LinearInterpolationExtrapolationCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "binomial-probability-calculator",
      title: "Binomial Probability Calculator",
      category: "math",
      subcategory: "statistics-probability",
      description: "Calculate Binomial Probability. Determine the likelihood of a specific number of successes in a series of independent experiments.",
      loader: () => import("@/components/calculators/Math/BinomialProbabilityCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "normal-cdf-pdf-estimator",
      title: "Normal CDF / PDF Quick Estimator",
      category: "math",
      subcategory: "statistics-probability",
      description: "Estimate Normal Distribution values. Calculate Cumulative Distribution Function (CDF) and Probability Density Function (PDF) probabilities.",
      loader: () => import("@/components/calculators/Math/NormalCdfPdfEstimatorCalculator"),
      urlStyle: "flat"
    }
];
