// AUTO-GENERATED by scripts/split-registry.cjs — DO NOT EDIT BY HAND.
// Per-category slice of the master CalculatorEntry registry.
// Re-run `node scripts/split-registry.cjs` after editing the master.

import type { CalculatorEntry } from "@/data/calculatorRegistry";

export const conversionEntries: CalculatorEntry[] = [
  {
      slug: "length-m-ft-in",
      title: "Length: m ↔ ft ↔ in",
      category: "conversion",
      subcategory: "core-units",
      description: "Convert length units instantly. Quickly transform meters to feet, inches to centimeters, and handle both metric and imperial measurements with precision.",
      loader: () => import("@/components/calculators/Conversion/LengthMFtInCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "area-m2-ft2",
      title: "Area: m² ↔ ft²",
      category: "conversion",
      subcategory: "core-units",
      description: "Calculate area conversions for real estate and land. Convert square meters to square feet (m² to sq ft) and other area units accurately.",
      loader: () => import("@/components/calculators/Conversion/AreaM2Ft2Calculator"),
      urlStyle: "flat"
    },
  {
      slug: "volume-l-ml-gal-oz",
      title: "Volume: L ↔ mL ↔ gal ↔ oz",
      category: "conversion",
      subcategory: "core-units",
      description: "Convert liquid volume units easily. Switch between liters, milliliters, gallons, and fluid ounces for cooking, science, or industrial needs.",
      loader: () => import("@/components/calculators/Conversion/VolumeLMlGalOzCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "mass-kg-lb-oz",
      title: "Mass: kg ↔ lb ↔ oz",
      category: "conversion",
      subcategory: "core-units",
      description: "Convert weight and mass units. Instantly calculate kilograms to pounds (kg to lbs), ounces to grams, and more for fitness or shipping.",
      loader: () => import("@/components/calculators/Conversion/MassKgLbOzCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "temperature-c-f-k",
      title: "Temperature: °C ↔ °F ↔ K",
      category: "conversion",
      subcategory: "core-units",
      description: "Convert temperature readings. Switch between Celsius (°C), Fahrenheit (°F), and Kelvin (K) for weather, science, and cooking applications.",
      loader: () => import("@/components/calculators/Conversion/TemperatureCFKCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "density-g-per-ml-kg-per-m3",
      title: "Density: g/mL ↔ kg/m³",
      category: "conversion",
      subcategory: "core-units",
      description: "Calculate density conversions. Transform grams per milliliter to kilograms per cubic meter for chemistry and physics calculations.",
      loader: () => import("@/components/calculators/Conversion/DensityGPerMlKgPerM3Calculator"),
      urlStyle: "flat"
    },
  {
      slug: "angle-deg-rad",
      title: "Angle: deg ↔ rad",
      category: "conversion",
      subcategory: "core-units",
      description: "Convert angles between degrees and radians. Essential tool for trigonometry, geometry, and engineering calculations.",
      loader: () => import("@/components/calculators/Conversion/AngleDegRadCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "speed-mps-kmph-mph",
      title: "Speed: m/s ↔ km/h ↔ mph",
      category: "conversion",
      subcategory: "core-units",
      description: "Convert speed and velocity units. Calculate meters per second, kilometers per hour, and miles per hour (mph) for travel and physics.",
      loader: () => import("@/components/calculators/Conversion/SpeedMpsKmphMphCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "force-n-lbf",
      title: "Force: N ↔ lbf",
      category: "conversion",
      subcategory: "mechanics-pressure",
      description: "Convert force units accurately. Transform Newtons (N) to pound-force (lbf) for engineering and mechanical physics problems.",
      loader: () => import("@/components/calculators/Conversion/ForceNLbfCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "energy-j-cal-kwh",
      title: "Energy: J ↔ cal ↔ kWh",
      category: "conversion",
      subcategory: "mechanics-pressure",
      description: "Convert energy units. Switch between Joules (J), calories (cal), and kilowatt-hours (kWh) for nutrition and electrical calculations.",
      loader: () => import("@/components/calculators/Conversion/EnergyJCalKwhCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "power-w-hp",
      title: "Power: W ↔ hp",
      category: "conversion",
      subcategory: "mechanics-pressure",
      description: "Convert power units instantly. Calculate Watts (W) to mechanical or metric Horsepower (hp) for engines and motors.",
      loader: () => import("@/components/calculators/Conversion/PowerWHpCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "pressure-pa-bar-psi",
      title: "Pressure: Pa ↔ bar ↔ psi",
      category: "conversion",
      subcategory: "mechanics-pressure",
      description: "Convert pressure units for tires and hydraulics. Transform Pascals (Pa), Bar, and PSI (pounds per square inch) accurately.",
      loader: () => import("@/components/calculators/Conversion/PressurePaBarPsiCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "torque-nm-lbfft",
      title: "Torque: N·m ↔ lbf·ft",
      category: "conversion",
      subcategory: "mechanics-pressure",
      description: "Convert torque settings. Switch between Newton-meters (Nm) and pound-feet (lb-ft) for automotive and machinery mechanics.",
      loader: () => import("@/components/calculators/Conversion/TorqueNmLbfftCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "work-potential-energy",
      title: "Work & Potential Energy",
      category: "conversion",
      subcategory: "mechanics-pressure",
      description: "Calculate work and gravitational potential energy. Convert between related mechanical units to solve physics equations.",
      loader: () => import("@/components/calculators/Conversion/WorkPotentialEnergyCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "time-ms-s-min-hr",
      title: "Time: ms ↔ s ↔ min ↔ hr",
      category: "conversion",
      subcategory: "time-frequency",
      description: "Convert time durations easily. Transform milliseconds, seconds, minutes, and hours for scientific timing or project planning.",
      loader: () => import("@/components/calculators/Conversion/TimeMsSMinHrCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "frequency-hz-khz-mhz",
      title: "Frequency: Hz ↔ kHz ↔ MHz",
      category: "conversion",
      subcategory: "time-frequency",
      description: "Convert frequency units. Switch between Hertz (Hz), Kilohertz (kHz), and Megahertz (MHz) for audio and electronics.",
      loader: () => import("@/components/calculators/Conversion/FrequencyHzKhzMhzCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "period-frequency",
      title: "Period ↔ Frequency",
      category: "conversion",
      subcategory: "time-frequency",
      description: "Calculate the relationship between period and frequency. Convert time cycles (T) to frequency (f) and vice-versa instantly.",
      loader: () => import("@/components/calculators/Conversion/PeriodFrequencyCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "frame-rate-fps-hz",
      title: "Frame Rate: fps ↔ Hz",
      category: "conversion",
      subcategory: "time-frequency",
      description: "Convert video frame rates to refresh rates. Match FPS (Frames Per Second) with monitor Hz for smooth video playback.",
      loader: () => import("@/components/calculators/Conversion/FrameRateFpsHzCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "clock-time-timezone-shift",
      title: "Clock Time & Timezone Shift",
      category: "conversion",
      subcategory: "time-frequency",
      description: "Calculate time differences. Shift clock times across different time zones to plan meetings and travel effectively.",
      loader: () => import("@/components/calculators/Conversion/ClockTimeTimezoneShiftCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "bytes-b-kb-mb-gb-tb",
      title: "Bytes: B ↔ kB ↔ MB ↔ GB ↔ TB",
      category: "conversion",
      subcategory: "computing-data",
      description: "Convert digital storage sizes. Transform Bytes to Kilobytes, Megabytes (MB), Gigabytes (GB), and Terabytes (TB) for data management.",
      loader: () => import("@/components/calculators/Conversion/BytesBKbMbGbTbCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "bits-b-kb-mb-gb",
      title: "Bits: b ↔ kb ↔ Mb ↔ Gb",
      category: "conversion",
      subcategory: "computing-data",
      description: "Convert network data units. Switch between bits, kilobits, megabits (Mb), and gigabits (Gb) to understand network speeds.",
      loader: () => import("@/components/calculators/Conversion/BitsBKbMbGbCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "binary-decimal-prefixes",
      title: "Binary ↔ Decimal prefixes (KiB ↔ KB)",
      category: "conversion",
      subcategory: "computing-data",
      description: "Understand storage definitions. Convert between binary prefixes (KiB, MiB - IEC) and decimal prefixes (KB, MB - SI).",
      loader: () => import("@/components/calculators/Conversion/BinaryDecimalPrefixesCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "transfer-speed-mbps-mbs",
      title: "Transfer Speed: Mbps ↔ MB/s",
      category: "conversion",
      subcategory: "computing-data",
      description: "Convert internet speed to file transfer rate. See how fast a file will download by converting Mbps (Megabits) to MB/s (Megabytes).",
      loader: () => import("@/components/calculators/Conversion/TransferSpeedMbpsMbsCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "compression-ratio-size",
      title: "Compression Ratio & Size",
      category: "conversion",
      subcategory: "computing-data",
      description: "Estimate file size reduction. Calculate the final file size based on original size and compression ratio.",
      loader: () => import("@/components/calculators/Conversion/CompressionRatioSizeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "checksum-hash-quick-tools",
      title: "Checksum & Hash Quick Tools",
      category: "conversion",
      subcategory: "computing-data",
      description: "Verify data integrity. Quickly generate or compare checksums and hash values for files to ensure they are not corrupted.",
      loader: () => import("@/components/calculators/Conversion/ChecksumHashQuickToolsCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cooking-tsp-tbsp-cup-ml",
      title: "Cooking: tsp/tbsp/cup ↔ mL",
      category: "conversion",
      subcategory: "everyday-mixed",
      description: "Convert kitchen measurements. Transform teaspoons, tablespoons, and cups into milliliters (mL) for precise baking and cooking.",
      loader: () => import("@/components/calculators/Conversion/CookingTspTbspCupMlCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "fuel-economy-l-per-100km-mpg",
      title: "Fuel Economy: L/100km ↔ mpg",
      category: "conversion",
      subcategory: "everyday-mixed",
      description: "Convert fuel consumption ratings. Switch between Liters per 100km (L/100km) and Miles Per Gallon (MPG) for vehicle efficiency.",
      loader: () => import("@/components/calculators/Conversion/FuelEconomyLPer100kmMpgCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "currency-fx-quick-convert",
      title: "Currency: FX quick convert",
      category: "conversion",
      subcategory: "everyday-mixed",
      description: "Quick currency converter. Estimate values between major currencies for travel budgets and international shopping.",
      loader: () => import("@/components/calculators/Conversion/CurrencyFxQuickConvertCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "bmi-bsa-quick-estimators",
      title: "BMI & BSA quick estimators",
      category: "conversion",
      subcategory: "everyday-mixed",
      description: "Quickly estimate Body Mass Index (BMI) and Body Surface Area (BSA) using standard conversion formulas for health checks.",
      loader: () => import("@/components/calculators/Conversion/BmiBsaQuickEstimatorsCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "paper-size-a-series-us",
      title: "Paper Size: A-series ↔ US",
      category: "conversion",
      subcategory: "everyday-mixed",
      description: "Compare international paper sizes. Convert between ISO A-series (A4, A3) and US Letter/Legal sizes for printing.",
      loader: () => import("@/components/calculators/Conversion/PaperSizeASeriesUsCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "shoe-size-eu-us-uk",
      title: "Shoe Size: EU ↔ US ↔ UK",
      category: "conversion",
      subcategory: "everyday-mixed",
      description: "Convert international shoe sizes. Find the right fit by converting between European (EU), American (US), and British (UK) sizing charts.",
      loader: () => import("@/components/calculators/Conversion/ShoeSizeEuUsUkCalculator"),
      urlStyle: "flat"
    }
];
