// AUTO-GENERATED by scripts/split-registry.cjs — DO NOT EDIT BY HAND.
// Per-category slice of the master CalculatorEntry registry.
// Re-run `node scripts/split-registry.cjs` after editing the master.

import type { CalculatorEntry } from "@/data/calculatorRegistry";

export const sportsEntries: CalculatorEntry[] = [
  {
      slug: "vo2max-estimator-cooper-rockport",
      title: "VO2max Estimator (Cooper/Rockport)",
      category: "sports",
      subcategory: "training-performance",
      description: "Estimate your VO2max aerobic capacity. Use Cooper or Rockport test results to assess your cardiovascular fitness level.",
      loader: () => import("@/components/calculators/Sports/Vo2maxEstimatorCooperRockportCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "running-pace-split-finish-time",
      title: "Running Pace / Split / Finish Time Calculator",
      category: "sports",
      subcategory: "running-cycling-triathlon-performance",
      description: "Calculate your running pace and finish times. Determine the splits needed to achieve your marathon or 5K personal best.",
      loader: () => import("@/components/calculators/Sports/RunningPaceSplitFinishTimeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "race-time-predictor-riegel",
      title: "Race Time Predictor (Riegel Formula)",
      category: "sports",
      subcategory: "running-cycling-triathlon-performance",
      description: "Predict your race time for any distance. Use the Riegel formula to estimate performance based on a previous race result.",
      loader: () => import("@/components/calculators/Sports/RaceTimePredictorRiegelCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "heart-rate-zones-karvonen",
      title: "Heart-Rate Zones Calculator (Karvonen Method)",
      category: "sports",
      subcategory: "running-cycling-triathlon-performance",
      description: "Calculate accurate heart rate training zones. Use the Karvonen method to account for resting heart rate and optimize your cardio.",
      loader: () => import("@/components/calculators/Sports/HeartRateZonesKarvonenCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cycling-power-speed-estimator",
      title: "Cycling Power ↔ Speed Estimator (flat/wind)",
      category: "sports",
      subcategory: "running-cycling-triathlon-performance",
      description: "Estimate cycling power vs speed. Calculate how much wattage is required to maintain speed against wind resistance and flat terrain.",
      loader: () => import("@/components/calculators/Sports/CyclingPowerSpeedEstimatorCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "ftp-zones-planner",
      title: "FTP (Functional Threshold Power) Zones Planner",
      category: "sports",
      subcategory: "running-cycling-triathlon-performance",
      description: "Plan your cycling training zones. Calculate power zones based on your Functional Threshold Power (FTP) for structured workouts.",
      loader: () => import("@/components/calculators/Sports/FtpZonesPlannerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "swim-pace-css-splits",
      title: "Swim Pace: CSS (Critical Swim Speed) & Splits",
      category: "sports",
      subcategory: "running-cycling-triathlon-performance",
      description: "Calculate your Critical Swim Speed (CSS). Determine optimal pacing for swim training and monitor aerobic threshold improvements.",
      loader: () => import("@/components/calculators/Sports/SwimPaceCssSplitsCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "t1-t2-time-impact",
      title: "T1/T2 Transition Time Impact (Triathlon)",
      category: "sports",
      subcategory: "running-cycling-triathlon-performance",
      description: "Analyze triathlon transition times. See how T1 and T2 durations impact your overall race finish time and ranking.",
      loader: () => import("@/components/calculators/Sports/T1T2TimeImpactCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "hydration-sweat-rate",
      title: "Hydration / Sweat Rate Calculator",
      category: "sports",
      subcategory: "running-cycling-triathlon-performance",
      description: "Calculate your sweat rate. Determine exactly how much fluid you need to drink to stay hydrated during endurance events.",
      loader: () => import("@/components/calculators/Sports/HydrationSweatRateCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cycling-cadence",
      title: "Cycling Cadence Calculator",
      category: "sports",
      subcategory: "running-cycling-triathlon-performance",
      description: "Calculate cycling cadence. Measure your RPM (revolutions per minute) based on gear ratio and speed to improve pedaling efficiency.",
      loader: () => import("@/components/calculators/Sports/CyclingCadenceCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "negative-split",
      title: "Negative Split Race Planner",
      category: "sports",
      subcategory: "running-cycling-triathlon-performance",
      description: "Plan a negative split strategy. Calculate the pace required for the second half of your race to finish stronger than you started.",
      loader: () => import("@/components/calculators/Sports/NegativeSplitCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "swimming-power-points",
      title: "Swimming Power Points Calculator",
      category: "sports",
      subcategory: "running-cycling-triathlon-performance",
      description: "Calculate swimming power points. Compare performances across different events and distances using standardized scoring tables.",
      loader: () => import("@/components/calculators/Sports/SwimmingPowerPointsCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "pool-length-time-converter",
      title: "Pool Length Time Converter (SCY/SCM/LCM)",
      category: "sports",
      subcategory: "running-cycling-triathlon-performance",
      description: "Convert swim times between pool lengths. Switch between Short Course Yards, Short Course Meters, and Long Course Meters accurately.",
      seoTitle: "Swim Time Converter — SCY, SCM & LCM Pool Lengths",
      seoDescription: "Convert swim times between Short Course Yards (SCY), Short Course Meters (SCM), and Long Course Meters (LCM). Essential for competitive swimmers comparing performance across pool sizes.",
      loader: () => import("@/components/calculators/Sports/PoolLengthTimeConverterCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "swim-interval-pace",
      title: "Swim Interval Pace Calculator",
      category: "sports",
      subcategory: "running-cycling-triathlon-performance",
      description: "Calculate swim interval pacing. Set target times for 100m or 50m repeats to improve speed and endurance in the pool.",
      loader: () => import("@/components/calculators/Sports/SwimIntervalPaceCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "one-rep-max-1rm",
      title: "One-Rep Max (1RM) Calculator",
      category: "sports",
      subcategory: "strength-lifting-conditioning",
      description: "Calculate your One-Rep Max (1RM). safely estimate your maximum lifting potential for bench press, squat, and deadlift.",
      loader: () => import("@/components/calculators/Sports/OneRepMax1rmCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "training-weight-percentage",
      title: "Training Weight Percentage Calculator",
      category: "sports",
      subcategory: "strength-lifting-conditioning",
      description: "Calculate training weights. Determine specific percentages of your 1RM to plan hypertrophy, strength, or power workouts.",
      loader: () => import("@/components/calculators/Sports/TrainingWeightPercentageCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "target-heart-rate-rpe-zones",
      title: "Target Heart Rate / RPE Zones",
      category: "sports",
      subcategory: "strength-lifting-conditioning",
      description: "Match heart rate to Perceived Exertion (RPE). Align subjective training intensity with objective heart rate data.",
      loader: () => import("@/components/calculators/Sports/TargetHeartRateRpeZonesCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "tdee-calculator",
      title: "TDEE Calculator (Sports)",
      category: "sports",
      subcategory: "strength-lifting-conditioning",
      description: "Calculate Total Daily Energy Expenditure for athletes. Estimate calorie needs based on high activity levels and training volume.",
      loader: () => import("@/components/calculators/Sports/TdeeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "plank-hold-progression",
      title: "Plank / Hold Time Progression",
      category: "sports",
      subcategory: "strength-lifting-conditioning",
      description: "Track core strength progression. Log and plan plank hold times to gradually build abdominal endurance and stability.",
      loader: () => import("@/components/calculators/Sports/PlankHoldProgressionCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "wilks-coefficient",
      title: "Wilks Coefficient Calculator",
      category: "sports",
      subcategory: "strength-lifting-conditioning",
      description: "Calculate your Wilks Score. Compare powerlifting strength across different body weight categories fairly.",
      loader: () => import("@/components/calculators/Sports/WilksCoefficientCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "body-fat-percentage",
      title: "Body Fat Percentage Calculator (Athletes)",
      category: "sports",
      subcategory: "strength-lifting-conditioning",
      description: "Estimate body fat percentage for athletes. Track body composition changes during cutting or bulking phases.",
      loader: () => import("@/components/calculators/Sports/BodyFatPercentageCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "plate-loading",
      title: "Plate Loading Calculator",
      category: "sports",
      subcategory: "strength-lifting-conditioning",
      description: "Calculate barbell plate loading. Find the exact combination of plates needed to reach a specific target weight on the bar.",
      loader: () => import("@/components/calculators/Sports/PlateLoadingCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "macronutrient-calculator",
      title: "Macronutrient Calculator (Sports)",
      category: "sports",
      subcategory: "strength-lifting-conditioning",
      description: "Calculate athlete macronutrient needs. Optimize protein, carb, and fat intake for performance recovery and muscle growth.",
      loader: () => import("@/components/calculators/Sports/MacronutrientCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "calorie-deficit-surplus",
      title: "Calorie Deficit / Surplus Calculator",
      category: "sports",
      subcategory: "strength-lifting-conditioning",
      description: "Plan calorie deficits or surpluses. Adjust energy intake precisely for weight cutting or mass gaining cycles.",
      loader: () => import("@/components/calculators/Sports/CalorieDeficitSurplusCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "fitness-age-calculator",
      title: "Fitness Age Calculator",
      category: "sports",
      subcategory: "strength-lifting-conditioning",
      description: "Estimate your fitness age. Compare your cardiovascular health and VO2max against age-related norms.",
      loader: () => import("@/components/calculators/Sports/FitnessAgeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "yoga-calories-burned",
      title: "Yoga Calories Burned Calculator",
      category: "sports",
      subcategory: "strength-lifting-conditioning",
      description: "Estimate calories burned during yoga. Calculate energy expenditure for Hatha, Vinyasa, or Bikram yoga sessions.",
      loader: () => import("@/components/calculators/Sports/YogaCaloriesBurnedCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "fantasy-team-points-projections",
      title: "Fantasy Team Points Projections Calculator",
      category: "sports",
      subcategory: "ball-sports-advanced-metrics",
      description: "Project fantasy sports points. Estimate team scores based on player stats for football, basketball, or soccer leagues.",
      loader: () => import("@/components/calculators/Sports/FantasyTeamPointsProjectionsCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "betting-odds-payout-calculator",
      title: "Betting Odds & Payout Calculator",
      category: "sports",
      subcategory: "ball-sports-advanced-metrics",
      description: "Calculate potential betting payouts. Convert between Decimal, Fractional, and Moneyline odds to see your return.",
      loader: () => import("@/components/calculators/Sports/BettingOddsPayoutCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "soccer-league-table-points-gd",
      title: "Soccer League Table: Points & GD",
      category: "sports",
      subcategory: "ball-sports-advanced-metrics",
      description: "Calculate soccer league standings. Track points, goal differential, and ranking scenarios for your team.",
      loader: () => import("@/components/calculators/Sports/SoccerLeagueTablePointsGdCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "expected-goals-xg-helper",
      title: "xG (Expected Goals) Reading Helper",
      category: "sports",
      subcategory: "ball-sports-advanced-metrics",
      description: "Understand Expected Goals (xG). Interpret match statistics to analyze team performance beyond the final score.",
      loader: () => import("@/components/calculators/Sports/ExpectedGoalsXgHelperCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "basketball-efg-ts",
      title: "Basketball eFG% & TS% Calculator",
      category: "sports",
      subcategory: "ball-sports-advanced-metrics",
      description: "Calculate Effective Field Goal and True Shooting percentage. Measure basketball scoring efficiency accurately.",
      loader: () => import("@/components/calculators/Sports/BasketballEfgTsCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "basketball-pace-ortg-drtg",
      title: "Basketball Pace & ORtg/DRtg",
      category: "sports",
      subcategory: "ball-sports-advanced-metrics",
      description: "Calculate Basketball Pace and Ratings. Analyze possessions per game and offensive/defensive efficiency metrics.",
      loader: () => import("@/components/calculators/Sports/BasketballPaceOrtgDrtgCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "baseball-ops-slg-obp",
      title: "Baseball OPS / SLG / OBP Calculator",
      category: "sports",
      subcategory: "ball-sports-advanced-metrics",
      description: "Calculate baseball sabermetrics. Find On-Base Plus Slugging (OPS), Slugging percentage, and On-Base Percentage instantly.",
      loader: () => import("@/components/calculators/Sports/BaseballOpsSlgObpCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "era-whip-calculator",
      title: "ERA & WHIP Calculator",
      category: "sports",
      subcategory: "ball-sports-advanced-metrics",
      description: "Calculate pitcher stats. Determine Earned Run Average (ERA) and Walks Plus Hits Per Inning Pitched (WHIP).",
      loader: () => import("@/components/calculators/Sports/EraWhipCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "win-probability-shift-wps",
      title: "Win Probability Shift (WPS) Estimator",
      category: "sports",
      subcategory: "ball-sports-advanced-metrics",
      description: "Estimate Win Probability Shift. Analyze how specific plays impact the likelihood of winning a game in real-time.",
      loader: () => import("@/components/calculators/Sports/WinProbabilityShiftWpsCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "babip-calculator",
      title: "BABIP Calculator",
      category: "sports",
      subcategory: "ball-sports-advanced-metrics",
      description: "Calculate Batting Average on Balls in Play (BABIP). Assess whether a pitcher or hitter is lucky or skilled.",
      loader: () => import("@/components/calculators/Sports/BabipCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "ground-ball-to-fly-ball-ratio-gb-fb",
      title: "Ground Ball to Fly Ball Ratio (GB/FB)",
      category: "sports",
      subcategory: "ball-sports-advanced-metrics",
      description: "Calculate GB/FB ratio. Analyze a pitcher's tendency to induce grounders versus fly balls.",
      loader: () => import("@/components/calculators/Sports/GroundBallToFlyBallRatioGbFbCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "golf-handicap-differential-index",
      title: "Golf Handicap Differential & Index",
      category: "sports",
      subcategory: "individual-game-management",
      description: "Calculate Golf Handicap Differential. Determine your index based on course rating and slope difficulty.",
      loader: () => import("@/components/calculators/Sports/GolfHandicapDifferentialIndexCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "golf-expected-putts-per-round",
      title: "Golf Expected Putts per Round",
      category: "sports",
      subcategory: "individual-game-management",
      description: "Estimate expected putts per round. Track putting performance against benchmarks to improve your short game.",
      loader: () => import("@/components/calculators/Sports/GolfExpectedPuttsPerRoundCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "tennis-serve-speed",
      title: "Tennis Serve Speed Calculator",
      category: "sports",
      subcategory: "individual-game-management",
      description: "Calculate tennis serve speed. Estimate velocity based on the distance and time between impact and bounce.",
      loader: () => import("@/components/calculators/Sports/TennisServeSpeedCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "tennis-elo-rating-progress",
      title: "Tennis ELO / Rating Progress",
      category: "sports",
      subcategory: "individual-game-management",
      description: "Track Tennis ELO rating progress. Understand how match wins and losses affect your player ranking.",
      loader: () => import("@/components/calculators/Sports/TennisEloRatingProgressCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "rowing-split-500m-pace",
      title: "Rowing Split (500m) ↔ Pace",
      category: "sports",
      subcategory: "individual-game-management",
      description: "Convert rowing splits to pace. Calculate 500m split times based on total distance and duration for ergometer training.",
      loader: () => import("@/components/calculators/Sports/RowingSplit500mPaceCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "climbing-grade-converter-yds-french-eu",
      title: "Climbing Grade Converter",
      category: "sports",
      subcategory: "individual-game-management",
      description: "Convert climbing grades. Switch between YDS, French, and European scales to understand route difficulty worldwide.",
      loader: () => import("@/components/calculators/Sports/ClimbingGradeConverterYdsFrenchEuCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "tournament-bracket-seeding-helper",
      title: "Tournament Bracket Seeding Helper",
      category: "sports",
      subcategory: "individual-game-management",
      description: "Organize tournament brackets. Seed players or teams correctly to ensure fair matchups in knockout rounds.",
      loader: () => import("@/components/calculators/Sports/TournamentBracketSeedingHelperCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "golf-handicap-calculator",
      title: "Golf Handicap Calculator",
      category: "sports",
      subcategory: "individual-game-management",
      description: "Calculate your official Golf Handicap. Enter your scores to track improvement and compete fairly with others.",
      loader: () => import("@/components/calculators/Sports/GolfHandicapCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "bowling-score-calculator",
      title: "Bowling Score Calculator",
      category: "sports",
      subcategory: "individual-game-management",
      description: "Calculate bowling scores. Simulate frames, strikes, and spares to predict your final game score.",
      loader: () => import("@/components/calculators/Sports/BowlingScoreCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "fina-points-calculator",
      title: "FINA Points Calculator",
      category: "sports",
      subcategory: "individual-game-management",
      description: "Calculate FINA swimming points. Convert race times into official FINA points for ranking comparison.",
      loader: () => import("@/components/calculators/Sports/FinaPointsCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "swim-performance-level-calculator",
      title: "Swim Performance Level Calculator",
      category: "sports",
      subcategory: "individual-game-management",
      description: "Assess swim performance level. Compare your times against age-group standards to see where you rank.",
      loader: () => import("@/components/calculators/Sports/SwimPerformanceLevelCalculator"),
      urlStyle: "flat"
    }
];
