// AUTO-GENERATED by scripts/split-registry.cjs — DO NOT EDIT BY HAND.
// Per-category slice of the master CalculatorEntry registry.
// Re-run `node scripts/split-registry.cjs` after editing the master.

import type { CalculatorEntry } from "@/data/calculatorRegistry";

export const cookingEntries: CalculatorEntry[] = [
  {
      slug: "cups-grams-ounces-by-ingredient",
      title: "Cups ↔ Grams ↔ Ounces Converter",
      category: "cooking",
      subcategory: "ingredient-conversions-kitchen-math",
      description: "Convert cooking ingredients from volume to weight. Switch between cups, grams, and ounces for flour, sugar, and more with density adjustments.",
      loader: () => import("@/components/calculators/Cooking/CupsGramsOuncesByIngredientCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "volume-weight-food-density",
      title: "Volume ↔ Weight Converter",
      category: "cooking",
      subcategory: "ingredient-conversions-kitchen-math",
      description: "Calculate food density conversions. Translate volume measurements to weight for precise cooking using common ingredient densities.",
      loader: () => import("@/components/calculators/Cooking/VolumeWeightFoodDensityCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "fahrenheit-celsius-oven-internal-temp",
      title: "Fahrenheit ↔ Celsius Converter",
      category: "cooking",
      subcategory: "ingredient-conversions-kitchen-math",
      description: "Convert oven temperatures instantly. Switch between Fahrenheit and Celsius for baking recipes and internal meat thermometers.",
      loader: () => import("@/components/calculators/Cooking/FahrenheitCelsiusOvenInternalTempCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "teaspoon-tablespoon-cup-ml-converter",
      title: "Teaspoon/Tablespoon/Cup ↔ mL Converter",
      category: "cooking",
      subcategory: "ingredient-conversions-kitchen-math",
      description: "Convert small kitchen measurements. Transform teaspoons, tablespoons, and cups into milliliters (mL) for liquid ingredients.",
      loader: () => import("@/components/calculators/Cooking/TeaspoonTablespoonCupMlConverterCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "recipe-scaler",
      title: "Recipe Scaler (x0.5, x2, x3…)",
      category: "cooking",
      subcategory: "ingredient-conversions-kitchen-math",
      description: "Scale your recipes up or down. Multiply or divide ingredient quantities to adjust serving sizes for parties or single meals.",
      loader: () => import("@/components/calculators/Cooking/RecipeScalerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "serving-size-multiplier",
      title: "Serving Size Multiplier",
      category: "cooking",
      subcategory: "ingredient-conversions-kitchen-math",
      description: "Adjust recipes by serving size. Input your desired number of servings to automatically recalculate all ingredient amounts.",
      loader: () => import("@/components/calculators/Cooking/ServingSizeMultiplierCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "salt-percent-brining",
      title: "Salt % for Brining Calculator",
      category: "cooking",
      subcategory: "ingredient-conversions-kitchen-math",
      description: "Calculate the perfect brine ratio. Determine the exact amount of salt needed for wet brining meats to ensure flavor and moisture.",
      loader: () => import("@/components/calculators/Cooking/SaltPercentBriningCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "alcohol-abv-dilution",
      title: "Alcohol by Volume (ABV) Dilution",
      category: "cooking",
      subcategory: "ingredient-conversions-kitchen-math",
      description: "Calculate alcohol dilution for cooking. Estimate the remaining Alcohol by Volume (ABV) in your dishes after simmering or baking.",
      loader: () => import("@/components/calculators/Cooking/AlcoholAbvDilutionCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cake-pan-size-volume-converter",
      title: "Cake Pan Size & Volume Converter",
      category: "cooking",
      subcategory: "baking-essentials",
      description: "Convert cake pan sizes. Adjust recipes for different pan shapes and volumes (round vs square) without ruining your bake.",
      loader: () => import("@/components/calculators/Cooking/CakePanSizeVolumeConverterCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "bakers-percentage",
      title: "Baker’s Percentage Calculator",
      category: "cooking",
      subcategory: "baking-essentials",
      description: "Master Baker's Math. Calculate ingredient ratios based on flour weight to create consistent and scalable bread recipes.",
      loader: () => import("@/components/calculators/Cooking/BakersPercentageCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dough-hydration-percent",
      title: "Dough Hydration % Calculator",
      category: "cooking",
      subcategory: "baking-essentials",
      description: "Calculate dough hydration percentage. Essential for sourdough and artisanal bread to achieve the perfect crumb and texture.",
      loader: () => import("@/components/calculators/Cooking/DoughHydrationPercentCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "sourdough-starter-ratio-feed-planner",
      title: "Sourdough Starter Ratio & Feed Planner",
      category: "cooking",
      subcategory: "baking-essentials",
      description: "Plan your sourdough starter feedings. Calculate the perfect ratio of starter, flour, and water to keep your wild yeast active.",
      loader: () => import("@/components/calculators/Cooking/SourdoughStarterRatioFeedPlannerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "yeast-conversion-instant-active-fresh",
      title: "Yeast Conversion Calculator",
      category: "cooking",
      subcategory: "baking-essentials",
      description: "Convert yeast types easily. Switch between instant, active dry, and fresh yeast quantities for any baking recipe.",
      loader: () => import("@/components/calculators/Cooking/YeastConversionInstantActiveFreshCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "flour-blend-substitution",
      title: "Flour Blend Substitution Helper",
      category: "cooking",
      subcategory: "baking-essentials",
      description: "Create gluten-free flour blends. Calculate ratios for substituting all-purpose flour with almond, coconut, or rice flour mixes.",
      loader: () => import("@/components/calculators/Cooking/FlourBlendSubstitutionCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "sugar-butter-flour-density-lookup",
      title: "Sugar/Butter/Flour Density Lookup",
      category: "cooking",
      subcategory: "baking-essentials",
      description: "Quickly look up ingredient densities. Convert cups of packed sugar, butter, or sifted flour to grams accurately.",
      loader: () => import("@/components/calculators/Cooking/SugarButterFlourDensityLookupCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "chocolate-butter-tempering-temperature",
      title: "Chocolate/Butter Tempering Temperature",
      category: "cooking",
      subcategory: "baking-essentials",
      description: "Guide to chocolate tempering temperatures. Find the precise melting, cooling, and working points for dark, milk, and white chocolate.",
      loader: () => import("@/components/calculators/Cooking/ChocolateButterTemperingTemperatureCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "turkey-thaw-cook-time",
      title: "Turkey Size, Thaw & Cook Time Calculator",
      category: "cooking",
      subcategory: "meat-poultry-food-safety-times",
      description: "Plan your Thanksgiving turkey. Calculate thawing time and cooking time based on bird weight for a safe and juicy roast.",
      loader: () => import("@/components/calculators/Cooking/TurkeyThawCookTimeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "whole-chicken-roast-cook-time",
      title: "Whole Chicken/Roast Cook Time Estimator",
      category: "cooking",
      subcategory: "meat-poultry-food-safety-times",
      description: "Estimate roasting time for whole chickens. Ensure perfectly cooked poultry by calculating oven time based on weight.",
      loader: () => import("@/components/calculators/Cooking/WholeChickenRoastCookTimeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "steak-doneness-time-resting",
      title: "Steak Doneness Time & Resting Window",
      category: "cooking",
      subcategory: "meat-poultry-food-safety-times",
      description: "Time your steak to perfection. Estimate cooking time for rare, medium, or well-done steaks and calculate the vital resting period.",
      loader: () => import("@/components/calculators/Cooking/SteakDonenessTimeRestingCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "pork-beef-smoking-time-per-lb",
      title: "Pork/Beef Smoking Time per lb",
      category: "cooking",
      subcategory: "meat-poultry-food-safety-times",
      description: "Plan your BBQ smoking session. Calculate cooking time per pound for pork shoulders or beef briskets at low temperatures.",
      loader: () => import("@/components/calculators/Cooking/PorkBeefSmokingTimePerLbCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "safe-internal-temperature-checker",
      title: "Safe Internal Temperature Checker",
      category: "cooking",
      subcategory: "meat-poultry-food-safety-times",
      description: "Check safe internal food temperatures. Reference USDA guidelines for meat, poultry, and fish to prevent foodborne illness.",
      loader: () => import("@/components/calculators/Cooking/SafeInternalTemperatureCheckerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "defrost-time-fridge-cold-water",
      title: "Defrost Time Estimator",
      category: "cooking",
      subcategory: "meat-poultry-food-safety-times",
      description: "Estimate defrosting times. Calculate how long meat needs to thaw in the fridge or cold water based on its weight.",
      loader: () => import("@/components/calculators/Cooking/DefrostTimeFridgeColdWaterCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "rice-water-ratio-yield",
      title: "Rice:Water Ratio & Yield Calculator",
      category: "cooking",
      subcategory: "everyday-kitchen-ratios-yields",
      description: "Get the perfect rice-to-water ratio. Calculate yield and liquid needs for Basmati, Jasmine, Brown, or Sushi rice.",
      loader: () => import("@/components/calculators/Cooking/RiceWaterRatioYieldCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "pasta-dry-cooked-yield-portions",
      title: "Pasta Dry ↔ Cooked Yield & Portions",
      category: "cooking",
      subcategory: "everyday-kitchen-ratios-yields",
      description: "Convert dry pasta to cooked weight. Estimate how much pasta to boil to get the exact number of cooked servings you need.",
      loader: () => import("@/components/calculators/Cooking/PastaDryCookedYieldPortionsCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "stock-broth-reduction-time-yield",
      title: "Stock/Broth Reduction Time & Yield",
      category: "cooking",
      subcategory: "everyday-kitchen-ratios-yields",
      description: "Estimate stock reduction yield. Calculate how much volume remains after reducing broth to a demi-glace or glaze.",
      loader: () => import("@/components/calculators/Cooking/StockBrothReductionTimeYieldCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "oil-for-frying-pan-depth-volume",
      title: "Oil for Frying Calculator",
      category: "cooking",
      subcategory: "everyday-kitchen-ratios-yields",
      description: "Calculate oil needed for deep frying. Determine the volume required to fill your pan or fryer to the safe depth level.",
      loader: () => import("@/components/calculators/Cooking/OilForFryingPanDepthVolumeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "icing-frosting-coverage-cake-size",
      title: "Icing/Frosting Coverage by Cake Size",
      category: "cooking",
      subcategory: "everyday-kitchen-ratios-yields",
      description: "Calculate icing and frosting amounts. Determine how much frosting you need to cover round or square cakes of various sizes.",
      loader: () => import("@/components/calculators/Cooking/IcingFrostingCoverageCakeSizeCalculator"),
      urlStyle: "flat"
    }
];
