import { useState, useMemo, useEffect } from "react";
import CalculatorVerticalLayout from "@/components/templates/CalculatorVerticalLayout";
import DailyHoroscopeWidget from "@/components/calculators/DailyQuotes/DailyHoroscopeWidget";
import QuoteCard, { DailyQuoteItem } from "@/components/calculators/DailyQuotes/QuoteCard";
import { 
  Briefcase, Rocket, Camera, Laptop, 
  Smile, HeartHandshake, Brain, Moon, 
  ArrowLeft, Sparkles, RefreshCw, Loader2,
  Copy, Share2, Check
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { toast } from "@/components/ui/sonner";

// JSON file URL generated by n8n (RAW)
const DATA_URL = "https://raw.githubusercontent.com/williamsasmartins/smartkit-onepage-wonder/main/public/daily_horoscope.json";

// Expected JSON structure
type DailyDataPacket = {
  date: string;
  hero: { text: string; author: string };
  content: {
    professional: DailyQuoteItem[];
    motivation: DailyQuoteItem[];
    captions: DailyQuoteItem[];
    tech: DailyQuoteItem[];
    fun: DailyQuoteItem[];
    faith: DailyQuoteItem[];
    wisdom: DailyQuoteItem[];
  };
};

type CategoryKey = keyof DailyDataPacket["content"] | "horoscope" | "dream";

export default function DailyQuotesPage() {
  const [data, setData] = useState<DailyDataPacket | null>(null);
  const [loading, setLoading] = useState(true);
  const [selectedCategory, setSelectedCategory] = useState<CategoryKey | null>(null);
  const [liked, setLiked] = useState<Set<number>>(new Set());
  const [shuffleSeed, setShuffleSeed] = useState(0);

  // --- DREAM INTERPRETER STATES ---
  const [dreamInput, setDreamInput] = useState("");
  const [interpretation, setInterpretation] = useState<any>(null);
  const [isInterpreting, setIsInterpreting] = useState(false);
  const [copied, setCopied] = useState(false);

  // FETCH REAL DATA
  useEffect(() => {
    const fetchData = async () => {
      try {
        // Appends timestamp to avoid aggressive browser caching
        const res = await fetch(`${DATA_URL}?t=${new Date().getTime()}`);
        if (!res.ok) throw new Error("Failed to load daily inspiration");
        const json = await res.json();
        setData(json);
      } catch (error) {
        console.error("Error fetching data:", error);
        // Silent fail - user sees loading state or empty state handled below
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, []);

  const toggleLike = (id: number) => {
    const next = new Set(liked);
    if (next.has(id)) next.delete(id);
    else next.add(id);
    setLiked(next);
  };

  const handleShuffle = () => {
    setShuffleSeed(prev => prev + 1);
  };

  // --- DREAM INTERPRETER LOGIC ---
  const handleInterpretDream = async () => {
    if (!dreamInput.trim()) return;
    setIsInterpreting(true);
    setInterpretation(null);

    try {
      const res = await fetch("https://n8n.sweetslove.ca/webhook/dream-interpreter", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ dream: dreamInput }),
      });

      if (!res.ok) throw new Error("Failed to interpret");

      const data = await res.json();
      
      // Handle different n8n response structures
      const aiContent = data.message?.content || data[0]?.message?.content || data.content || data;
      
      if (typeof aiContent === "string") {
        const cleanJson = aiContent.replace(/^```json\s*/i, "").replace(/\s*```$/, "");
        setInterpretation(JSON.parse(cleanJson));
      } else {
        setInterpretation(aiContent);
      }

    } catch (error) {
      console.error("Dream API Error:", error);
      toast("The oracle is silent right now. Please try again.");
    } finally {
      setIsInterpreting(false);
    }
  };

  // --- SHARE & COPY FUNCTIONS ---
  const handleCopyResult = () => {
    if (!interpretation) return;
    const text = `🌙 Dream Interpretation:\n\n"${interpretation.summary}"\n\n✨ Advice: ${interpretation.advice}\n\n🔮 Interpreted by SmartKitNow.com`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    toast("Interpretation copied to clipboard!");
  };

  const handleShareResult = async () => {
    if (!interpretation) return;
    const text = `🌙 Dream Interpretation:\n\n"${interpretation.summary}"\n\n✨ Advice: ${interpretation.advice}\n\n🔮 Check yours at SmartKitNow.com`;
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'My Dream Meaning',
          text: text,
          url: 'https://smartkitnow.com/daily-quotes',
        });
      } catch (err) {
        console.log('Share canceled');
      }
    } else {
      handleCopyResult(); // Fallback to copy
    }
  };

  const CATEGORIES = [
    { id: "horoscope", label: "Daily Horoscope", icon: Sparkles, color: "text-purple-500", desc: "Your zodiac forecast" },
    { id: "dream", label: "Dream Interpreter", icon: Moon, color: "text-indigo-400", desc: "Find the meaning (AI)" },
    { id: "professional", label: "Professional", icon: Briefcase, color: "text-blue-500", desc: "Career & Success" },
    { id: "motivation", label: "Motivation", icon: Rocket, color: "text-orange-500", desc: "Energy & Mindset" },
    { id: "captions", label: "Social Captions", icon: Camera, color: "text-pink-500", desc: "For Instagram/TikTok" },
    { id: "tech", label: "Tech & Geek", icon: Laptop, color: "text-cyan-500", desc: "Coding humor" },
    { id: "fun", label: "Fun & Sarcasm", icon: Smile, color: "text-yellow-500", desc: "Witty & Relatable" },
    { id: "faith", label: "Faith & Verses", icon: HeartHandshake, color: "text-emerald-500", desc: "Spiritual comfort" },
    { id: "wisdom", label: "Wisdom", icon: Brain, color: "text-violet-500", desc: "Famous quotes" },
  ];

  // Filter and Shuffle Logic
  const currentItems = useMemo(() => {
    if (!data || !selectedCategory || selectedCategory === "horoscope" || selectedCategory === "dream") return [];
    
    // @ts-expect-error
    const itemsList = data.content?.[selectedCategory as keyof DailyDataPacket["content"]];
    
    if (!itemsList || !Array.isArray(itemsList)) return [];

    const allItems = [...itemsList];
    
    if (shuffleSeed >= 0) {
        for (let i = allItems.length - 1; i > 0; i--) {
            const j = Math.floor(Math.random() * (i + 1));
            [allItems[i], allItems[j]] = [allItems[j], allItems[i]];
        }
    }
    
    return allItems.slice(0, 6); 
  }, [selectedCategory, shuffleSeed, data]);

  const renderContent = () => {
    if (selectedCategory === "horoscope") {
      return <DailyHoroscopeWidget showNavigation={false} />;
    }

    // --- DREAM INTERPRETER UI ---
    if (selectedCategory === "dream") {
      return (
        <div className="max-w-2xl mx-auto animate-in fade-in zoom-in-95 duration-500">
          
          {/* Input Section */}
          <div className="bg-muted/30 rounded-2xl p-6 border border-border mb-8">
            <div className="flex items-center gap-3 mb-4">
              <div className="p-2 bg-indigo-500/10 rounded-lg">
                <Moon className="w-6 h-6 text-indigo-500" />
              </div>
              <h3 className="text-xl font-bold">Dream Interpreter</h3>
            </div>
            
            <textarea 
              value={dreamInput}
              onChange={(e) => setDreamInput(e.target.value)}
              placeholder="Describe your dream here... (e.g., I was flying over a crystal city)"
              className="w-full min-h-[120px] p-4 rounded-xl bg-background border border-input focus:ring-2 focus:ring-indigo-500/50 resize-none transition-all mb-4"
              disabled={isInterpreting}
            />
            
            <Button 
              onClick={handleInterpretDream} 
              disabled={isInterpreting || !dreamInput.trim()}
              className="w-full bg-indigo-600 hover:bg-indigo-700 text-white shadow-lg shadow-indigo-500/20 h-12 text-lg"
            >
              {isInterpreting ? (
                <>
                  <Loader2 className="w-5 h-5 mr-2 animate-spin" />
                  Connecting with the subconscious...
                </>
              ) : (
                <>
                  <Sparkles className="w-5 h-5 mr-2" />
                  Interpret Dream
                </>
              )}
            </Button>
          </div>

          {/* Result Section */}
          {interpretation && (
            <div className="space-y-6 animate-in slide-in-from-bottom-4 duration-700">
              
              {/* Summary Card */}
              <div className="bg-gradient-to-br from-indigo-500/10 to-purple-500/10 border border-indigo-500/20 rounded-xl p-6 text-center relative group">
                <h4 className="text-indigo-500 font-bold uppercase tracking-wider text-xs mb-2">Core Meaning</h4>
                <p className="text-xl font-medium text-foreground leading-relaxed">
                  "{interpretation.summary}"
                </p>
                
                {/* Action Buttons */}
                <div className="flex justify-center gap-2 mt-4 opacity-100 transition-opacity">
                  <Button variant="secondary" size="sm" onClick={handleCopyResult} className="gap-2 h-8 text-xs">
                    {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                    {copied ? "Copied" : "Copy"}
                  </Button>
                  <Button variant="secondary" size="sm" onClick={handleShareResult} className="gap-2 h-8 text-xs">
                    <Share2 className="w-3 h-3" />
                    Share
                  </Button>
                </div>
              </div>

              {/* Analysis */}
              <div className="prose dark:prose-invert max-w-none">
                <h4 className="flex items-center gap-2 text-lg font-bold mb-2">
                  <Brain className="w-5 h-5 text-purple-500" />
                  Deep Analysis
                </h4>
                <p className="text-muted-foreground leading-relaxed">
                  {interpretation.analysis}
                </p>
              </div>

              {/* Symbols Grid */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {interpretation.symbols?.map((sym: string, idx: number) => (
                  <div key={idx} className="bg-muted/40 p-4 rounded-lg border border-border flex items-start gap-3">
                    <Sparkles className="w-4 h-4 text-amber-500 mt-1 shrink-0" />
                    <span className="text-sm text-foreground/90">{sym}</span>
                  </div>
                ))}
              </div>

              {/* Advice */}
              <div className="bg-emerald-500/10 border border-emerald-500/20 p-5 rounded-xl flex gap-4 items-start">
                <div className="p-2 bg-emerald-500/20 rounded-full shrink-0">
                  <HeartHandshake className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />
                </div>
                <div>
                  <h4 className="font-bold text-emerald-700 dark:text-emerald-400 text-sm uppercase mb-1">Guidance</h4>
                  <p className="text-emerald-900 dark:text-emerald-100 font-medium">
                    {interpretation.advice}
                  </p>
                </div>
              </div>

            </div>
          )}
        </div>
      );
    }

    if (currentItems.length === 0) return (
      <div className="text-center py-20 animate-in fade-in zoom-in-95">
        <div className="w-20 h-20 mx-auto bg-muted rounded-full flex items-center justify-center mb-4">
           {selectedCategory === "professional" && <Briefcase className="w-10 h-10 text-muted-foreground/50" />}
           {selectedCategory === "motivation" && <Rocket className="w-10 h-10 text-muted-foreground/50" />}
           {/* Fallback icon */}
           {![ "professional", "motivation"].includes(selectedCategory) && <RefreshCw className="w-10 h-10 text-muted-foreground/50" />}
        </div>
        <h3 className="text-xl font-bold mb-2">Refreshing Inspiration...</h3>
        <p className="text-muted-foreground max-w-sm mx-auto mb-6">
          We are currently downloading new quotes from the cosmos. Please verify if the n8n workflow has run successfully.
        </p>
      </div>
    );

    return (
      <div className="space-y-6 animate-in fade-in slide-in-from-right-8 duration-300">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {currentItems.map((item) => (
            <QuoteCard
              key={item.id}
              item={item}
              categoryLabel={selectedCategory?.toString() || ""}
              isLiked={liked.has(item.id)}
              onToggleLike={toggleLike}
              tone={selectedCategory === "tech" ? "tech" : "default"}
            />
          ))}
        </div>
        
        <div className="flex justify-center pt-8 pb-4">
            <Button variant="secondary" size="lg" onClick={handleShuffle} className="gap-2 shadow-sm">
                <RefreshCw className="w-4 h-4" />
                Shuffle Suggestions
            </Button>
        </div>
      </div>
    );
  };

  const seoDescription = (
    <div className="max-w-3xl mx-auto text-center space-y-4 mb-10 text-muted-foreground">
      <p className="text-lg leading-relaxed">
        Start your day with clarity and purpose. Explore our comprehensive <strong>Daily Inspiration Hub</strong> featuring 
        accurate <span className="text-foreground font-medium">Horoscope forecasts</span>, 
        deep <span className="text-foreground font-medium">Dream Meanings</span>, and a curated collection of 
        <span className="text-foreground font-medium"> Motivational Quotes</span>.
      </p>
    </div>
  );

  return (
    <CalculatorVerticalLayout
      title="Daily Inspiration Hub"
      description=""
      widget={
        <div className="min-h-[600px]">
          {loading ? (
            <div className="flex flex-col items-center justify-center py-20 gap-4">
              <Loader2 className="w-10 h-10 animate-spin text-primary" />
              <p className="text-muted-foreground animate-pulse">Connecting to the stars...</p>
            </div>
          ) : (
            <>
              {/* Hero Section from real JSON */}
              {!selectedCategory && data?.hero && (
                 <div className="relative rounded-2xl overflow-hidden p-8 text-center bg-gradient-to-br from-indigo-500/10 via-purple-500/10 to-background border border-border mb-8 animate-in fade-in duration-700">
                   <div className="relative z-10 max-w-3xl mx-auto space-y-4">
                     <div className="inline-flex items-center justify-center px-3 py-1 rounded-full bg-primary/10 text-primary text-xs font-bold uppercase tracking-wider mb-2">
                       Quote of the Day • {data.date}
                     </div>
                     <h1 className="text-2xl md:text-3xl font-extrabold text-foreground leading-tight">
                       "{data.hero.text}"
                     </h1>
                     <p className="text-lg text-muted-foreground font-medium">
                       — {data.hero.author}
                     </p>
                   </div>
                   {seoDescription}
                 </div>
              )}

              {/* Header with Back Button */}
              {selectedCategory && (
                <div className="flex items-center justify-between mb-8">
                  <Button 
                    variant="ghost" 
                    onClick={() => setSelectedCategory(null)}
                    className="gap-2 pl-0 hover:bg-transparent hover:text-primary group"
                  >
                    <div className="p-1 rounded-full bg-muted group-hover:bg-primary/10 transition-colors">
                        <ArrowLeft className="w-4 h-4" />
                    </div>
                    <span className="font-semibold text-lg">Back to Hub</span>
                  </Button>
                </div>
              )}

              {/* HUB MENU */}
              {!selectedCategory ? (
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                  {CATEGORIES.map((cat) => (
                    <Card 
                      key={cat.id} 
                      className="cursor-pointer hover:border-primary/50 hover:bg-accent/5 hover:-translate-y-1 transition-all duration-300 group shadow-sm hover:shadow-md"
                      onClick={() => setSelectedCategory(cat.id as CategoryKey)}
                    >
                      <CardContent className="p-6 flex items-start gap-4">
                        <div className={`p-3 rounded-xl bg-muted/50 group-hover:bg-background border border-transparent group-hover:border-border transition-colors ${cat.color}`}>
                          <cat.icon className="w-7 h-7" />
                        </div>
                        <div>
                          <h3 className="font-bold text-lg leading-none mb-2 group-hover:text-primary transition-colors">
                            {cat.label}
                          </h3>
                          <p className="text-sm text-muted-foreground leading-snug">
                            {cat.desc}
                          </p>
                        </div>
                      </CardContent>
                    </Card>
                  ))}
                </div>
              ) : (
                // CONTENT LIST
                <div>
                  <div className="mb-6 border-b border-border pb-4">
                    <h2 className="text-3xl font-extrabold capitalize flex items-center gap-3">
                      {(() => {
                          const CatIcon = CATEGORIES.find(c => c.id === selectedCategory)?.icon;
                          return CatIcon ? <CatIcon className={`w-8 h-8 ${CATEGORIES.find(c => c.id === selectedCategory)?.color}`} /> : null;
                      })()}
                      {selectedCategory.replace("_", " ")} 
                    </h2>
                    <p className="text-muted-foreground mt-1 ml-11">
                        Fresh selections for {data?.date}
                    </p>
                  </div>
                  {renderContent()}
                </div>
              )}
            </>
          )}
        </div>
      }
      showTopBanner
      showSidebar
      showBottomBanner
      hideLegalDisclaimer
    />
  );
}
