import { useState, useMemo, useEffect } from "react";
import CalculatorVerticalLayout from "@/components/templates/CalculatorVerticalLayout";
import DailyHoroscopeWidget from "@/components/calculators/DailyQuotes/DailyHoroscopeWidget";
import QuoteCard, { DailyQuoteItem } from "@/components/calculators/DailyQuotes/QuoteCard";
import { 
  Briefcase, Rocket, Camera, Laptop, 
  Smile, HeartHandshake, Brain, Moon, 
  ArrowLeft, Sparkles, RefreshCw, Loader2 
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { toast } from "@/components/ui/sonner";

// JSON file URL generated by n8n (RAW)
const DATA_URL = "https://raw.githubusercontent.com/williamsasmartins/smartkit-onepage-wonder/main/public/daily_horoscope.json";

// Expected JSON structure
type DailyDataPacket = {
  date: string;
  hero: { text: string; author: string };
  content: {
    professional: DailyQuoteItem[];
    motivation: DailyQuoteItem[];
    captions: DailyQuoteItem[];
    tech: DailyQuoteItem[];
    fun: DailyQuoteItem[];
    faith: DailyQuoteItem[];
    wisdom: DailyQuoteItem[];
  };
  // Signs are at the root, but the Widget handles them separately
};

type CategoryKey = keyof DailyDataPacket["content"] | "horoscope" | "dream";

export default function DailyQuotesPage() {
  const [data, setData] = useState<DailyDataPacket | null>(null);
  const [loading, setLoading] = useState(true);
  const [selectedCategory, setSelectedCategory] = useState<CategoryKey | null>(null);
  const [liked, setLiked] = useState<Set<number>>(new Set());
  const [shuffleSeed, setShuffleSeed] = useState(0);

  // FETCH REAL DATA
  useEffect(() => {
    const fetchData = async () => {
      try {
        // Appends timestamp to avoid aggressive browser caching
        const res = await fetch(`${DATA_URL}?t=${new Date().getTime()}`);
        if (!res.ok) throw new Error("Failed to load daily inspiration");
        const json = await res.json();
        setData(json);
      } catch (error) {
        console.error("Error fetching data:", error);
        toast("Could not load today's inspiration. Please try again later.");
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, []);

  const toggleLike = (id: number) => {
    const next = new Set(liked);
    if (next.has(id)) next.delete(id);
    else next.add(id);
    setLiked(next);
  };

  const handleShuffle = () => {
    setShuffleSeed(prev => prev + 1);
  };

  const CATEGORIES = [
    { id: "horoscope", label: "Daily Horoscope", icon: Sparkles, color: "text-purple-500", desc: "Your zodiac forecast" },
    { id: "dream", label: "Dream Interpreter", icon: Moon, color: "text-indigo-400", desc: "Find the meaning (AI)" },
    { id: "professional", label: "Professional", icon: Briefcase, color: "text-blue-500", desc: "Career & Success" },
    { id: "motivation", label: "Motivation", icon: Rocket, color: "text-orange-500", desc: "Energy & Mindset" },
    { id: "captions", label: "Social Captions", icon: Camera, color: "text-pink-500", desc: "For Instagram/TikTok" },
    { id: "tech", label: "Tech & Geek", icon: Laptop, color: "text-cyan-500", desc: "Coding humor" },
    { id: "fun", label: "Fun & Sarcasm", icon: Smile, color: "text-yellow-500", desc: "Witty & Relatable" },
    { id: "faith", label: "Faith & Verses", icon: HeartHandshake, color: "text-emerald-500", desc: "Spiritual comfort" },
    { id: "wisdom", label: "Wisdom", icon: Brain, color: "text-violet-500", desc: "Famous quotes" },
  ];

  // Filter and Shuffle Logic
  const currentItems = useMemo(() => {
    if (!data || !selectedCategory || selectedCategory === "horoscope" || selectedCategory === "dream") return [];
    
    // @ts-ignore
    const itemsList = data.content?.[selectedCategory as keyof DailyDataPacket["content"]];
    
    if (!itemsList || !Array.isArray(itemsList)) return [];

    const allItems = [...itemsList];
    
    // Shuffle
    if (shuffleSeed >= 0) {
        for (let i = allItems.length - 1; i > 0; i--) {
            const j = Math.floor(Math.random() * (i + 1));
            [allItems[i], allItems[j]] = [allItems[j], allItems[i]];
        }
    }
    
    // Show up to 6 items
    return allItems.slice(0, 6); 
  }, [selectedCategory, shuffleSeed, data]);

  const renderContent = () => {
    if (selectedCategory === "horoscope") {
      // The widget fetches internally, so it works independently
      return <DailyHoroscopeWidget showNavigation={false} />;
    }

    if (selectedCategory === "dream") {
      return (
        <div className="text-center py-20 bg-muted/20 rounded-xl border border-dashed border-border animate-in fade-in zoom-in-95">
          <div className="w-20 h-20 mx-auto bg-indigo-100 dark:bg-indigo-900/30 rounded-full flex items-center justify-center mb-6">
            <Moon className="w-10 h-10 text-indigo-500" />
          </div>
          <h3 className="text-2xl font-bold mb-3">Dream Interpreter AI</h3>
          <p className="text-muted-foreground max-w-md mx-auto mb-8 leading-relaxed">
            Did you dream about flying, falling, or losing teeth? Our AI interpretation tool is being calibrated to uncover the hidden meanings of your subconscious.
          </p>
          <div className="flex justify-center gap-4">
            <Button variant="outline" onClick={() => setSelectedCategory(null)}>
              Go Back
            </Button>
            <Button disabled>Coming Soon</Button>
          </div>
        </div>
      );
    }

    if (currentItems.length === 0) return (
      <div className="text-center py-10 text-muted-foreground">
        No inspiration found for this category today. Try again tomorrow!
      </div>
    );

    return (
      <div className="space-y-6 animate-in fade-in slide-in-from-right-8 duration-300">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {currentItems.map((item) => (
            <QuoteCard
              key={item.id}
              item={item}
              categoryLabel={selectedCategory?.toString() || ""}
              isLiked={liked.has(item.id)}
              onToggleLike={toggleLike}
              tone={selectedCategory === "tech" ? "tech" : "default"}
            />
          ))}
        </div>
        
        <div className="flex justify-center pt-8 pb-4">
            <Button variant="secondary" size="lg" onClick={handleShuffle} className="gap-2 shadow-sm">
                <RefreshCw className="w-4 h-4" />
                Shuffle Suggestions
            </Button>
        </div>
      </div>
    );
  };

  const seoDescription = (
    <div className="max-w-3xl mx-auto text-center space-y-4 mb-10 text-muted-foreground">
      <p className="text-lg leading-relaxed">
        Start your day with clarity and purpose. Explore our comprehensive <strong>Daily Inspiration Hub</strong> featuring 
        accurate <span className="text-foreground font-medium">Horoscope forecasts</span>, 
        deep <span className="text-foreground font-medium">Dream Meanings</span>, and a curated collection of 
        <span className="text-foreground font-medium"> Motivational Quotes</span>.
      </p>
    </div>
  );

  return (
    <CalculatorVerticalLayout
      title="Daily Inspiration Hub"
      description=""
      widget={
        <div className="min-h-[600px]">
          {loading ? (
            <div className="flex flex-col items-center justify-center py-20 gap-4">
              <Loader2 className="w-10 h-10 animate-spin text-primary" />
              <p className="text-muted-foreground animate-pulse">Connecting to the stars...</p>
            </div>
          ) : (
            <>
              {/* Hero Section from real JSON */}
              {!selectedCategory && data?.hero && (
                 <div className="relative rounded-2xl overflow-hidden p-8 text-center bg-gradient-to-br from-indigo-500/10 via-purple-500/10 to-background border border-border mb-8 animate-in fade-in duration-700">
                   <div className="relative z-10 max-w-3xl mx-auto space-y-4">
                     <div className="inline-flex items-center justify-center px-3 py-1 rounded-full bg-primary/10 text-primary text-xs font-bold uppercase tracking-wider mb-2">
                       Quote of the Day • {data.date}
                     </div>
                     <h1 className="text-2xl md:text-3xl font-extrabold text-foreground leading-tight">
                       "{data.hero.text}"
                     </h1>
                     <p className="text-lg text-muted-foreground font-medium">
                       — {data.hero.author}
                     </p>
                   </div>
                   {seoDescription}
                 </div>
              )}

              {/* Header with Back Button */}
              {selectedCategory && (
                <div className="flex items-center justify-between mb-8">
                  <Button 
                    variant="ghost" 
                    onClick={() => setSelectedCategory(null)}
                    className="gap-2 pl-0 hover:bg-transparent hover:text-primary group"
                  >
                    <div className="p-1 rounded-full bg-muted group-hover:bg-primary/10 transition-colors">
                        <ArrowLeft className="w-4 h-4" />
                    </div>
                    <span className="font-semibold text-lg">Back to Hub</span>
                  </Button>
                </div>
              )}

              {/* HUB MENU */}
              {!selectedCategory ? (
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                  {CATEGORIES.map((cat) => (
                    <Card 
                      key={cat.id} 
                      className="cursor-pointer hover:border-primary/50 hover:bg-accent/5 hover:-translate-y-1 transition-all duration-300 group shadow-sm hover:shadow-md"
                      onClick={() => setSelectedCategory(cat.id as CategoryKey)}
                    >
                      <CardContent className="p-6 flex items-start gap-4">
                        <div className={`p-3 rounded-xl bg-muted/50 group-hover:bg-background border border-transparent group-hover:border-border transition-colors ${cat.color}`}>
                          <cat.icon className="w-7 h-7" />
                        </div>
                        <div>
                          <h3 className="font-bold text-lg leading-none mb-2 group-hover:text-primary transition-colors">
                            {cat.label}
                          </h3>
                          <p className="text-sm text-muted-foreground leading-snug">
                            {cat.desc}
                          </p>
                        </div>
                      </CardContent>
                    </Card>
                  ))}
                </div>
              ) : (
                // CONTENT LIST
                <div>
                  <div className="mb-6 border-b border-border pb-4">
                    <h2 className="text-3xl font-extrabold capitalize flex items-center gap-3">
                      {(() => {
                          const CatIcon = CATEGORIES.find(c => c.id === selectedCategory)?.icon;
                          return CatIcon ? <CatIcon className={`w-8 h-8 ${CATEGORIES.find(c => c.id === selectedCategory)?.color}`} /> : null;
                      })()}
                      {selectedCategory.replace("_", " ")} 
                    </h2>
                    <p className="text-muted-foreground mt-1 ml-11">
                        Fresh selections for {data?.date}
                    </p>
                  </div>
                  {renderContent()}
                </div>
              )}
            </>
          )}
        </div>
      }
      showTopBanner
      showSidebar
      showBottomBanner
      hideLegalDisclaimer
    />
  );
}
