// AUTO-GENERATED by scripts/split-registry.cjs — DO NOT EDIT BY HAND.
// Per-category slice of the master CalculatorEntry registry.
// Re-run `node scripts/split-registry.cjs` after editing the master.

import type { CalculatorEntry } from "@/data/calculatorRegistry";

export const timeEntries: CalculatorEntry[] = [
  {
      slug: "world-clock",
      title: "Real-Time World Clock",
      category: "time",
      subcategory: "general",
      description: "A dynamic digital clock displaying time and date worldwide. Choose local, popular cities, or search globally.",
      loader: () => import("@/components/calculators/Time/WorldClockCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "days-between-dates",
      title: "Days Between Dates (date duration)",
      category: "time",
      subcategory: "dates-durations",
      description: "Calculate the number of days, months, or years between two specific dates. Essential for planning projects, calculating age, or tracking duration.",
      loader: () => import("@/components/calculators/Time/DaysBetweenDatesCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "add-subtract-date",
      title: "Add/Subtract Date (days/months/years)",
      category: "time",
      subcategory: "dates-durations",
      description: "Add or subtract a specific number of days, months, or years from a given starting date. Perfect for deadline tracking.",
      loader: () => import("@/components/calculators/Time/AddSubtractDateCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "add-subtract-time",
      title: "Add/Subtract Time (h/min/s)",
      category: "time",
      subcategory: "dates-durations",
      description: "Add or subtract hours, minutes, or seconds from a starting time. Useful for scheduling and time management.",
      loader: () => import("@/components/calculators/Time/AddSubtractTimeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "business-days",
      title: "Business Days Calculator (exclude weekends/holidays)",
      category: "time",
      subcategory: "dates-durations",
      description: "Calculate the number of working days between two dates, automatically excluding weekends and customizable holidays.",
      loader: () => import("@/components/calculators/Time/BusinessDaysCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "iso-week-number",
      title: "Week Number & ISO Week Finder",
      category: "time",
      subcategory: "dates-durations",
      description: "Find the ISO week number for any given date. Standardized for business and international scheduling.",
      loader: () => import("@/components/calculators/Time/IsoWeekNumberCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "age-calculator",
      title: "Age Calculator (years/months/days)",
      category: "time",
      subcategory: "dates-durations",
      description: "Calculate a person's age precisely in years, months, and days.",
      loader: () => import("@/components/calculators/Time/AgeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "date-difference-hms",
      title: "Date Difference in Hours/Minutes/Seconds",
      category: "time",
      subcategory: "dates-durations",
      description: "Determine the exact difference between two dates in total hours, minutes, and seconds.",
      loader: () => import("@/components/calculators/Time/DateDifferenceHmsCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "julian-date-day-number",
      title: "Julian Date/Day Calculator",
      category: "time",
      subcategory: "dates-durations",
      description: "Convert any date into its Julian Date or Day Number (1-366). Used in science, astronomy, and military applications.",
      loader: () => import("@/components/calculators/Time/JulianDateDayNumberCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "leap-year-checker",
      title: "Leap Year Checker",
      category: "time",
      subcategory: "dates-durations",
      description: "Check quickly whether a given year is a leap year.",
      loader: () => import("@/components/calculators/Time/LeapYearCheckerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "time-zone-converter",
      title: "Time Zone Converter (between cities)",
      category: "time",
      subcategory: "time-zones-clocks",
      description: "Convert time instantly between different global cities and time zones. Ideal for international communication.",
      loader: () => import("@/components/calculators/Time/TimeZoneConverterCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "world-clock",
      title: "World Clock (list of cities)",
      category: "time",
      subcategory: "time-zones-clocks",
      description: "Display the current time for a list of major global cities. Quick reference for time differences.",
      loader: () => import("@/components/calculators/Time/WorldClockCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "meeting-planner-time-zones",
      title: "Meeting Planner (common time across time zones)",
      category: "time",
      subcategory: "time-zones-clocks",
      description: "Find the best overlapping time for a meeting across multiple time zones. Maximize attendance for global teams.",
      loader: () => import("@/components/calculators/Time/MeetingPlannerTimeZonesCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "utc-local-time-converter",
      title: "UTC ↔ Local Time Converter",
      category: "time",
      subcategory: "time-zones-clocks",
      description: "Convert Coordinated Universal Time (UTC) to your local time zone and vice versa.",
      loader: () => import("@/components/calculators/Time/UtcLocalTimeConverterCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dst-change-checker",
      title: "DST Change Checker (time changes)",
      category: "time",
      subcategory: "time-zones-clocks",
      description: "Check upcoming Daylight Saving Time (DST) changes for any location and see the time shift.",
      loader: () => import("@/components/calculators/Time/DstChangeCheckerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "epoch-unix-time-converter",
      title: "Epoch/Unix Time Converter",
      category: "time",
      subcategory: "time-zones-clocks",
      description: "Convert between human-readable dates and the Epoch (Unix) timestamp. Essential for programming and data logging.",
      loader: () => import("@/components/calculators/Time/EpochUnixTimeConverterCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "calendar-generator-pdf",
      title: "Calendar Generator (month/year, export PDF)",
      category: "time",
      subcategory: "calendar-extras",
      description: "Generate and customize a monthly or yearly calendar, with an option to export as a PDF.",
      loader: () => import("@/components/calculators/Time/CalendarGeneratorPdfCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "workday-workweek-planner",
      title: "Workday/Workweek Planner (customized)",
      category: "time",
      subcategory: "calendar-extras",
      description: "Customize your work schedule (e.g., 4/10s, 9/80s) and plan your workdays/workweeks efficiently.",
      loader: () => import("@/components/calculators/Time/WorkdayWorkweekPlannerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "countdown-timer",
      title: "Countdown Timer (until a date/time)",
      category: "time",
      subcategory: "calendar-extras",
      description: "Set a countdown timer to track the exact time remaining until a specific future date or event.",
      loader: () => import("@/components/calculators/Time/CountdownTimerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "stopwatch-split-times",
      title: "Stopwatch & Split Times (web tool)",
      category: "time",
      subcategory: "calendar-extras",
      description: "Simple web-based stopwatch with functionality to record and manage split times.",
      loader: () => import("@/components/calculators/Time/StopwatchSplitTimesCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "day-of-week-for-date",
      title: "Day of Week for Any Date (includes Doomsday rule)",
      category: "time",
      subcategory: "calendar-extras",
      description: "Determine the exact day of the week for any past or future date (and learn the 'Doomsday Rule').",
      loader: () => import("@/components/calculators/Time/DayOfWeekForDateCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "count-specific-weekdays",
      title: "Count Specific Weekdays Between Dates (e.g., all Fridays)",
      category: "time",
      subcategory: "calendar-extras",
      description: "Count the total occurrence of a specific weekday (e.g., all Mondays) between two dates.",
      loader: () => import("@/components/calculators/Time/CountSpecificWeekdaysCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "sunrise-sunset-times",
      title: "Sunrise and Sunset Times",
      category: "time",
      subcategory: "sun-moon-astronomy",
      description: "Calculate the exact sunrise and sunset times for any location and date. Essential for photographers and planners.",
      loader: () => import("@/components/calculators/Time/SunriseSunsetTimesCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "moon-phases",
      title: "Moon Phases",
      category: "time",
      subcategory: "sun-moon-astronomy",
      description: "Track the lunar cycle and predict the phase of the moon (New, Full, Quarter) for any date.",
      loader: () => import("@/components/calculators/Time/MoonPhasesCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "astronomical-seasons",
      title: "Seasons Calculator",
      category: "time",
      subcategory: "sun-moon-astronomy",
      description: "Calculate the exact date and time for the start of the astronomical seasons (solstices and equinoxes).",
      loader: () => import("@/components/calculators/Time/AstronomicalSeasonsCalculator"),
      urlStyle: "flat"
    }
];
