// AUTO-GENERATED by scripts/split-registry.cjs — DO NOT EDIT BY HAND.
// Per-category slice of the master CalculatorEntry registry.
// Re-run `node scripts/split-registry.cjs` after editing the master.

import type { CalculatorEntry } from "@/data/calculatorRegistry";

export const electricalEntries: CalculatorEntry[] = [
  {
      slug: "ohms-law",
      title: "Ohm's Law Calculator (V, I, R, P)",
      category: "electrical",
      subcategory: "basic-electrical-circuit-calculations",
      description: "Calculate Voltage, Current, Resistance, or Power using Ohm's Law.",
      loader: () => import("@/components/calculators/Electrical/OhmsLawCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "voltage-drop-wire-length",
      title: "Voltage Drop Calculator (Wire Gauge & Length)",
      category: "electrical",
      subcategory: "basic-electrical-circuit-calculations",
      description: "Calculate voltage drop based on wire gauge, length, and current.",
      loader: () => import("@/components/calculators/Electrical/VoltageDropWireLengthCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "current-amperage",
      title: "Current (Amperage) Calculator",
      category: "electrical",
      subcategory: "basic-electrical-circuit-calculations",
      description: "Calculate electrical current in a circuit.",
      loader: () => import("@/components/calculators/Electrical/CurrentAmperageCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "power-watts",
      title: "Power (Watts) Calculator",
      category: "electrical",
      subcategory: "basic-electrical-circuit-calculations",
      description: "Calculate electrical power in Watts.",
      loader: () => import("@/components/calculators/Electrical/PowerWattsCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "electrical-resistance",
      title: "Electrical Resistance Calculator",
      category: "electrical",
      subcategory: "basic-electrical-circuit-calculations",
      description: "Calculate resistance in a circuit.",
      loader: () => import("@/components/calculators/Electrical/ElectricalResistanceCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "parallel-series-circuit",
      title: "Parallel & Series Circuit Calculator",
      category: "electrical",
      subcategory: "basic-electrical-circuit-calculations",
      description: "Calculate equivalent resistance for parallel and series circuits.",
      loader: () => import("@/components/calculators/Electrical/ParallelSeriesCircuitCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "resistor-color-code",
      title: "Resistor Color Code Decoder",
      category: "electrical",
      subcategory: "basic-electrical-circuit-calculations",
      description: "Decode resistor color bands to find resistance value.",
      loader: () => import("@/components/calculators/Electrical/ResistorColorCodeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "electrical-load-capacity",
      title: "Electrical Load Capacity (Breaker/Panel) Calculator",
      category: "electrical",
      subcategory: "basic-electrical-circuit-calculations",
      description: "Estimate load capacity for breakers and electrical panels.",
      loader: () => import("@/components/calculators/Electrical/ElectricalLoadCapacityCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "wire-size-awg-kcmil",
      title: "Wire Size (AWG/KCMIL) Calculator",
      category: "electrical",
      subcategory: "wiring-conductors-breakers",
      description: "Determine appropriate wire size (AWG/KCMIL) for a given load.",
      loader: () => import("@/components/calculators/Electrical/WireSizeAwgKcmilCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "breaker-size",
      title: "Breaker Size Calculator",
      category: "electrical",
      subcategory: "wiring-conductors-breakers",
      description: "Calculate the correct circuit breaker size for a specific load.",
      loader: () => import("@/components/calculators/Electrical/BreakerSizeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "conduit-fill",
      title: "Conduit Fill Calculator",
      category: "electrical",
      subcategory: "wiring-conductors-breakers",
      description: "Calculate the maximum number of wires allowed in a conduit.",
      loader: () => import("@/components/calculators/Electrical/ConduitFillCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cable-ampacity-by-distance",
      title: "Cable Ampacity by Distance Calculator",
      category: "electrical",
      subcategory: "wiring-conductors-breakers",
      description: "Calculate cable ampacity accounting for distance and voltage drop.",
      loader: () => import("@/components/calculators/Electrical/CableAmpacityByDistanceCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "three-phase-power",
      title: "3-Phase Power Calculator",
      category: "electrical",
      subcategory: "wiring-conductors-breakers",
      description: "Calculate power, voltage, and current in 3-phase systems.",
      loader: () => import("@/components/calculators/Electrical/ThreePhasePowerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "transformer-kva",
      title: "Transformer kVA Calculator",
      category: "electrical",
      subcategory: "wiring-conductors-breakers",
      description: "Calculate Transformer capacity in kVA.",
      loader: () => import("@/components/calculators/Electrical/TransformerKvaCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "motor-fla",
      title: "Motor FLA (Full Load Amps) Calculator",
      category: "electrical",
      subcategory: "wiring-conductors-breakers",
      description: "Calculate Full Load Amps for electric motors.",
      loader: () => import("@/components/calculators/Electrical/MotorFlaCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "conduit-bending",
      title: "Conduit Bending Calculator",
      category: "electrical",
      subcategory: "wiring-conductors-breakers",
      description: "Calculate bend deduction and other values for conduit bending.",
      loader: () => import("@/components/calculators/Electrical/ConduitBendingCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "led-power-consumption",
      title: "LED Lighting Power Consumption Calculator",
      category: "electrical",
      subcategory: "lighting-energy-cost-home-electrical",
      description: "Estimate power consumption and savings with LED lighting.",
      loader: () => import("@/components/calculators/Electrical/LedPowerConsumptionCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "lumens-to-watts",
      title: "Lighting Lumens-to-Watts Converter",
      category: "electrical",
      subcategory: "lighting-energy-cost-home-electrical",
      description: "Convert between Lumens and Watts for different light sources.",
      loader: () => import("@/components/calculators/Electrical/LumensToWattsCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "electricity-cost-per-hour-month",
      title: "Electricity Cost per Hour/Month Calculator",
      category: "electrical",
      subcategory: "lighting-energy-cost-home-electrical",
      description: "Calculate electricity cost based on usage and rate.",
      loader: () => import("@/components/calculators/Electrical/ElectricityCostPerHourMonthCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "lighting-circuit-load-planner",
      title: "Lighting Circuit Load Planner",
      category: "electrical",
      subcategory: "lighting-energy-cost-home-electrical",
      description: "Plan electrical load for lighting circuits.",
      loader: () => import("@/components/calculators/Electrical/LightingCircuitLoadPlannerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "generator-sizing",
      title: "Generator Sizing Calculator",
      category: "electrical",
      subcategory: "lighting-energy-cost-home-electrical",
      description: "Estimate the size of generator needed for your home or equipment.",
      loader: () => import("@/components/calculators/Electrical/GeneratorSizingCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "power-factor",
      title: "Power Factor Calculator",
      category: "electrical",
      subcategory: "lighting-energy-cost-home-electrical",
      description: "Calculate power factor and correction capacitor size.",
      loader: () => import("@/components/calculators/Electrical/PowerFactorCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "pv-system-production-estimator",
      title: "PV System Production Estimator (e.g., PVWatts)",
      category: "electrical",
      subcategory: "renewable-energy-battery-systems",
      description: "Estimate energy production for solar PV systems.",
      loader: () => import("@/components/calculators/Electrical/PvSystemProductionEstimatorCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "off-grid-system-sizing",
      title: "Off-Grid System Sizing Calculator",
      category: "electrical",
      subcategory: "renewable-energy-battery-systems",
      description: "Size solar and battery systems for off-grid applications.",
      loader: () => import("@/components/calculators/Electrical/OffGridSystemSizingCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "solar-panel-output-array-sizing",
      title: "Solar Panel Output & Array Sizing Calculator",
      category: "electrical",
      subcategory: "renewable-energy-battery-systems",
      description: "Calculate solar panel output and size your array.",
      loader: () => import("@/components/calculators/Electrical/SolarPanelOutputArraySizingCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "solar-battery-bank-sizing",
      title: "Solar Battery Bank Sizing Calculator",
      category: "electrical",
      subcategory: "renewable-energy-battery-systems",
      description: "Size battery banks for solar energy storage.",
      loader: () => import("@/components/calculators/Electrical/SolarBatteryBankSizingCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "inverter-load-capacity",
      title: "Inverter Load Capacity Calculator",
      category: "electrical",
      subcategory: "renewable-energy-battery-systems",
      description: "Calculate required inverter size for your loads.",
      loader: () => import("@/components/calculators/Electrical/InverterLoadCapacityCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "ev-charging-time",
      title: "EV Charging Time Calculator",
      category: "electrical",
      subcategory: "renewable-energy-battery-systems",
      description: "Estimate time required to charge an electric vehicle.",
      loader: () => import("@/components/calculators/Electrical/EvChargingTimeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "battery-runtime-estimator",
      title: "Battery Runtime Estimator",
      category: "electrical",
      subcategory: "renewable-energy-battery-systems",
      description: "Estimate how long a battery will last under a specific load.",
      loader: () => import("@/components/calculators/Electrical/BatteryRuntimeEstimatorCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "system-payback-period-roi",
      title: "System Payback Period (ROI) Calculator",
      category: "electrical",
      subcategory: "renewable-energy-battery-systems",
      description: "Calculate ROI and payback period for renewable energy systems.",
      loader: () => import("@/components/calculators/Electrical/SystemPaybackPeriodRoiCalculator"),
      urlStyle: "flat"
    }
];
