import { useState, useMemo } from "react";
import CalculatorVerticalLayout from '@/components/templates/CalculatorVerticalLayout';
import { Card, CardContent } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { Zap, BookOpen, AlertTriangle, ExternalLink } from "lucide-react";
import useFaqJsonLd from "@/hooks/useFaqJsonLd";

export default function SystemPaybackPeriodRoiCalculator() {
  /**
   * Inputs:
   * val1 = Wh (Watt-hours consumed per day)
   * val2 = Ah (Battery capacity in Amp-hours)
   * val3 = Sun Hours (Average peak sun hours per day)
   *
   * Assumptions:
   * - System voltage: 12V (common for small solar systems)
   * - Cost per watt installed: $3.00 (typical residential solar cost)
   * - Battery cost per Ah: $10 (typical lead-acid battery cost)
   * - Daily energy cost savings = Wh consumed * cost per kWh (assumed $0.13/kWh)
   *
   * Calculation:
   * - Calculate system size in watts needed = Wh / Sun Hours
   * - Calculate solar system cost = system size * cost per watt
   * - Calculate battery cost = Ah * cost per Ah
   * - Total system cost = solar system cost + battery cost
   * - Daily savings in $ = Wh / 1000 * $0.13
   * - Payback period (days) = total cost / daily savings
   * - Payback period (years) = payback period (days) / 365
   */

  const [inputs, setInputs] = useState({
    val1: "", // Wh
    val2: "", // Ah
    val3: "", // Sun Hours
  });

  const handleInputChange = (field: string, value: string) => {
    // Allow only numbers and decimals
    if (/^\d*\.?\d*$/.test(value)) {
      setInputs((prev) => ({ ...prev, [field]: value }));
    }
  };

  const results = useMemo(() => {
    const Wh = parseFloat(inputs.val1);
    const Ah = parseFloat(inputs.val2);
    const sunHours = parseFloat(inputs.val3);

    if (isNaN(Wh) || Wh <= 0) {
      return {
        primary: "-",
        secondary: "Invalid Wh",
        details: "Please enter a valid Watt-hour consumption (> 0).",
        feedback: "",
      };
    }
    if (isNaN(Ah) || Ah <= 0) {
      return {
        primary: "-",
        secondary: "Invalid Ah",
        details: "Please enter a valid battery capacity in Amp-hours (> 0).",
        feedback: "",
      };
    }
    if (isNaN(sunHours) || sunHours <= 0) {
      return {
        primary: "-",
        secondary: "Invalid Sun Hours",
        details: "Please enter a valid average peak sun hours per day (> 0).",
        feedback: "",
      };
    }

    // Constants
    const systemVoltage = 12; // volts
    const costPerWatt = 3.0; // $ per watt installed solar
    const costPerAh = 10.0; // $ per Ah battery
    const costPerKWh = 0.13; // $ per kWh electricity cost

    // Calculate system size in watts needed
    const systemWatts = Wh / sunHours;

    // Calculate solar system cost
    const solarCost = systemWatts * costPerWatt;

    // Calculate battery cost
    const batteryCost = Ah * costPerAh;

    // Total system cost
    const totalCost = solarCost + batteryCost;

    // Daily savings in $
    const dailySavings = (Wh / 1000) * costPerKWh;

    if (dailySavings === 0) {
      return {
        primary: "-",
        secondary: "No Savings",
        details: "Daily savings calculated as zero, check inputs.",
        feedback: "",
      };
    }

    // Payback period in days and years
    const paybackDays = totalCost / dailySavings;
    const paybackYears = paybackDays / 365;

    return {
      primary: paybackYears.toFixed(2),
      secondary: "Years to Payback",
      details: `System Size: ${systemWatts.toFixed(1)} W | Total Cost: $${totalCost.toFixed(
        2
      )} | Daily Savings: $${dailySavings.toFixed(2)}`,
      feedback:
        paybackYears < 1
          ? "Excellent ROI: Payback period less than 1 year."
          : paybackYears < 5
          ? "Good ROI: Payback period within 5 years."
          : "Long ROI: Payback period exceeds 5 years, consider system sizing or cost optimization.",
    };
  }, [inputs]);

  const faqs = [
    {
      question: "What is the System Payback Period (ROI)?",
      answer:
        "The System Payback Period, or Return on Investment (ROI), is the time it takes for the savings generated by a renewable energy system to cover its initial installation and equipment costs. It is typically expressed in years. A shorter payback period indicates a more financially attractive investment. This calculator estimates the payback period based on your daily energy consumption, battery capacity, and average sun hours.",
    },
    {
      question: "Why do I need to input Watt-hours and Amp-hours?",
      answer:
        "Watt-hours (Wh) represent your daily energy consumption, which determines the size of the solar system required. Amp-hours (Ah) represent the battery capacity needed to store energy for use when the sun is not shining. Both values are critical to accurately estimate the system cost and thus the payback period. Underestimating these values can lead to undersized systems and longer payback periods.",
    },
    {
      question: "How does average sun hours affect the calculation?",
      answer:
        "Average peak sun hours represent the average number of hours per day when solar irradiance is strong enough to generate maximum power. This value directly impacts the size of the solar panel array needed. More sun hours mean smaller panels and lower costs, reducing the payback period. Conversely, fewer sun hours require larger panels and increase system costs.",
    },
    {
      question: "Can this calculator be used for grid-tied and off-grid systems?",
      answer:
        "This calculator is primarily designed for renewable energy systems with battery storage, such as off-grid or hybrid systems. For grid-tied systems without batteries, the battery capacity input can be set to zero, but the payback period may not be accurate as it doesn't account for net metering or feed-in tariffs. Always consider your system configuration when interpreting results.",
    },
    {
      question: "What factors can affect the accuracy of the payback period estimate?",
      answer:
        "Several factors can influence the accuracy of the payback period estimate, including variations in electricity rates, system installation costs, maintenance expenses, battery lifespan, and changes in energy consumption patterns. Additionally, incentives, tax credits, and rebates can significantly reduce upfront costs and improve ROI. This calculator provides a baseline estimate; consult a professional for detailed financial analysis.",
    },
  ];
  const faqJsonLd = useFaqJsonLd(faqs);

  const example = {
    title: "Real World Example",
    scenario:
      "Running a small off-grid cabin that consumes 1200 Wh per day, with a 100 Ah battery bank, located in an area with 5 average peak sun hours per day.",
    steps: [
      {
        label: "Step 1: Input Daily Energy Consumption",
        explanation: "Enter 1200 Wh as the daily energy consumption based on your load calculations.",
      },
      {
        label: "Step 2: Input Battery Capacity",
        explanation:
          "Enter 100 Ah to represent your battery bank capacity, ensuring sufficient storage for nighttime and cloudy days.",
      },
      {
        label: "Step 3: Input Average Sun Hours",
        explanation:
          "Enter 5 hours, representing the average peak sun hours for your location, which affects solar panel sizing.",
      },
      {
        label: "Step 4: Calculate Payback Period",
        explanation:
          "The calculator estimates the system size, total cost, daily savings, and payback period in years based on these inputs.",
      },
    ],
    result:
      "The system size is approximately 240 W, total system cost is about $1,320, daily savings are $0.16, resulting in a payback period of approximately 22.5 years. This indicates the need to optimize system size or reduce costs for better ROI.",
  };

  const references = [
    {
      title: "NEC Table 310.16",
      description: "Allowable Ampacities of Insulated Conductors.",
      url: "https://www.nfpa.org/",
    },
    {
      title: "NREL Solar Radiation Data",
      description:
        "National Renewable Energy Laboratory provides solar radiation and sun hours data for accurate system design.",
      url: "https://www.nrel.gov/grid/solar-resource/solar-data.html",
    },
    {
      title: "Battery University - Battery Basics",
      description:
        "Comprehensive resource on battery types, capacities, and maintenance for renewable energy systems.",
      url: "https://batteryuniversity.com/article/bu-808a-battery-capacity",
    },
  ];

  const widget = (
    <div className="space-y-6">
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="space-y-2">
          <Label htmlFor="wh-input">Daily Energy Consumption (Wh)</Label>
          <Input
            id="wh-input"
            type="number"
            min={0}
            step="any"
            placeholder="e.g. 1200"
            value={inputs.val1}
            onChange={(e) => handleInputChange("val1", e.target.value)}
          />
        </div>
        <div className="space-y-2">
          <Label htmlFor="ah-input">Battery Capacity (Ah)</Label>
          <Input
            id="ah-input"
            type="number"
            min={0}
            step="any"
            placeholder="e.g. 100"
            value={inputs.val2}
            onChange={(e) => handleInputChange("val2", e.target.value)}
          />
        </div>
        <div className="space-y-2">
          <Label htmlFor="sun-hours-input">Average Peak Sun Hours (hours/day)</Label>
          <Input
            id="sun-hours-input"
            type="number"
            min={0}
            step="any"
            placeholder="e.g. 5"
            value={inputs.val3}
            onChange={(e) => handleInputChange("val3", e.target.value)}
          />
        </div>
      </div>

      <Button className="w-full bg-blue-600 hover:bg-blue-700 h-12 text-lg" onClick={() => {}}>
        <Zap className="mr-2 h-5 w-5" /> Calculate
      </Button>

      {results && (
        <Card className="mt-6 bg-slate-50 dark:bg-slate-900 border-blue-200 shadow-md">
          <CardContent className="p-6 text-center">
            <span className="text-sm font-semibold text-slate-500 uppercase">Result</span>
            <div className="text-5xl font-extrabold text-blue-600 my-3">{results.primary}</div>
            <div className="text-xl font-bold mt-2">{results.secondary}</div>
            <p className="text-xs text-slate-500 mt-2">{results.details}</p>
            {results.feedback && (
              <>
                <Separator className="my-4" />
                <p className="text-sm font-semibold text-blue-700 dark:text-blue-400">{results.feedback}</p>
              </>
            )}
          </CardContent>
        </Card>
      )}
    </div>
  );

  const editorial = (
    <div className="space-y-12">
      <section id="how-to-use" className="scroll-mt-24">
        <h2 className="text-2xl font-bold mb-4 text-slate-900 dark:text-slate-100">How to use this calculator</h2>
        <ol className="list-decimal pl-5 space-y-3 text-slate-600 dark:text-slate-400">
          <li>
            Enter your average daily energy consumption in Watt-hours (Wh). This is the total energy your system uses in a day.
          </li>
          <li>
            Enter your battery bank capacity in Amp-hours (Ah). This represents the total storage capacity of your batteries.
          </li>
          <li>
            Enter the average peak sun hours per day for your location. This value affects how much solar energy your panels can generate daily.
          </li>
          <li>
            Click the "Calculate" button to compute the estimated system payback period in years, along with system size and cost details.
          </li>
          <li>
            Review the results and consider adjusting inputs to optimize your system design and ROI.
          </li>
        </ol>
      </section>

      <section id="guide">
        <h2 className="text-2xl font-bold mb-4 flex items-center gap-2 text-slate-900 dark:text-slate-100">
          <BookOpen className="w-6 h-6 text-blue-500" /> Complete Guide to System Payback Period (ROI) Calculator
        </h2>
        <div className="prose prose-slate dark:prose-invert">
          <p>
            The System Payback Period (ROI) Calculator estimates how long it will take for your renewable energy system to pay for itself through energy savings. It combines your daily energy consumption, battery capacity, and solar resource availability to calculate the system size and cost.
          </p>
          <p>
            The calculator assumes a 12V system voltage, typical installation costs per watt, and battery costs per amp-hour. It also uses an average electricity cost to estimate daily savings. These assumptions can be adjusted for more precise calculations.
          </p>
          <p>
            Understanding your system's payback period helps you make informed decisions about investing in renewable energy, balancing upfront costs with long-term savings and environmental benefits.
          </p>
          <p>
            For accurate results, ensure your inputs reflect your actual consumption, battery specifications, and local solar conditions. Consult with a professional for detailed system design and financial analysis.
          </p>
        </div>
      </section>

      <section
        id="mistakes"
        className="bg-amber-50 dark:bg-amber-950/30 p-6 rounded-xl border border-amber-200 dark:border-amber-900"
      >
        <h3 className="font-bold text-lg mb-3 flex items-center gap-2 text-amber-900 dark:text-amber-100">
          <AlertTriangle className="w-5 h-5" /> Safety & Common Mistakes
        </h3>
        <div className="space-y-2 text-sm text-amber-900 dark:text-amber-100">
          <p>
            <strong>Warning:</strong> Electricity and renewable energy systems involve risks including electric shock, fire hazards, and equipment damage. Always follow National Electrical Code (NEC) guidelines and local regulations.
          </p>
          <p>
            Common mistakes include underestimating energy consumption, oversizing or undersizing battery banks, and ignoring local solar resource variability. These errors can lead to inefficient systems, increased costs, or system failure.
          </p>
          <p>
            Ensure proper system design by consulting with qualified engineers or electricians. Use this calculator as a preliminary tool, not a substitute for professional advice.
          </p>
          <p>
            Regular maintenance and monitoring are essential to ensure system safety and longevity.
          </p>
        </div>
      </section>

      <section id="example" className="scroll-mt-24">
        <h2 className="text-2xl font-bold mb-4 text-slate-900 dark:text-slate-100">Real World Example</h2>
        <p className="mb-4">{example.scenario}</p>
        <ol className="list-decimal pl-5 space-y-3 text-slate-600 dark:text-slate-400">
          {example.steps.map((step, i) => (
            <li key={i}>
              <strong>{step.label}:</strong> {step.explanation}
            </li>
          ))}
        </ol>
        <p className="mt-4 font-semibold">{example.result}</p>
      </section>

      <section id="faq">
        <h2 className="text-2xl font-bold mb-6 text-slate-900 dark:text-slate-100">Frequently asked questions</h2>
        <div className="space-y-6">
          {faqs.map((faq, i) => (
            <div key={i} className="border-b border-slate-200 dark:border-slate-800 pb-5 last:border-0">
              <h3 className="font-semibold text-lg text-slate-900 dark:text-slate-100 mb-2">{faq.question}</h3>
              <p className="text-slate-600 dark:text-slate-400 leading-relaxed">{faq.answer}</p>
            </div>
          ))}
        </div>
      </section>

      <section id="references">
        <h2 className="text-2xl font-bold mb-4 flex items-center gap-2 text-slate-900 dark:text-slate-100">
          <BookOpen className="w-5 h-5 text-blue-500" /> References & additional resources
        </h2>
        <div className="space-y-4">
          {references.map((ref, i) => (
            <div key={i}>
              <a
                href={ref.url}
                target="_blank"
                rel="noopener noreferrer"
                className="text-blue-600 dark:text-blue-400 font-semibold hover:underline flex items-center gap-1"
              >
                {ref.title} <ExternalLink className="w-3 h-3" />
              </a>
              <p className="text-sm text-slate-600 dark:text-slate-400 mt-1">{ref.description}</p>
            </div>
          ))}
        </div>
      </section>
    </div>
  );

  return (
    <CalculatorVerticalLayout
      title="System Payback Period (ROI) Calculator"
      description="Professional electrical calculator: System Payback Period (ROI) Calculator. Accurate engineering formulas, NEC compliance tips, and safety guidelines."
      widget={widget}
      editorial={editorial}
      jsonLd={faqJsonLd}
      example={example}
      relatedCalculators={[]}
      onThisPage={[
        { id: "how-to-use", label: "How to Use" },
        { id: "guide", label: "Complete Guide" },
        { id: "mistakes", label: "Safety & Mistakes" },
        { id: "example", label: "Real World Example" },
        { id: "faq", label: "Frequently Asked Questions" },
        { id: "references", label: "References" },
      ]}
      showTopBanner
      showSidebar
      showBottomBanner
    />
  );
}