// AUTO-GENERATED by scripts/split-registry.cjs — DO NOT EDIT BY HAND.
// Per-category slice of the master CalculatorEntry registry.
// Re-run `node scripts/split-registry.cjs` after editing the master.

import type { CalculatorEntry } from "@/data/calculatorRegistry";

export const constructionEntries: CalculatorEntry[] = [
  {
      slug: "drywall-area-sheets",
      title: "Drywall Area & Sheets Calculator",
      category: "construction",
      subcategory: "interior-surfaces-finishes",
      description: "Calculate number of drywall sheets for walls/ceilings.",
      loader: () => import("@/components/calculators/Construction/DrywallAreaSheetsCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "concrete-slab-volume",
      title: "Concrete Slab Volume Calculator",
      category: "construction",
      subcategory: "concrete-masonry-foundations",
      description: "Calculate the exact volume of concrete needed for slabs, patios, or driveways. Avoid over-ordering and minimize material waste.",
      loader: () => import("@/components/calculators/Construction/ConcreteSlabVolumeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "concrete-footing-foundation",
      title: "Concrete Footing & Foundation Calculator",
      category: "construction",
      subcategory: "concrete-masonry-foundations",
      description: "Estimate concrete volume for footings and foundations. Calculate the amount of rebar needed for structural reinforcement.",
      loader: () => import("@/components/calculators/Construction/ConcreteFootingFoundationCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "concrete-block-cmu-wall",
      title: "Concrete Block (CMU) Wall Calculator",
      category: "construction",
      subcategory: "concrete-masonry-foundations",
      description: "Determine the perfect concrete mix ratio (cement, sand, gravel). Essential for strong, durable, and professional-grade DIY concrete projects.",
      loader: () => import("@/components/calculators/Construction/ConcreteBlockCmuWallCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "rebar-spacing-quantity",
      title: "Rebar Spacing & Quantity Calculator",
      category: "construction",
      subcategory: "concrete-masonry-foundations",
      description: "Calculate the concrete volume required to fill fence post or deck support holes based on depth and diameter.",
      loader: () => import("@/components/calculators/Construction/RebarSpacingQuantityCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "mortar-mix-ratio-bag",
      title: "Mortar Mix Ratio & Bag Calculator",
      category: "construction",
      subcategory: "concrete-masonry-foundations",
      description: "Estimate the concrete curing time. Determine how long your slab needs to set before it can be walked on or support heavy loads.",
      loader: () => import("@/components/calculators/Construction/MortarMixRatioBagCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cement-sand-aggregate-ratio",
      title: "Cement, Sand & Aggregate Ratio Calculator",
      category: "construction",
      subcategory: "concrete-masonry-foundations",
      description: "Calculate the number of concrete masonry units (CMU) or cinder blocks needed for walls and structures.",
      loader: () => import("@/components/calculators/Construction/CementSandAggregateRatioCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "concrete-weight-yield",
      title: "Concrete Weight & Yield Calculator",
      category: "construction",
      subcategory: "concrete-masonry-foundations",
      description: "Estimate the volume of mortar required for laying concrete block walls. Minimize waste and ensure enough material is on hand.",
      loader: () => import("@/components/calculators/Construction/ConcreteWeightYieldCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "concrete-curing-time",
      title: "Concrete Curing Time Estimator",
      category: "construction",
      subcategory: "concrete-masonry-foundations",
      description: "Concrete Curing Time Estimator Estimate the time required for concrete to reach its full strength. Factors in ambient temperature, mix type, and curing methods to ensure durability and safety before removing forms or applying loads.",
      loader: () => import("@/components/calculators/Construction/ConcreteCuringTimeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "brick-calculator",
      title: "Brick Calculator",
      category: "construction",
      subcategory: "concrete-masonry-foundations",
      description: "Brick Calculator Calculate the number of bricks and amount of mortar needed for your wall project. Enter wall dimensions and brick size to get precise material estimates and minimize waste.",
      loader: () => import("@/components/calculators/Construction/BrickCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "retaining-wall-calculator",
      title: "Retaining Wall Calculator",
      category: "construction",
      subcategory: "concrete-masonry-foundations",
      description: "Retaining Wall Calculator Plan your retaining wall project with precision. Calculate the number of retaining blocks, gravel backing, and drainage materials needed to build a stable and long-lasting structure.",
      loader: () => import("@/components/calculators/Construction/RetainingWallCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "deck-board-joist-spacing",
      title: "Deck Board & Joist Spacing Calculator",
      category: "construction",
      subcategory: "lumber-decking-fencing",
      description: "Calculate deck board quantity and joist spacing.",
      loader: () => import("@/components/calculators/Construction/DeckBoardJoistSpacingCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "stair-tread-riser-dimensions",
      title: "Stair Tread & Riser Dimensions Calculator",
      category: "construction",
      subcategory: "lumber-decking-fencing",
      description: "Calculate riser height, tread depth, and stringer length.",
      loader: () => import("@/components/calculators/Construction/StairTreadRiserDimensionsCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "trim-baseboard-length-estimator",
      title: "Trim & Baseboard Length Estimator",
      category: "construction",
      subcategory: "lumber-decking-fencing",
      description: "Estimate total linear feet of trim or baseboard needed.",
      loader: () => import("@/components/calculators/Construction/TrimBaseboardLengthEstimatorCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "hardwood-plank-quantity",
      title: "Hardwood Plank Quantity Calculator",
      category: "construction",
      subcategory: "lumber-decking-fencing",
      description: "Calculate number of hardwood planks for flooring.",
      loader: () => import("@/components/calculators/Construction/HardwoodPlankQuantityCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "laminate-flooring-waste-allowance",
      title: "Laminate Flooring Waste Allowance Calculator",
      category: "construction",
      subcategory: "lumber-decking-fencing",
      description: "Estimate extra laminate flooring needed for cuts/waste.",
      loader: () => import("@/components/calculators/Construction/LaminateFlooringWasteAllowanceCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "carpet-roll-waste",
      title: "Carpet Roll & Waste Calculator",
      category: "construction",
      subcategory: "lumber-decking-fencing",
      description: "Calculate carpet rolls required including installation waste.",
      loader: () => import("@/components/calculators/Construction/CarpetRollWasteCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "board-foot",
      title: "Board Foot Calculator",
      category: "construction",
      subcategory: "lumber-decking-fencing",
      description: "Calculate lumber volume in board feet for pricing.",
      loader: () => import("@/components/calculators/Construction/BoardFootCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "fence-post-material-linear-feet",
      title: "Fence Post & Material Calculator",
      category: "construction",
      subcategory: "lumber-decking-fencing",
      description: "Estimate posts, rails, and pickets for fencing.",
      loader: () => import("@/components/calculators/Construction/FencePostMaterialLinearFeetCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "tile-area-grout",
      title: "Tile Area & Grout Calculator",
      category: "construction",
      subcategory: "lumber-decking-fencing",
      description: "Calculate tiles and grout needed for floor/wall areas.",
      loader: () => import("@/components/calculators/Construction/TileAreaGroutCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "flooring-material-cost",
      title: "Flooring Material Cost Estimator",
      category: "construction",
      subcategory: "lumber-decking-fencing",
      description: "Estimate total cost of flooring materials.",
      loader: () => import("@/components/calculators/Construction/FlooringMaterialCostCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "baluster-spacing-calculator",
      title: "Baluster Spacing Calculator",
      category: "construction",
      subcategory: "lumber-decking-fencing",
      description: "Calculate even spacing for railing balusters/spindles.",
      loader: () => import("@/components/calculators/Construction/BalusterSpacingCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "paint-coverage-gallons",
      title: "Paint Coverage & Gallons Needed Calculator",
      category: "construction",
      subcategory: "interior-surfaces-finishes",
      description: "Estimate gallons of paint required for room coverage.",
      loader: () => import("@/components/calculators/Construction/PaintCoverageGallonsCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "wallpaper-roll-coverage",
      title: "Wallpaper Roll Coverage Calculator",
      category: "construction",
      subcategory: "interior-surfaces-finishes",
      description: "Calculate number of wallpaper rolls needed for a room.",
      loader: () => import("@/components/calculators/Construction/WallpaperRollCoverageCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "ceiling-tile-quantity",
      title: "Ceiling Tile Quantity Calculator",
      category: "construction",
      subcategory: "interior-surfaces-finishes",
      description: "Estimate tiles needed for drop ceilings.",
      loader: () => import("@/components/calculators/Construction/CeilingTileQuantityCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "plaster-volume-bag",
      title: "Plaster Volume & Bag Estimator",
      category: "construction",
      subcategory: "interior-surfaces-finishes",
      description: "Calculate plaster volume and bags for wall repairs.",
      loader: () => import("@/components/calculators/Construction/PlasterVolumeBagCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "acoustic-panel-area",
      title: "Acoustic Panel Area Planner",
      category: "construction",
      subcategory: "interior-surfaces-finishes",
      description: "Calculate acoustic panel coverage for soundproofing.",
      loader: () => import("@/components/calculators/Construction/AcousticPanelAreaCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "joint-compound-amount",
      title: "Joint Compound Amount Calculator",
      category: "construction",
      subcategory: "interior-surfaces-finishes",
      description: "Estimate joint compound needed for drywall finishing.",
      loader: () => import("@/components/calculators/Construction/JointCompoundAmountCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "plywood-calculator",
      title: "Plywood Calculator",
      category: "construction",
      subcategory: "interior-surfaces-finishes",
      description: "Calculate number of plywood sheets for subfloors/sheathing.",
      loader: () => import("@/components/calculators/Construction/PlywoodCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "roof-pitch-slope-angle",
      title: "Roof Pitch & Slope Angle Calculator",
      category: "construction",
      subcategory: "roofing-siding-site-prep",
      description: "Calculate roof pitch, slope angle, and rafter length.",
      loader: () => import("@/components/calculators/Construction/RoofPitchSlopeAngleCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "roof-shingle-bundle",
      title: "Roof Shingle & Bundle Calculator",
      category: "construction",
      subcategory: "roofing-siding-site-prep",
      description: "Estimate bundles of shingles for roof coverage.",
      loader: () => import("@/components/calculators/Construction/RoofShingleBundleCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "metal-roof-panel-coverage",
      title: "Metal Roofing Panel Coverage Calculator",
      category: "construction",
      subcategory: "roofing-siding-site-prep",
      description: "Calculate metal panels needed for roofing projects.",
      loader: () => import("@/components/calculators/Construction/MetalRoofPanelCoverageCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "roof-underlayment-roll",
      title: "Roof Underlayment Roll Estimator",
      category: "construction",
      subcategory: "roofing-siding-site-prep",
      description: "Estimate rolls of underlayment for roof protection.",
      loader: () => import("@/components/calculators/Construction/RoofUnderlaymentRollCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "siding-panel-coverage",
      title: "Siding Panel Coverage Calculator",
      category: "construction",
      subcategory: "roofing-siding-site-prep",
      description: "Calculate siding panels required for exterior walls.",
      loader: () => import("@/components/calculators/Construction/SidingPanelCoverageCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "gutter-size",
      title: "Roof Drainage (Gutter Size) Calculator",
      category: "construction",
      subcategory: "roofing-siding-site-prep",
      description: "Determine appropriate gutter size based on roof area.",
      loader: () => import("@/components/calculators/Construction/GutterSizeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "hip-roof-calculator",
      title: "Hip Roof Calculator",
      category: "construction",
      subcategory: "roofing-siding-site-prep",
      description: "Calculate area and materials for hip roof designs.",
      loader: () => import("@/components/calculators/Construction/HipRoofCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "gable-roof-calculator",
      title: "Gable Roof Calculator",
      category: "construction",
      subcategory: "roofing-siding-site-prep",
      description: "Calculate area and materials for gable roof designs.",
      loader: () => import("@/components/calculators/Construction/GableRoofCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "excavation-calculator",
      title: "Excavation Calculator",
      category: "construction",
      subcategory: "roofing-siding-site-prep",
      description: "Estimate soil volume to be removed for excavation.",
      loader: () => import("@/components/calculators/Construction/ExcavationCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "insulation-r-value-requirement",
      title: "Insulation R-Value Requirement Calculator",
      category: "construction",
      subcategory: "insulation-hvac-energy",
      description: "Determine recommended insulation R-values by zone.",
      loader: () => import("@/components/calculators/Construction/InsulationRValueRequirementCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "hvac-btu-requirement",
      title: "HVAC BTU Requirement Calculator",
      category: "construction",
      subcategory: "insulation-hvac-energy",
      description: "Calculate BTU output needed for heating/cooling.",
      loader: () => import("@/components/calculators/Construction/HvacBtuRequirementCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "duct-size-airflow",
      title: "Duct Size & Airflow Calculator",
      category: "construction",
      subcategory: "insulation-hvac-energy",
      description: "Estimate duct size for efficient airflow.",
      loader: () => import("@/components/calculators/Construction/DuctSizeAirflowCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "heating-cost-per-square-foot",
      title: "Heating Cost per Square Foot Estimator",
      category: "construction",
      subcategory: "insulation-hvac-energy",
      description: "Estimate heating costs based on area and fuel type.",
      loader: () => import("@/components/calculators/Construction/HeatingCostPerSquareFootCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "energy-efficiency-savings",
      title: "Energy Efficiency Savings Estimator",
      category: "construction",
      subcategory: "insulation-hvac-energy",
      description: "Calculate potential savings from energy upgrades.",
      loader: () => import("@/components/calculators/Construction/EnergyEfficiencySavingsCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cfm-calculator",
      title: "CFM Calculator",
      category: "construction",
      subcategory: "insulation-hvac-energy",
      description: "Calculate Cubic Feet per Minute (CFM) for ventilation.",
      loader: () => import("@/components/calculators/Construction/CfmCalculator"),
      urlStyle: "flat"
    }
];
