// AUTO-GENERATED by scripts/split-registry.cjs — DO NOT EDIT BY HAND.
// Per-category slice of the master CalculatorEntry registry.
// Re-run `node scripts/split-registry.cjs` after editing the master.

import type { CalculatorEntry } from "@/data/calculatorRegistry";

export const everydayEntries: CalculatorEntry[] = [
  {
      slug: "qr-code-generator",
      title: "Free QR Code Generator",
      category: "everyday",
      subcategory: "general",
      description: "Generate free QR codes for URLs, text, and contacts (vCard). Download PNG or SVG, choose error‑correction (ECC), margins, size and brand colors.",
      loader: () => import("@/components/calculators/EverydayLife/QrCodeGeneratorCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "word-counter",
      title: "Word Counter Utility",
      category: "everyday",
      subcategory: "general",
      description: "A fast, minimal, and clean tool to count words, characters, sentences, and paragraphs in real-time. Optimize your content for SEO and readability effortlessly.",
      loader: () => import("@/components/calculators/EverydayLife/WordCounterCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "qr-code-generator",
      title: "QR Code Generator",
      category: "everyday",
      subcategory: "utilities",
      description: "Gere QR Codes gratuitos para URLs e textos. Baixe em PNG ou SVG com tamanho, margem e correção de erro configuráveis.",
      loader: () => import("@/components/calculators/EverydayLife/QrCodeGeneratorCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cleaning-dilution-ratio",
      title: "Cleaning Dilution Ratio Calculator",
      category: "everyday",
      subcategory: "home-maintenance",
      description: "Calculate the perfect cleaning dilution ratio. Mix chemicals and water safely and effectively for household cleaning tasks.",
      loader: () => import("@/components/calculators/Misc/CleaningDilutionRatioCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "laundry-detergent-dosage",
      title: "Laundry Detergent Dosage by Load Size",
      category: "everyday",
      subcategory: "home-maintenance",
      description: "Determine the right laundry detergent dosage. Calculate the exact amount needed per load size to save money and protect clothes.",
      loader: () => import("@/components/calculators/Misc/LaundryDetergentDosageCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "home-paint-touch-up",
      title: "Home Paint Touch-Up Estimator",
      category: "everyday",
      subcategory: "home-maintenance",
      description: "Estimate paint needed for touch-ups. Calculate exactly how much paint covers scratches and small repairs on walls and trim.",
      loader: () => import("@/components/calculators/Misc/HomePaintTouchUpCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "room-air-changes-ach",
      title: "Room Air Changes per Hour (ACH) Calculator",
      category: "everyday",
      subcategory: "home-maintenance",
      description: "Calculate Air Changes per Hour (ACH). Measure ventilation efficiency and air quality turnover rates for any room size.",
      loader: () => import("@/components/calculators/Misc/RoomAirChangesAchCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "propane-tank-burn-time",
      title: "Propane Tank Burn Time Estimator",
      category: "everyday",
      subcategory: "home-maintenance",
      description: "Estimate propane tank burn time. Calculate how long your grill, heater, or generator will run based on tank size and BTU usage.",
      loader: () => import("@/components/calculators/Misc/PropaneTankBurnTimeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "refrigerator-freezer-safe-zone-time-window",
      title: "Refrigerator/Freezer Safe Zone Time Window",
      category: "everyday",
      subcategory: "home-maintenance",
      description: "Track food safety during power outages. Estimate how long food stays safe in your refrigerator or freezer without power.",
      loader: () => import("@/components/calculators/Misc/RefrigeratorFreezerSafeZoneTimeWindowCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "light-bulb-cost-per-year",
      title: "Light Bulb Cost per Year Calculator",
      category: "everyday",
      subcategory: "home-maintenance",
      description: "Calculate electricity costs for light bulbs. Compare LED vs. incandescent usage to see how much you save on your energy bill.",
      loader: () => import("@/components/calculators/Misc/LightBulbCostPerYearCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "water-heater-recovery-time",
      title: "Water Heater Recovery Time Estimator",
      category: "everyday",
      subcategory: "home-maintenance",
      description: "Estimate water heater recovery time. Calculate how long it takes for your tank to provide hot water again after depletion.",
      loader: () => import("@/components/calculators/Misc/WaterHeaterRecoveryTimeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "home-renovation-cost-estimator",
      title: "Home Renovation Cost Estimator",
      category: "everyday",
      subcategory: "home-maintenance",
      description: "Estimate home renovation costs. Create a budget for your remodeling project by calculating material and labor expenses.",
      loader: () => import("@/components/calculators/Misc/HomeRenovationCostEstimatorCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "appliance-energy-consumption",
      title: "Appliance Energy Consumption Calculator",
      category: "everyday",
      subcategory: "home-maintenance",
      description: "Calculate appliance energy consumption. Track how much electricity your fridge, TV, and washer use to manage your utility bill.",
      loader: () => import("@/components/calculators/Misc/ApplianceEnergyConsumptionCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "life-expectancy",
      title: "Life Expectancy Calculator",
      category: "everyday",
      subcategory: "health-wellness-sleep",
      description: "Estimate your life expectancy. Analyze lifestyle factors like diet and exercise to see statistical projections for longevity.",
      loader: () => import("@/components/calculators/Misc/LifeExpectancyCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "bmi-calculator",
      title: "Body Mass Index (BMI) Calculator",
      category: "everyday",
      subcategory: "health-wellness-sleep",
      description: "Calculate Body Mass Index (BMI) quickly. A simple everyday tool to check if your weight falls within a healthy range.",
      loader: () => import("@/components/calculators/Misc/BmiCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "sleep-debt-ideal-bedtime",
      title: "Sleep Debt & Ideal Bedtime Planner",
      category: "everyday",
      subcategory: "health-wellness-sleep",
      description: "Calculate your sleep debt and recovery plan. Find out how much sleep you owe your body and determine your ideal bedtime.",
      loader: () => import("@/components/calculators/Misc/SleepDebtIdealBedtimeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "caffeine-max-per-day",
      title: "Caffeine Max per Day Calculator",
      category: "everyday",
      subcategory: "health-wellness-sleep",
      description: "Monitor your caffeine intake. Calculate your daily limit based on body weight to enjoy coffee safely without the jitters.",
      seoTitle: "Daily Caffeine Limit Calculator — Safe Dose by Body Weight",
      seoDescription: "Find your safe daily caffeine limit based on body weight. Track coffee, tea, energy drinks, and supplements to avoid jitters, anxiety, and sleep disruption.",
      loader: () => import("@/components/calculators/Misc/CaffeineMaxPerDayCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "screen-time-pomodoro-planner",
      title: "Screen Time Budget / Pomodoro Planner",
      category: "everyday",
      subcategory: "health-wellness-sleep",
      description: "Manage digital wellness with a screen time budget. Plan productive work intervals using the Pomodoro technique.",
      loader: () => import("@/components/calculators/Misc/ScreenTimePomodoroPlannerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "steps-to-distance-converter",
      title: "Steps → Distance Converter",
      category: "everyday",
      subcategory: "health-wellness-sleep",
      description: "Convert daily steps to distance. See how many miles or kilometers you walked based on your step count and stride length.",
      loader: () => import("@/components/calculators/Misc/StepsToDistanceConverterCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "hydration-reminder-interval",
      title: "Hydration Reminder Interval Planner",
      category: "everyday",
      subcategory: "health-wellness-sleep",
      description: "Set up a hydration schedule. Calculate the best intervals to drink water throughout the day to meet your daily intake goals.",
      loader: () => import("@/components/calculators/Misc/HydrationReminderIntervalCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "myplate-daily-calorie-nutrient",
      title: "MyPlate Daily Calorie/Nutrient Planner",
      category: "everyday",
      subcategory: "health-wellness-sleep",
      description: "Plan balanced meals with MyPlate guidelines. Calculate daily calorie and nutrient portions for a healthy lifestyle.",
      loader: () => import("@/components/calculators/Misc/MyplateDailyCalorieNutrientCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "bmr-calculator",
      title: "Basal Metabolic Rate (BMR) Calculator",
      category: "everyday",
      subcategory: "health-wellness-sleep",
      description: "Calculate everyday BMR. Find out the minimum calories your body needs to function before adding any physical activity.",
      loader: () => import("@/components/calculators/Misc/BmrCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "party-food-drinks-planner",
      title: "Party Food & Drinks Planner",
      category: "everyday",
      subcategory: "events-party-culinary",
      description: "Plan party food and drink quantities. Calculate exactly how many servings, pizzas, and beverages you need for your guest list.",
      loader: () => import("@/components/calculators/Misc/PartyFoodDrinksPlannerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "ice-quantity-beverages",
      title: "Ice Quantity for Beverages Calculator",
      category: "everyday",
      subcategory: "events-party-culinary",
      description: "Calculate ice needed for parties. Estimate bags of ice required for drinks and cooling based on guest count and duration.",
      loader: () => import("@/components/calculators/Misc/IceQuantityBeveragesCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "buffet-pan-capacity-count",
      title: "Buffet Serving Pan Capacity & Count",
      category: "everyday",
      subcategory: "events-party-culinary",
      description: "Plan buffet quantities. Calculate how much food fits in standard hotel pans to ensure you feed everyone without running out.",
      loader: () => import("@/components/calculators/Misc/BuffetPanCapacityCountCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "beverage-mix-estimator",
      title: "Wine/Beer/Soft Drink Mix Estimator",
      category: "everyday",
      subcategory: "events-party-culinary",
      description: "Estimate the beverage mix for events. Calculate the ratio of wine, beer, and soft drinks needed based on guest preferences.",
      loader: () => import("@/components/calculators/Misc/BeverageMixEstimatorCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "coffee-urn-yield-strength",
      title: "Coffee Urn Yield & Strength Calculator",
      category: "everyday",
      subcategory: "events-party-culinary",
      description: "Brew coffee for a crowd. Calculate the coffee grounds-to-water ratio for large urns to ensure the perfect strength.",
      loader: () => import("@/components/calculators/Misc/CoffeeUrnYieldStrengthCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "leftovers-cooling-reheat-time",
      title: "Leftovers Cooling & Reheat Time",
      category: "everyday",
      subcategory: "events-party-culinary",
      description: "Handle leftovers safely. Estimate cooling times and safe reheating duration to prevent food spoilage after big meals.",
      loader: () => import("@/components/calculators/Misc/LeftoversCoolingReheatTimeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "event-budget-calculator",
      title: "Event Budget Calculator",
      category: "everyday",
      subcategory: "events-party-culinary",
      description: "Create a comprehensive event budget. Track expenses for venue, food, and entertainment to keep your party planning on track.",
      loader: () => import("@/components/calculators/Misc/EventBudgetCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "event-capacity-calculator",
      title: "Event Capacity Calculator",
      category: "everyday",
      subcategory: "events-party-culinary",
      description: "Calculate venue capacity. Determine how many guests can safely fit in a room based on square footage and seating layout.",
      seoTitle: "Event Capacity Calculator — Max Guests by Room Size & Layout",
      seoDescription: "Calculate safe event capacity from room square footage. Get instant guest counts for standing, seated, cocktail, banquet, and classroom layouts. Fire code and ADA guidance included.",
      loader: () => import("@/components/calculators/Misc/EventCapacityCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "mulch-coverage-bag-count",
      title: "Mulch Coverage & Bag Count Calculator",
      category: "everyday",
      subcategory: "garden-exterior",
      description: "Calculate mulch coverage and bags needed. Determine the cubic yards or bags of mulch required for your garden beds.",
      loader: () => import("@/components/calculators/Misc/MulchCoverageBagCountCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "garden-soil-compost-volume",
      title: "Garden Soil/Compost Volume Calculator",
      category: "everyday",
      subcategory: "garden-exterior",
      description: "Calculate soil volume for raised beds. Find out exactly how much topsoil or compost you need to fill your garden planters.",
      loader: () => import("@/components/calculators/Misc/GardenSoilCompostVolumeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "lawn-mowing-time-fuel",
      title: "Lawn Mowing Time & Fuel Planner",
      category: "everyday",
      subcategory: "garden-exterior",
      description: "Estimate lawn mowing time. Calculate how long it takes to mow your yard and the fuel required based on mower size.",
      loader: () => import("@/components/calculators/Misc/LawnMowingTimeFuelCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "hose-runtime-flow-rate",
      title: "Hose Runtime vs Flow Rate Calculator",
      category: "everyday",
      subcategory: "garden-exterior",
      description: "Calculate hose runtime for watering. Determine how long to run your sprinkler to deliver a specific amount of water.",
      loader: () => import("@/components/calculators/Misc/HoseRuntimeFlowRateCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "rainwater-barrel-days-supply",
      title: "Rainwater Barrel Days of Supply",
      category: "everyday",
      subcategory: "garden-exterior",
      description: "Estimate rainwater supply duration. Calculate how long your rain barrel will last during dry spells based on garden usage.",
      loader: () => import("@/components/calculators/Misc/RainwaterBarrelDaysSupplyCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "grass-seed-quantity",
      title: "Grass Seed Quantity Calculator",
      category: "everyday",
      subcategory: "garden-exterior",
      description: "Calculate grass seed needed. Determine the pounds of seed required to overseed or plant a new lawn based on area.",
      loader: () => import("@/components/calculators/Misc/GrassSeedQuantityCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "square-footage-calculator",
      title: "Square Footage Calculator",
      category: "everyday",
      subcategory: "garden-exterior",
      description: "Calculate square footage for lawns and gardens. Measure the total area of your outdoor space for landscaping projects.",
      loader: () => import("@/components/calculators/Misc/SquareFootageCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "planting-calendar-frost-date",
      title: "Planting Calendar & Frost Date Finder",
      category: "everyday",
      subcategory: "garden-exterior",
      description: "Find your planting dates. Determine the best time to sow seeds based on local frost dates and your hardiness zone.",
      loader: () => import("@/components/calculators/Misc/PlantingCalendarFrostDateCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "plant-spacing-calculator",
      title: "Plant Spacing Calculator",
      category: "everyday",
      subcategory: "garden-exterior",
      description: "Optimize your garden layout. Calculate the ideal spacing between plants to maximize yield and prevent overcrowding.",
      loader: () => import("@/components/calculators/Misc/PlantSpacingCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "fertilizer-application-calculator",
      title: "Fertilizer Application Calculator",
      category: "everyday",
      subcategory: "garden-exterior",
      description: "Calculate fertilizer application rates. Determine the correct amount of nitrogen, phosphorus, and potassium for your lawn area.",
      loader: () => import("@/components/calculators/Misc/FertilizerApplicationCalculator"),
      urlStyle: "flat"
    }
];
