// AUTO-GENERATED by scripts/split-registry.cjs — DO NOT EDIT BY HAND.
// Per-category slice of the master CalculatorEntry registry.
// Re-run `node scripts/split-registry.cjs` after editing the master.

import type { CalculatorEntry } from "@/data/calculatorRegistry";

export const videoEntries: CalculatorEntry[] = [
  {
      slug: "video-bitrate-file-size",
      title: "Video Bitrate ↔ File Size Calculator",
      category: "video",
      subcategory: "bitrate-file-size-storage",
      description: "Calculate video file size from bitrate, duration, and codec or vice versa.",
      loader: () => import("@/components/calculators/Video/VideoBitrateFileSizeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "recording-time-card-ssd-capacity",
      title: "Recording Time vs Card/SSD Capacity",
      category: "video",
      subcategory: "bitrate-file-size-storage",
      description: "Estimate maximum recording time based on storage capacity and bitrate.",
      loader: () => import("@/components/calculators/Video/RecordingTimeCardSsdCapacityCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "audio-bitrate-channels-impact-file-size",
      title: "Audio Bitrate + Channels Impact (File Size)",
      category: "video",
      subcategory: "bitrate-file-size-storage",
      description: "Calculate how audio bitrate and number of channels affect total file size.",
      loader: () => import("@/components/calculators/Video/AudioBitrateChannelsImpactFileSizeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "vbr-cbr-size-estimator",
      title: "VBR vs CBR Size Estimator",
      category: "video",
      subcategory: "bitrate-file-size-storage",
      description: "Compare file size differences between Variable Bitrate (VBR) and Constant Bitrate (CBR).",
      loader: () => import("@/components/calculators/Video/VbrCbrSizeEstimatorCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "uncompressed-video-size-resolution-bit-depth",
      title: "Uncompressed Video Size (Resolution × Bit Depth)",
      category: "video",
      subcategory: "bitrate-file-size-storage",
      description: "Calculate raw uncompressed video file size based on resolution, bit depth, and FPS.",
      loader: () => import("@/components/calculators/Video/UncompressedVideoSizeResolutionBitDepthCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "h264-h265-target-bitrate-helper-resolution-fps",
      title: "H.264/H.265 Target Bitrate Helper (by resolution/FPS)",
      category: "video",
      subcategory: "bitrate-file-size-storage",
      description: "Recommended target bitrates for H.264 and H.265 by resolution and frame rate.",
      loader: () => import("@/components/calculators/Video/H264H265TargetBitrateHelperResolutionFpsCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "youtube-twitch-recommended-bitrate-checker",
      title: "YouTube/Twitch Recommended Bitrate (Upload/Stream) Checker",
      category: "video",
      subcategory: "bitrate-file-size-storage",
      description: "Check platform-recommended bitrates for streaming and upload quality.",
      loader: () => import("@/components/calculators/Video/YoutubeTwitchRecommendedBitrateCheckerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "surveillance-nvr-video-storage-planner",
      title: "Surveillance/NVR Video Storage Planner",
      category: "video",
      subcategory: "bitrate-file-size-storage",
      description: "Plan storage needs for surveillance systems with multiple cameras.",
      loader: () => import("@/components/calculators/Video/SurveillanceNvrVideoStoragePlannerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "live-streaming-bitrate-calculator",
      title: "Live Streaming Bitrate Calculator",
      category: "video",
      subcategory: "bitrate-file-size-storage",
      description: "Determine optimal bitrate for live streaming based on resolution and bandwidth.",
      loader: () => import("@/components/calculators/Video/LiveStreamingBitrateCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "video-data-rate-calculator",
      title: "Video Data Rate Calculator (Mbps ↔ MB/s)",
      category: "video",
      subcategory: "bitrate-file-size-storage",
      description: "Convert between Mbps (megabits per second) and MB/s (megabytes per second).",
      loader: () => import("@/components/calculators/Video/VideoDataRateCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "video-compression-size-estimator",
      title: "Video Compression Size Estimator (H.264/etc.)",
      category: "video",
      subcategory: "bitrate-file-size-storage",
      description: "Estimate compressed file size for different codecs and quality settings.",
      loader: () => import("@/components/calculators/Video/VideoCompressionSizeEstimatorCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "camera-bitrate-record-time-converter",
      title: "Camera Bitrate to Record Time Converter",
      category: "video",
      subcategory: "bitrate-file-size-storage",
      description: "Convert camera bitrate settings to available recording time on storage media.",
      loader: () => import("@/components/calculators/Video/CameraBitrateRecordTimeConverterCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "aspect-ratio-letterbox-pillarbox",
      title: "Aspect Ratio Calculator (Letterbox/Pillarbox)",
      category: "video",
      subcategory: "resolution-aspect-ratio-pixels",
      description: "Calculate letterbox/pillarbox dimensions when changing aspect ratios.",
      loader: () => import("@/components/calculators/Video/AspectRatioLetterboxPillarboxCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "resolution-presets-pixel-count-720p-1080p-4k-8k",
      title: "Resolution Presets & Pixel Count (720p/1080p/4K/8K)",
      category: "video",
      subcategory: "resolution-aspect-ratio-pixels",
      description: "View standard resolution presets and total pixel counts (e.g., 1080p, 4K, 8K).",
      loader: () => import("@/components/calculators/Video/ResolutionPresetsPixelCount720p1080p4k8kCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "screen-size-from-diagonal-ar",
      title: "Screen Size from Diagonal & AR",
      category: "video",
      subcategory: "resolution-aspect-ratio-pixels",
      description: "Calculate physical width and height from diagonal screen size and aspect ratio.",
      loader: () => import("@/components/calculators/Video/ScreenSizeFromDiagonalArCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "tv-size-viewing-distance-planner",
      title: "TV Size & Viewing Distance Planner",
      category: "video",
      subcategory: "resolution-aspect-ratio-pixels",
      description: "Recommend optimal viewing distance based on TV size and resolution.",
      loader: () => import("@/components/calculators/Video/TvSizeViewingDistancePlannerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "pixel-aspect-ratio-par-converter",
      title: "Pixel Aspect Ratio (PAR) Converter",
      category: "video",
      subcategory: "resolution-aspect-ratio-pixels",
      description: "Handle non-square pixel aspect ratios in video formats.",
      loader: () => import("@/components/calculators/Video/PixelAspectRatioParConverterCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "anamorphic-lens-calculator",
      title: "Anamorphic Lens Calculator",
      category: "video",
      subcategory: "resolution-aspect-ratio-pixels",
      description: "Calculate squeeze factors and final aspect ratio with anamorphic lenses.",
      loader: () => import("@/components/calculators/Video/AnamorphicLensCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "video-crop-dimension-calculator",
      title: "Video Crop Dimension Calculator",
      category: "video",
      subcategory: "resolution-aspect-ratio-pixels",
      description: "Determine output dimensions after cropping video to specific ratios or sizes.",
      loader: () => import("@/components/calculators/Video/VideoCropDimensionCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "timecode-duration-hh-mm-ss-ff-converter",
      title: "Timecode ↔ Duration (HH:MM:SS:FF) Converter",
      category: "video",
      subcategory: "time-fps-timecode",
      description: "Convert between timecode and total duration in seconds or frames.",
      loader: () => import("@/components/calculators/Video/TimecodeDurationHhMmSsFfConverterCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "fps-converter-23-976-24-25-29-97-30-50-59-94",
      title: "FPS Converter (23.976↔24↔25↔29.97↔30↔50↔59.94)",
      category: "video",
      subcategory: "time-fps-timecode",
      description: "Convert footage between common frame rates with pulldown options.",
      loader: () => import("@/components/calculators/Video/FpsConverter239762425299730505994Calculator"),
      urlStyle: "flat"
    },
  {
      slug: "shutter-angle-speed-helper-180-degree-rule",
      title: "Shutter Angle/Speed Helper (180° Rule)",
      category: "video",
      subcategory: "time-fps-timecode",
      description: "Calculate shutter speed from angle and FPS (180° rule guide).",
      loader: () => import("@/components/calculators/Video/ShutterAngleSpeedHelper180DegreeRuleCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "slow-mo-speed-ramp-time-calculator",
      title: "Slow-Mo & Speed-Ramp Time Calculator",
      category: "video",
      subcategory: "time-fps-timecode",
      description: "Calculate playback duration changes when slowing down or ramping footage.",
      loader: () => import("@/components/calculators/Video/SlowMoSpeedRampTimeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "frame-count-duration-converter",
      title: "Frame Count ↔ Duration Converter",
      category: "video",
      subcategory: "time-fps-timecode",
      description: "Convert total frames to duration at a given FPS and vice versa.",
      loader: () => import("@/components/calculators/Video/FrameCountDurationConverterCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "frames-to-timecode-calculator",
      title: "Frames to Timecode Calculator",
      category: "video",
      subcategory: "time-fps-timecode",
      description: "Convert frame numbers to SMPTE timecode.",
      loader: () => import("@/components/calculators/Video/FramesToTimecodeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "timecode-addition-subtraction-calculator",
      title: "Timecode Addition/Subtraction Calculator",
      category: "video",
      subcategory: "time-fps-timecode",
      description: "Add or subtract timecodes accurately.",
      loader: () => import("@/components/calculators/Video/TimecodeAdditionSubtractionCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "drop-frame-timecode-converter",
      title: "Drop Frame Timecode Converter",
      category: "video",
      subcategory: "time-fps-timecode",
      description: "Handle drop-frame vs non-drop-frame NTSC timecode conversions.",
      loader: () => import("@/components/calculators/Video/DropFrameTimecodeConverterCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "timecode-to-frames-calculator",
      title: "Timecode to Frames Calculator",
      category: "video",
      subcategory: "time-fps-timecode",
      description: "Convert timecode back to total frame count.",
      loader: () => import("@/components/calculators/Video/TimecodeToFramesCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "render-time-calculator-3d",
      title: "3D Render Time Calculator",
      category: "video",
      subcategory: "video-rendering-export",
      description: "Calculate estimated render time based on frame count and time per frame.",
      loader: () => import("@/components/calculators/Video/ThreeDRenderTimeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "render-farm-time-calculator-3d",
      title: "3D Render Farm Time Calculator",
      category: "video",
      subcategory: "video-rendering-export",
      description: "Estimate render time when using a render farm with multiple nodes.",
      loader: () => import("@/components/calculators/Video/ThreeDRenderFarmTimeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "render-farm-cost-estimator",
      title: "Render Farm Cost Estimator",
      category: "video",
      subcategory: "video-rendering-export",
      description: "Calculate cost of using cloud render farms.",
      loader: () => import("@/components/calculators/Video/RenderFarmCostEstimatorCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "video-export-time-estimator",
      title: "Video Export Time Estimator",
      category: "video",
      subcategory: "video-rendering-export",
      description: "Predict export duration based on project complexity and hardware.",
      loader: () => import("@/components/calculators/Video/VideoExportTimeEstimatorCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "gpu-render-performance-calculator",
      title: "GPU Render Performance Calculator",
      category: "video",
      subcategory: "video-rendering-export",
      description: "Compare render performance across different GPUs.",
      loader: () => import("@/components/calculators/Video/GpuRenderPerformanceCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "render-time-per-frame-calculator",
      title: "Render Time Per Frame Calculator",
      category: "video",
      subcategory: "video-rendering-export",
      description: "Estimate average time per frame based on test renders.",
      seoTitle: "Render Time Per Frame Calculator — 3D & Animation Job Estimates",
      seoDescription: "Estimate total render time from a single test frame. Calculate render job duration for 3D animations, VFX sequences, and video exports by frame count and render speed.",
      loader: () => import("@/components/calculators/Video/RenderTimePerFrameCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cloud-render-queue-planner",
      title: "Cloud Render Queue Planner",
      category: "video",
      subcategory: "video-rendering-export",
      description: "Plan render queue priorities and estimated completion times.",
      loader: () => import("@/components/calculators/Video/CloudRenderQueuePlannerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "video-rendering-hardware-requirement-calculator",
      title: "Video Rendering Hardware Requirement Calculator",
      category: "video",
      subcategory: "video-rendering-export",
      description: "Recommend CPU/GPU/RAM specs for target render times.",
      loader: () => import("@/components/calculators/Video/VideoRenderingHardwareRequirementCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "animation-render-duration-estimator",
      title: "Animation Render Duration Estimator",
      category: "video",
      subcategory: "video-rendering-export",
      description: "Estimate full animation render timeline.",
      loader: () => import("@/components/calculators/Video/AnimationRenderDurationEstimatorCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "multi-workstation-render-time-calculator",
      title: "Multi-Workstation Render Time Calculator",
      category: "video",
      subcategory: "video-rendering-export",
      description: "Predict time savings using multiple local workstations.",
      loader: () => import("@/components/calculators/Video/MultiWorkstationRenderTimeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "amplifier-power-required-calculator",
      title: "Amplifier Power Required Calculator",
      category: "video",
      subcategory: "audio-processing-engineering",
      description: "Calculate required amplifier power for desired SPL at distance.",
      loader: () => import("@/components/calculators/Video/AmplifierPowerRequiredCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dbu-dbv-conversion-calculator",
      title: "dBu to dBV Conversion Calculator",
      category: "video",
      subcategory: "audio-processing-engineering",
      description: "Convert between dBu and dBV audio levels.",
      loader: () => import("@/components/calculators/Video/DbuDbvConversionCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "sound-pressure-level-spl-calculator",
      title: "Sound Pressure Level (SPL) Calculator",
      category: "video",
      subcategory: "audio-processing-engineering",
      description: "Calculate SPL at different listening positions.",
      loader: () => import("@/components/calculators/Video/SoundPressureLevelSplCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "speaker-placement-calculator",
      title: "Speaker Placement Calculator",
      category: "video",
      subcategory: "audio-processing-engineering",
      description: "Optimal speaker positioning for stereo or surround setups.",
      loader: () => import("@/components/calculators/Video/SpeakerPlacementCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cable-length-impact-calculator",
      title: "Cable Length Impact Calculator",
      category: "video",
      subcategory: "audio-processing-engineering",
      description: "Estimate signal loss or impedance changes over long cable runs.",
      loader: () => import("@/components/calculators/Video/CableLengthImpactCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "inverse-square-law-calculator",
      title: "Inverse Square Law Calculator",
      category: "video",
      subcategory: "audio-processing-engineering",
      description: "Apply inverse square law to sound intensity over distance.",
      loader: () => import("@/components/calculators/Video/InverseSquareLawCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "ohms-law-for-audio-calculator",
      title: "Ohm's Law for Audio Calculator",
      category: "video",
      subcategory: "audio-processing-engineering",
      description: "Calculate voltage, current, power, or impedance in audio circuits.",
      loader: () => import("@/components/calculators/Video/OhmsLawForAudioCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "speaker-crossover-calculator",
      title: "Speaker Crossover Calculator",
      category: "video",
      subcategory: "audio-processing-engineering",
      description: "Design crossover frequencies for multi-driver speaker systems.",
      loader: () => import("@/components/calculators/Video/SpeakerCrossoverCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "decibel-power-ratio-calculator",
      title: "Decibel Power Ratio Calculator",
      category: "video",
      subcategory: "audio-processing-engineering",
      description: "Convert between decibels and power ratios.",
      loader: () => import("@/components/calculators/Video/DecibelPowerRatioCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "audio-file-size-estimator",
      title: "Audio File Size Estimator",
      category: "video",
      subcategory: "audio-processing-engineering",
      description: "Calculate audio file size based on sample rate, bit depth, channels, and duration.",
      loader: () => import("@/components/calculators/Video/AudioFileSizeEstimatorCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "wavelength-frequency-calculator",
      title: "Wavelength and Frequency Calculator",
      category: "video",
      subcategory: "audio-processing-engineering",
      description: "Convert between sound frequency and wavelength at different temperatures.",
      loader: () => import("@/components/calculators/Video/WavelengthFrequencyCalculator"),
      urlStyle: "flat"
  
    },
  {
      slug: "aspect-ratio-16-9-to-9-16-1-1-crop-safe-area-helper",
      title: "16:9 → 9:16/1:1 Crop & Safe Area Helper",
      category: "video",
      subcategory: "resolution-aspect-ratio-pixels",
      description: "Plan crops and safe areas when converting landscape to vertical or square formats.",
      loader: () => import("@/components/calculators/Video/AspectRatio169To91611CropSafeAreaHelperCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dpi-ppi-pixels-print-display",
      title: "DPI/PPI ↔ Pixels (Print/Display)",
      category: "video",
      subcategory: "resolution-aspect-ratio-pixels",
      description: "Convert between DPI/PPI and pixel dimensions for print and display.",
      loader: () => import("@/components/calculators/Video/DpiPpiPixelsPrintDisplayCalculator"),
      urlStyle: "flat"
    }
];
