// AUTO-GENERATED by scripts/split-registry.cjs — DO NOT EDIT BY HAND.
// Per-category slice of the master CalculatorEntry registry.
// Re-run `node scripts/split-registry.cjs` after editing the master.

import type { CalculatorEntry } from "@/data/calculatorRegistry";

export const scienceEntries: CalculatorEntry[] = [
  {
      slug: "kinematics-suvat-solver",
      title: "Kinematics Equations Solver (SUVAT)",
      category: "science",
      subcategory: "physics-mechanics-motion",
      description: "Solve motion problems using SUVAT equations. Calculate displacement, initial/final velocity, acceleration, and time for uniform acceleration.",
      loader: () => import("@/components/calculators/Science/KinematicsSuvatSolverCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "projectile-motion-calculator",
      title: "Projectile Motion Calculator",
      category: "science",
      subcategory: "physics-mechanics-motion",
      description: "Analyze projectile motion. Calculate range, maximum height, and time of flight for objects launched at an angle under gravity.",
      loader: () => import("@/components/calculators/Science/ProjectileMotionCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "force-work-energy-calculator",
      title: "Force, Work & Energy Calculator",
      category: "science",
      subcategory: "physics-mechanics-motion",
      description: "Calculate Force, Work, and Energy. Solve physics problems involving Newton's laws, kinetic energy, and potential energy.",
      loader: () => import("@/components/calculators/Science/ForceWorkEnergyCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "power-efficiency-calculator",
      title: "Power & Efficiency Calculator",
      category: "science",
      subcategory: "physics-mechanics-motion",
      description: "Determine Power and Efficiency. Calculate the rate of work done and the energy efficiency of mechanical systems or engines.",
      loader: () => import("@/components/calculators/Science/PowerEfficiencyCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "momentum-impulse-calculator",
      title: "Momentum & Impulse Calculator",
      category: "science",
      subcategory: "physics-mechanics-motion",
      description: "Calculate Momentum and Impulse. Analyze collisions and the change in motion of objects using mass and velocity.",
      loader: () => import("@/components/calculators/Science/MomentumImpulseCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "uniform-circular-motion-centripetal",
      title: "Uniform Circular Motion Calculator",
      category: "science",
      subcategory: "physics-mechanics-motion",
      description: "Solve for centripetal force and acceleration. Calculate the velocity and period of objects in uniform circular motion.",
      loader: () => import("@/components/calculators/Science/UniformCircularMotionCentripetalCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "free-fall-time-velocity-estimator",
      title: "Free-Fall Time/Velocity Estimator",
      category: "science",
      subcategory: "physics-mechanics-motion",
      description: "Estimate free-fall parameters. Calculate how long an object takes to fall and its impact velocity under gravity.",
      loader: () => import("@/components/calculators/Science/FreeFallTimeVelocityEstimatorCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "wave-speed-frequency-wavelength",
      title: "Wave Speed / Frequency / Wavelength",
      category: "science",
      subcategory: "physics-waves-optics-thermo",
      description: "Calculate wave properties. Find the relationship between wave speed, frequency, and wavelength with the wave equation.",
      loader: () => import("@/components/calculators/Science/WaveSpeedFrequencyWavelengthCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "snells-law-critical-angle",
      title: "Snell’s Law & Critical Angle Calculator",
      category: "science",
      subcategory: "physics-waves-optics-thermo",
      description: "Solve optics problems using Snell's Law. Calculate the angle of refraction and the critical angle for total internal reflection.",
      loader: () => import("@/components/calculators/Science/SnellsLawCriticalAngleCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "thin-lens-solver",
      title: "Thin Lens Solver",
      category: "science",
      subcategory: "physics-waves-optics-thermo",
      description: "Solve Thin Lens equation problems. Calculate focal length, object distance, and image distance for convex and concave lenses.",
      loader: () => import("@/components/calculators/Science/ThinLensSolverCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "specific-heat-q-mc-delta-t",
      title: "Specific Heat Calculator",
      category: "science",
      subcategory: "physics-waves-optics-thermo",
      description: "Calculate heat energy (q=mcΔT). Determine the energy required to change the temperature of a substance based on specific heat capacity.",
      loader: () => import("@/components/calculators/Science/SpecificHeatQMcDeltaTCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "heat-transfer-conduction",
      title: "Heat Transfer (Conduction) Calculator",
      category: "science",
      subcategory: "physics-waves-optics-thermo",
      description: "Calculate rate of heat transfer by conduction. Solve thermal conductivity problems using Fourier's law for engineering and physics.",
      loader: () => import("@/components/calculators/Science/HeatTransferConductionCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "blackbody-peak-wien-law-estimator",
      title: "Blackbody Peak (Wien's Law) Estimator",
      category: "science",
      subcategory: "physics-waves-optics-thermo",
      description: "Estimate peak wavelength of blackbody radiation. Use Wien's Displacement Law to find the temperature of stars and hot objects.",
      loader: () => import("@/components/calculators/Science/BlackbodyPeakWienLawEstimatorCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "photon-energy-e-hf",
      title: "Photon Energy Calculator",
      category: "science",
      subcategory: "physics-electricity-modern",
      description: "Calculate the energy of a photon. Use Planck's constant and frequency (E=hf) to solve quantum physics problems.",
      loader: () => import("@/components/calculators/Science/PhotonEnergyEHfCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "half-life-exponential-decay",
      title: "Half-Life / Exponential Decay Calculator",
      category: "science",
      subcategory: "physics-electricity-modern",
      description: "Calculate radioactive half-life. Solve exponential decay problems to determine remaining quantity or elapsed time.",
      loader: () => import("@/components/calculators/Science/HalfLifeExponentialDecayCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "radioactive-activity-a-lambda-n",
      title: "Radioactive Activity Calculator",
      category: "science",
      subcategory: "physics-electricity-modern",
      description: "Calculate radioactive activity (A = λN). Determine the decay rate of a sample based on its decay constant.",
      loader: () => import("@/components/calculators/Science/RadioactiveActivityALambdaNCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "reactance-capacitor-inductor-educational",
      title: "Capacitor/Inductor Reactance Calculator",
      category: "science",
      subcategory: "physics-electricity-modern",
      description: "Calculate reactance for AC circuits. Determine the opposition to current flow in capacitors and inductors at specific frequencies.",
      loader: () => import("@/components/calculators/Science/ReactanceCapacitorInductorEducationalCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "rc-time-constant-tau-rc",
      title: "RC Time Constant Calculator",
      category: "science",
      subcategory: "physics-electricity-modern",
      description: "Calculate the RC Time Constant (τ). Determine how fast a capacitor charges or discharges through a resistor in a circuit.",
      loader: () => import("@/components/calculators/Science/RcTimeConstantTauRcCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "molarity-moles-volume",
      title: "Molarity / Moles / Volume Calculator",
      category: "science",
      subcategory: "chemistry-solutions-stoichiometry",
      description: "Calculate Molarity, Moles, and Volume. The essential tool for preparing chemical solutions and performing lab calculations.",
      loader: () => import("@/components/calculators/Science/MolarityMolesVolumeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dilution-c1v1-c2v2",
      title: "Dilution Calculator (C₁V₁ = C₂V₂)",
      category: "science",
      subcategory: "chemistry-solutions-stoichiometry",
      description: "Solve dilution problems easily. Calculate the volume needed to dilute a stock solution to a desired concentration.",
      loader: () => import("@/components/calculators/Science/DilutionC1v1C2v2Calculator"),
      urlStyle: "flat"
    },
  {
      slug: "molality-normality-converter",
      title: "Molality & Normality Converter",
      category: "science",
      subcategory: "chemistry-solutions-stoichiometry",
      description: "Convert concentration units. Calculate Molality and Normality for precise chemical solutions and acid-base titrations.",
      loader: () => import("@/components/calculators/Science/MolalityNormalityConverterCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "ideal-gas-law-pv-nrt",
      title: "Ideal Gas Law Calculator",
      category: "science",
      subcategory: "chemistry-solutions-stoichiometry",
      description: "Solve Ideal Gas Law problems (PV = nRT). Calculate pressure, volume, temperature, or moles of a gas instantly.",
      loader: () => import("@/components/calculators/Science/IdealGasLawPvNrtCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "stoichiometry-limiting-reagent",
      title: "Stoichiometry & Limiting Reagent Solver",
      category: "science",
      subcategory: "chemistry-solutions-stoichiometry",
      description: "Solve stoichiometry problems. Calculate the amounts of reactants and products and identify the limiting reagent in reactions.",
      loader: () => import("@/components/calculators/Science/StoichiometryLimitingReagentCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "percent-yield-theoretical-yield",
      title: "Percent Yield & Theoretical Yield",
      category: "science",
      subcategory: "chemistry-solutions-stoichiometry",
      description: "Calculate Percent Yield. Compare actual yield to theoretical yield to measure the efficiency of a chemical reaction.",
      loader: () => import("@/components/calculators/Science/PercentYieldTheoreticalYieldCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "ph-poh-h-oh-calculator",
      title: "pH / pOH / [H+] Calculator",
      category: "science",
      subcategory: "chemistry-solutions-stoichiometry",
      description: "Calculate pH, pOH, and ion concentration. Convert between acidity metrics easily for chemistry and biology applications.",
      loader: () => import("@/components/calculators/Science/PhPohHOhCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "buffer-henderson-hasselbalch-helper",
      title: "Buffer (Henderson–Hasselbalch) Helper",
      category: "science",
      subcategory: "chemistry-solutions-stoichiometry",
      description: "Design chemical buffers. Use the Henderson-Hasselbalch equation to calculate pH and ratio of conjugate base to acid.",
      loader: () => import("@/components/calculators/Science/BufferHendersonHasselbalchHelperCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "molar-mass-calculator",
      title: "Molar Mass Calculator",
      category: "science",
      subcategory: "chemistry-composition-units",
      description: "Calculate Molar Mass. Find the molecular weight of any chemical compound by summing atomic masses from the periodic table.",
      loader: () => import("@/components/calculators/Science/MolarMassCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "percent-composition-by-mass",
      title: "Percent Composition by Mass",
      category: "science",
      subcategory: "chemistry-composition-units",
      description: "Calculate Percent Composition by Mass. Determine the percentage of each element within a chemical compound.",
      loader: () => import("@/components/calculators/Science/PercentCompositionByMassCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "ppm-ppb-concentration-converter",
      title: "ppm / ppb Concentration Converter",
      category: "science",
      subcategory: "chemistry-composition-units",
      description: "Convert concentration units. Switch between parts per million (ppm), parts per billion (ppb), and molarity for trace analysis.",
      loader: () => import("@/components/calculators/Science/PpmPpbConcentrationConverterCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "density-specific-gravity-calculator",
      title: "Density / Specific Gravity Calculator",
      category: "science",
      subcategory: "chemistry-composition-units",
      description: "Calculate Density and Specific Gravity. Determine the mass-to-volume ratio of solids, liquids, and gases.",
      loader: () => import("@/components/calculators/Science/DensitySpecificGravityCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "escape-velocity-calculator",
      title: "Escape Velocity Calculator",
      category: "science",
      subcategory: "astronomy-earth-science",
      description: "Calculate Escape Velocity. Determine the speed needed to break free from the gravitational pull of a planet or moon.",
      loader: () => import("@/components/calculators/Science/EscapeVelocityCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "orbital-period-kepler-estimator",
      title: "Orbital Period (Kepler) Estimator",
      category: "science",
      subcategory: "astronomy-earth-science",
      description: "Estimate Orbital Period using Kepler's Laws. Calculate the time it takes for a planet or satellite to orbit a massive body.",
      loader: () => import("@/components/calculators/Science/OrbitalPeriodKeplerEstimatorCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "gravity-on-other-planets-calculator",
      title: "Gravity on Other Planets Calculator",
      category: "science",
      subcategory: "astronomy-earth-science",
      description: "Calculate gravity on other planets. See how much you would weigh on Mars, Jupiter, or the Moon compared to Earth.",
      loader: () => import("@/components/calculators/Science/GravityOnOtherPlanetsCalculator"),
      urlStyle: "flat"
    }
];
