import { useState, useMemo, useCallback } from "react";
import CalculatorVerticalLayout from '@/components/templates/CalculatorVerticalLayout';
import { Card, CardContent } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Smile, Sparkles, RotateCcw, Lightbulb, ExternalLink } from "lucide-react";
import useFaqJsonLd from "@/hooks/useFaqJsonLd";

export default function MemeViralityCalculator() {
  // Inputs: Reach (number of people who see the meme),
  // Engagement Rate (percentage of people interacting),
  // Share Factor (average shares per engager)
  const [inputs, setInputs] = useState({
    reach: "",
    engagementRate: "",
    shareFactor: "",
  });

  const handleInputChange = useCallback((name, value) => {
    // Allow only numbers and decimals, sanitize input
    if (/^\d*\.?\d*$/.test(value) || value === "") {
      setInputs((prev) => ({ ...prev, [name]: value }));
    }
  }, []);

  const results = useMemo(() => {
    const reach = parseFloat(inputs.reach);
    const engagementRate = parseFloat(inputs.engagementRate);
    const shareFactor = parseFloat(inputs.shareFactor);

    // Initial state safety: if any input is empty or invalid, return neutral state
    if (
      isNaN(reach) ||
      isNaN(engagementRate) ||
      isNaN(shareFactor) ||
      reach <= 0 ||
      engagementRate < 0 ||
      shareFactor < 0
    ) {
      return { value: null };
    }

    // Formula: Virality Score = Reach × (Engagement Rate / 100) × Share Factor
    // This estimates the total shares generated by the meme.
    const viralityScore = reach * (engagementRate / 100) * shareFactor;

    // Label and subtext based on virality score thresholds (tongue-in-cheek)
    let label = "";
    let subtext = "";
    let color = "text-blue-600";
    let icon = <Smile className="mx-auto" size={48} />;

    if (viralityScore === 0) {
      label = "No Buzz";
      subtext = "Your meme didn't catch any attention. Try spicier content!";
      color = "text-gray-500";
      icon = <Frown className="mx-auto" size={48} />;
    } else if (viralityScore < 100) {
      label = "Mildly Viral";
      subtext = "Some shares, but your meme is still warming up.";
      color = "text-yellow-600";
      icon = <Meh className="mx-auto" size={48} />;
    } else if (viralityScore < 1000) {
      label = "Going Viral";
      subtext = "Your meme is spreading fast! Keep the momentum.";
      color = "text-green-600";
      icon = <Smile className="mx-auto" size={48} />;
    } else if (viralityScore < 10000) {
      label = "Super Viral";
      subtext = "Your meme is everywhere! Internet fame awaits.";
      color = "text-purple-600";
      icon = <Zap className="mx-auto" size={48} />;
    } else {
      label = "Legendary Meme";
      subtext = "Your meme broke the internet! Legendary status achieved.";
      color = "text-red-600";
      icon = <Flame className="mx-auto" size={48} />;
    }

    return {
      value: viralityScore.toLocaleString("en-US"),
      label,
      subtext,
      color,
      icon,
    };
  }, [inputs]);

  const faqs = [
    {
      question: "How accurate is the Meme Virality Calculator?",
      answer:
        "This calculator provides a fun, tongue-in-cheek estimate based on simple inputs. Actual meme virality depends on many unpredictable factors like timing, platform algorithms, and audience mood.",
    },
    {
      question: "What is 'Engagement Rate'?",
      answer:
        "Engagement Rate is the percentage of people who interact with your meme (likes, comments, shares) out of those who saw it. Higher engagement usually means higher virality potential.",
    },
    {
      question: "Can I use this for any social media platform?",
      answer:
        "Yes! Just input your estimated reach and engagement rates from any platform. Keep in mind that different platforms have different sharing dynamics.",
    },
  ];
  const faqJsonLd = useFaqJsonLd(faqs);

  const widget = (
    <div className="space-y-6">
      {/* Inputs */}
      <div className="space-y-4">
        <div>
          <Label htmlFor="reach">Reach (Number of people who see your meme)</Label>
          <Input
            id="reach"
            type="text"
            inputMode="decimal"
            placeholder="e.g. 10000"
            value={inputs.reach}
            onChange={(e) => handleInputChange("reach", e.target.value)}
          />
        </div>
        <div>
          <Label htmlFor="engagementRate">Engagement Rate (%)</Label>
          <Input
            id="engagementRate"
            type="text"
            inputMode="decimal"
            placeholder="e.g. 5"
            value={inputs.engagementRate}
            onChange={(e) => handleInputChange("engagementRate", e.target.value)}
          />
        </div>
        <div>
          <Label htmlFor="shareFactor">Share Factor (Average shares per engager)</Label>
          <Input
            id="shareFactor"
            type="text"
            inputMode="decimal"
            placeholder="e.g. 2"
            value={inputs.shareFactor}
            onChange={(e) => handleInputChange("shareFactor", e.target.value)}
          />
        </div>
      </div>

      <div className="flex flex-col sm:flex-row gap-3 pt-4">
        <Button
          className="flex-1 h-11 bg-blue-600 hover:bg-blue-700 text-white shadow-md"
          onClick={() => {
            // No special action needed, calculation is reactive
          }}
        >
          <Sparkles className="mr-2 h-4 w-4" /> Calculate
        </Button>
        <Button
          variant="outline"
          onClick={() => setInputs({ reach: "", engagementRate: "", shareFactor: "" })}
          className="flex-1 h-11"
        >
          <RotateCcw className="mr-2 h-4 w-4" /> Reset
        </Button>
      </div>

      {results.value !== null && (
        <Card className="bg-gradient-to-br from-slate-50 to-slate-100 dark:from-slate-900 dark:to-slate-950 border-slate-200 shadow-lg animate-in fade-in slide-in-from-bottom-4">
          <CardContent className="p-8 text-center">
            <div className="flex justify-center mb-4">{results.icon}</div>
            <p className={`text-5xl font-extrabold ${results.color}`}>{results.value}</p>
            <p className="mt-2 text-lg font-medium text-slate-600 dark:text-slate-300">{results.label}</p>
            <p className="mt-2 text-sm italic text-slate-500">{results.subtext}</p>
          </CardContent>
        </Card>
      )}
    </div>
  );

  const editorial = (
    <div className="space-y-12">
      <section id="what-is" className="scroll-mt-32">
        <h2 className="text-3xl font-bold mb-4 text-slate-900 dark:text-slate-100">
          Understanding Meme Virality Calculator
        </h2>
        <p className="text-slate-700 dark:text-slate-300 leading-relaxed mb-4">
          The Meme Virality Calculator estimates the potential spread of your meme based on three key factors: reach,
          engagement rate, and share factor. Reach represents how many people see your meme, engagement rate measures
          how many interact with it, and share factor estimates how many times each engager shares it further. By
          multiplying these, the calculator gives a fun estimate of your meme’s viral potential.
        </p>
        <p className="text-slate-700 dark:text-slate-300 leading-relaxed mb-4">
          While this tool is a playful approximation, it highlights the importance of audience interaction and sharing
          in making content go viral. Memes that resonate emotionally or humorously tend to have higher engagement and
          share factors, boosting their viral reach exponentially.
        </p>

        <div className="bg-blue-50 dark:bg-blue-950/30 p-6 rounded-xl border border-blue-100 dark:border-blue-900 my-6">
          <div className="flex items-center gap-2 mb-3">
            <Lightbulb className="w-5 h-5 text-yellow-500" />
            <h3 className="font-bold text-lg text-slate-800 dark:text-slate-200">Did You Know?</h3>
          </div>
          <p className="text-slate-700 dark:text-slate-300">
            The most viral meme ever, the “Distracted Boyfriend” image, has been shared millions of times worldwide,
            inspiring countless variations and becoming a cultural phenomenon beyond the internet.
          </p>
        </div>
      </section>

      <section id="how-to" className="scroll-mt-32">
        <h2 className="text-3xl font-bold mb-4 text-slate-900 dark:text-slate-100">How to Use the Calculator</h2>
        <p className="text-slate-700 dark:text-slate-300 leading-relaxed mb-4">
          Enter the estimated number of people who have seen your meme in the Reach field. Next, input the percentage
          of those viewers who engaged with the meme (liked, commented, or shared) as the Engagement Rate. Finally,
          provide the average number of times each engager shares the meme in the Share Factor field.
        </p>
        <p className="text-slate-700 dark:text-slate-300 leading-relaxed mb-4">
          Click “Calculate” to see your meme’s virality score, which estimates total shares generated. Use the Reset
          button to clear inputs and try different scenarios. This tool is perfect for social media managers and meme
          creators curious about their content’s viral potential.
        </p>
      </section>

      <section id="faq" className="scroll-mt-32">
        <h2 className="text-3xl font-bold mb-4 text-slate-900 dark:text-slate-100">Frequently Asked Questions</h2>
        <dl className="space-y-6">
          {faqs.map(({ question, answer }, i) => (
            <div key={i}>
              <dt className="font-semibold text-lg text-slate-900 dark:text-slate-100">{question}</dt>
              <dd className="mt-1 text-slate-700 dark:text-slate-300 leading-relaxed">{answer}</dd>
            </div>
          ))}
        </dl>
      </section>

      <section id="references" className="scroll-mt-32">
        <h2 className="text-3xl font-bold mb-4 text-slate-900 dark:text-slate-100">References</h2>
        <ul className="space-y-4 list-disc list-inside text-slate-700 dark:text-slate-300">
          <li>
            <a
              href="https://www.rollingstone.com/culture/culture-news/distracted-boyfriend-meme-viral-history-1234600/"
              target="_blank"
              rel="noopener noreferrer"
              className="font-bold text-blue-600 hover:underline flex items-center gap-1"
            >
              The Viral History of the Distracted Boyfriend Meme <ExternalLink className="w-3 h-3" />
            </a>
            <p className="text-sm text-slate-500 mt-1">
              Rolling Stone article detailing the cultural impact of one of the internet’s most viral memes.
            </p>
          </li>
          <li>
            <a
              href="https://sproutsocial.com/insights/social-media-engagement/"
              target="_blank"
              rel="noopener noreferrer"
              className="font-bold text-blue-600 hover:underline flex items-center gap-1"
            >
              What is Social Media Engagement? <ExternalLink className="w-3 h-3" />
            </a>
            <p className="text-sm text-slate-500 mt-1">
              Sprout Social’s guide explaining engagement metrics and their importance in social media marketing.
            </p>
          </li>
        </ul>
      </section>
    </div>
  );

  return (
    <CalculatorVerticalLayout
      title="Meme Virality Calculator"
      description="Predict meme success. A tongue-in-cheek calculator to estimate the viral potential of your latest internet creation."
      widget={widget}
      editorial={editorial}
      jsonLd={faqJsonLd}
      formula={{
        title: "The Math",
        formula: "Virality Score = Reach × (Engagement Rate ÷ 100) × Share Factor",
        variables: [
          { symbol: "Reach", description: "Number of people who see your meme" },
          { symbol: "Engagement Rate", description: "Percentage of viewers who interact with the meme" },
          { symbol: "Share Factor", description: "Average number of shares per engager" },
          { symbol: "Virality Score", description: "Estimated total shares generated by the meme" },
        ],
      }}
      example={{
        title: "Example",
        scenario:
          "You post a meme that reaches 10,000 people. 5% engage with it, and each engager shares it twice on average.",
        steps: [
          { label: "1", explanation: "Reach = 10,000" },
          { label: "2", explanation: "Engagement Rate = 5%" },
          { label: "3", explanation: "Share Factor = 2" },
          {
            label: "4",
            explanation:
              "Virality Score = 10,000 × (5 ÷ 100) × 2 = 1,000 total shares, indicating your meme is going viral!",
          },
        ],
        result: "Virality Score: 1,000 shares",
      }}
      relatedCalculators={[
        { title: "Pokémon GO Weight Loss Calculator", url: "/funny/pokemon-go-weight-loss", icon: "🤪" },
        { title: "Pizza Size/Price Comparison Calculator", url: "/funny/pizza-size-price-comparison", icon: "🍕" },
        { title: "Nickels to Crush Calculator", url: "/funny/nickels-to-crush-calculator", icon: "🤪" },
        { title: "Coffee Addiction Meter", url: "/funny/coffee-addiction-meter", icon: "☕" },
        { title: "First-Date Awkwardness Meter", url: "/funny/first-date-awkwardness-meter", icon: "❤️" },
        { title: "Tab Overload Anxiety Score", url: "/funny/tab-overload-anxiety-score", icon: "💻" },
      ]}
      onThisPage={[
        { id: "what-is", label: "Understanding" },
        { id: "how-to", label: "How to Use" },
        { id: "faq", label: "FAQ" },
        { id: "references", label: "References" },
      ]}
      showTopBanner
      showSidebar
      showBottomBanner
    />
  );
}