// AUTO-GENERATED by scripts/split-registry.cjs — DO NOT EDIT BY HAND.
// Per-category slice of the master CalculatorEntry registry.
// Re-run `node scripts/split-registry.cjs` after editing the master.

import type { CalculatorEntry } from "@/data/calculatorRegistry";

export const funnyEntries: CalculatorEntry[] = [
  {
      slug: "pizza-size-price-comparison",
      title: "Pizza Size/Price Comparison Calculator",
      category: "funny",
      subcategory: "food-social-life",
      description: "Solve the ultimate dinner dilemma. Calculate price per square inch to see if two medium pizzas are a better deal than one large.",
      loader: () => import("@/components/calculators/Funny/PizzaSizePriceComparisonCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "pizza-slices-per-person-regret-index",
      title: "Pizza Slices per Person & Regret Index",
      category: "funny",
      subcategory: "food-social-life",
      description: "Plan your pizza party perfectly. Estimate slices per person and calculate the potential 'regret index' for overeating.",
      loader: () => import("@/components/calculators/Funny/PizzaSlicesPerPersonRegretIndexCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "bbq-charcoal-splitter",
      title: "BBQ 'Who Brings the Charcoal?' Splitter",
      category: "funny",
      subcategory: "food-social-life",
      description: "Settle BBQ disputes fairly. A randomizer tool to decide who buys the charcoal, who brings the meat, and who just brings the vibes.",
      loader: () => import("@/components/calculators/Funny/BbqCharcoalSplitterCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "coffee-strength-vs-productivity-meme",
      title: "Coffee Strength vs Productivity Score",
      category: "funny",
      subcategory: "food-social-life",
      description: "Chart your caffeine intake against work output. Find the sweet spot between 'peak productivity' and 'jittery chaos'.",
      loader: () => import("@/components/calculators/Funny/CoffeeStrengthVsProductivityMemeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "hot-dog-bun-mismatch-solver",
      title: "Hot-Dog to Bun Mismatch Solver",
      category: "funny",
      subcategory: "food-social-life",
      description: "Solve the supermarket conspiracy. Calculate exactly how many packs of hot dogs and buns you need to buy to have zero leftovers.",
      loader: () => import("@/components/calculators/Funny/HotDogBunMismatchSolverCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "sugar-in-my-tea-dramatic",
      title: "How Much Sugar Is in My Tea? (Dramatic)",
      category: "funny",
      subcategory: "food-social-life",
      description: "Visualize your sugar intake. See a dramatic representation of exactly how many sugar cubes you are drinking in your daily tea.",
      loader: () => import("@/components/calculators/Funny/SugarInMyTeaDramaticCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "first-date-awkwardness-meter",
      title: "First-Date Awkwardness Meter",
      category: "funny",
      subcategory: "food-social-life",
      description: "Rate your date's potential awkwardness. Input variables like 'talks about ex' or 'forgot wallet' to predict the night's outcome.",
      loader: () => import("@/components/calculators/Funny/FirstDateAwkwardnessMeterCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "donut-calculator",
      title: "Donut Calculator",
      category: "funny",
      subcategory: "food-social-life",
      description: "Calculate the optimal number of donuts for the office. Adjust for team size, hunger levels, and the 'it is Friday' factor.",
      loader: () => import("@/components/calculators/Funny/DonutCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "ideal-egg-boiling-calculator",
      title: "Ideal Egg Boiling Calculator",
      category: "funny",
      subcategory: "food-social-life",
      description: "Boil the perfect egg every time. Calculate the exact cooking time for soft, medium, or hard-boiled eggs based on altitude and size.",
      loader: () => import("@/components/calculators/Funny/IdealEggBoilingCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "coffee-addiction-meter",
      title: "Coffee Addiction Meter",
      category: "funny",
      subcategory: "food-social-life",
      description: "Assess your coffee dependency level. Answer fun questions to see if you run on caffeine or actual sleep.",
      loader: () => import("@/components/calculators/Funny/CoffeeAddictionMeterCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "zombie-survival-calculator",
      title: "Zombie Survival Calculator",
      category: "funny",
      subcategory: "food-social-life",
      description: "Estimate your survival odds. Calculate how long you would last in a zombie apocalypse based on cardio, skills, and weapon choice.",
      loader: () => import("@/components/calculators/Funny/ZombieSurvivalCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "love-meter",
      title: "Love Meter (Name Compatibility)",
      category: "funny",
      subcategory: "food-social-life",
      description: "Test name compatibility. A classic fun algorithm to see if you and your crush are a 100% match or destined for doom.",
      loader: () => import("@/components/calculators/Funny/LoveMeterCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "meetings-wasted-time-counter",
      title: "Meetings Wasted-Time Counter",
      category: "funny",
      subcategory: "tech-work-life",
      description: "Calculate the cost of useless meetings. Input attendees and average salary to see how much money is burning while you talk.",
      loader: () => import("@/components/calculators/Funny/MeetingsWastedTimeCounterCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "email-cost-estimator-energy",
      title: "Cost to Send This Email (Energy/kWh)",
      category: "funny",
      subcategory: "tech-work-life",
      description: "Estimate the environmental cost of your emails. Calculate the energy usage and carbon footprint of sending that 'Reply All' message.",
      loader: () => import("@/components/calculators/Funny/EmailCostEstimatorEnergyCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "tab-overload-anxiety-score",
      title: "Tab Overload Anxiety Score",
      category: "funny",
      subcategory: "tech-work-life",
      description: "Measure your browser tab anxiety. Calculate a stress score based on the number of open tabs you are too afraid to close.",
      loader: () => import("@/components/calculators/Funny/TabOverloadAnxietyScoreCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "commit-message-quality-judge",
      title: "Commit Message Quality Judge",
      category: "funny",
      subcategory: "tech-work-life",
      description: "Rate your git commit messages. Are you writing useful descriptions or just 'wip' and 'fix'? Get a fun quality score.",
      loader: () => import("@/components/calculators/Funny/CommitMessageQualityJudgeCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "keyboard-clicks-per-day",
      title: "Keyboard Clicks per Day Estimator",
      category: "funny",
      subcategory: "tech-work-life",
      description: "Estimate your daily typing volume. Calculate how many millions of times you click your keyboard over a lifetime of work.",
      loader: () => import("@/components/calculators/Funny/KeyboardClicksPerDayCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "meme-virality-calculator",
      title: "Meme Virality Calculator",
      category: "funny",
      subcategory: "tech-work-life",
      description: "Predict meme success. A tongue-in-cheek calculator to estimate the viral potential of your latest internet creation.",
      loader: () => import("@/components/calculators/Funny/MemeViralityCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "calculator-word-generator-upside-down",
      title: "Calculator Word Generator (Upside-Down)",
      category: "funny",
      subcategory: "tech-work-life",
      description: "Write words on a calculator. Generate the numbers needed to spell 'HELLO', 'ZOMBIE', and other classics when turned upside down.",
      loader: () => import("@/components/calculators/Funny/CalculatorWordGeneratorUpsideDownCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "lost-socks-calculator",
      title: "Lost Socks Calculator",
      category: "funny",
      subcategory: "home-pets-pop-culture",
      description: "Solve the laundry mystery. Estimate the probability of losing a sock based on wash frequency and dryer portal theories.",
      loader: () => import("@/components/calculators/Funny/LostSocksCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "dog-zoomies-energy-meter",
      title: "Dog Zoomies Energy Release Meter",
      category: "funny",
      subcategory: "home-pets-pop-culture",
      description: "Measure dog energy bursts. Calculate the kinetic energy of your dog's 3 AM zoomies based on speed and destruction level.",
      loader: () => import("@/components/calculators/Funny/DogZoomiesEnergyMeterCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "cat-ignore-o-meter",
      title: "Cat 'Ignore-o-Meter'",
      category: "funny",
      subcategory: "home-pets-pop-culture",
      description: "Predict cat acknowledgement. Calculate the extremely low probability that your cat will actually respond when you call its name.",
      loader: () => import("@/components/calculators/Funny/CatIgnoreOMeterCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "plant-watering-procrastination-index",
      title: "Plant Watering Procrastination Index",
      category: "funny",
      subcategory: "home-pets-pop-culture",
      description: "Track plant neglect. Calculate how long you can 'procrastinate' watering your plants before they officially give up on you.",
      loader: () => import("@/components/calculators/Funny/PlantWateringProcrastinationIndexCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "netflix-one-more-episode-timer",
      title: "Netflix 'Just One More Episode' Timer",
      category: "funny",
      subcategory: "home-pets-pop-culture",
      description: "Manage binge-watching risks. Calculate how much of your life will be consumed if you watch 'just one more episode' tonight.",
      loader: () => import("@/components/calculators/Funny/NetflixOneMoreEpisodeTimerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "death-by-caffeine",
      title: "Death by Caffeine (Max Safe Intake)",
      category: "funny",
      subcategory: "home-pets-pop-culture",
      description: "Calculate your caffeine limit. Find out exactly how many cups of coffee would be lethal (so you can stop safely before that).",
      loader: () => import("@/components/calculators/Funny/DeathByCaffeineCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "social-media-time-alternatives",
      title: "Social Media Time Alternatives",
      category: "funny",
      subcategory: "home-pets-pop-culture",
      description: "Reclaim your time. See what new skills or hobbies you could have mastered in the time spent scrolling social media this year.",
      loader: () => import("@/components/calculators/Funny/SocialMediaTimeAlternativesCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "pokemon-go-weight-loss",
      title: "Pokémon GO Weight Loss Calculator",
      category: "funny",
      subcategory: "home-pets-pop-culture",
      description: "Gamify your fitness. Estimate how many calories you burn while walking to hatch eggs and catch Pokémon.",
      loader: () => import("@/components/calculators/Funny/PokemonGoWeightLossCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "life-value-in-tacos",
      title: "Life Value Estimator (Worth in Tacos)",
      category: "funny",
      subcategory: "home-pets-pop-culture",
      description: "Convert your net worth to tacos. See how rich you truly are by measuring your assets in units of delicious tacos.",
      loader: () => import("@/components/calculators/Funny/LifeValueInTacosCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "drake-equation-calculator",
      title: "Drake Equation Calculator",
      category: "funny",
      subcategory: "home-pets-pop-culture",
      description: "Estimate alien life. Use the famous Drake Equation to calculate the number of active, communicative extraterrestrial civilizations.",
      loader: () => import("@/components/calculators/Funny/DrakeEquationCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "vacation-budget-reality-check",
      title: "Vacation Budget Reality Check",
      category: "funny",
      subcategory: "absurd-travel-adventure",
      description: "Budget your dream trip vs reality. A fun tool to see how far your actual savings will get you (maybe just to the backyard?).",
      loader: () => import("@/components/calculators/Funny/VacationBudgetRealityCheckCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "loop-the-loop-speed-calculator",
      title: "Loop-the-Loop Speed Calculator",
      category: "funny",
      subcategory: "absurd-travel-adventure",
      description: "Physics for fun. Calculate the minimum speed a car needs to successfully drive through a vertical loop-the-loop without falling.",
      loader: () => import("@/components/calculators/Funny/LoopTheLoopSpeedCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "rocks-to-flood-country",
      title: "Rocks to Flood a Country Estimator",
      category: "funny",
      subcategory: "absurd-travel-adventure",
      description: "Absurd physics scenario. Calculate how many rocks you would need to throw into the ocean to theoretically flood a specific country.",
      loader: () => import("@/components/calculators/Funny/RocksToFloodCountryCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "penguin-slap-power",
      title: "Penguin Slap Power Calculator",
      category: "funny",
      subcategory: "absurd-travel-adventure",
      description: "Calculate slap physics. Estimate the thermodynamic energy converted if you theoretically slapped a penguin (strictly hypothetical).",
      loader: () => import("@/components/calculators/Funny/PenguinSlapPowerCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "nickels-to-crush-calculator",
      title: "Nickels to Crush Calculator",
      category: "funny",
      subcategory: "absurd-travel-adventure",
      description: "Hydraulic press simulator. Calculate how many nickels stacked on top of an object would be heavy enough to crush it.",
      loader: () => import("@/components/calculators/Funny/NickelsToCrushCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "black-hole-sun-impact",
      title: "Black Hole Sun Impact Calculator",
      category: "funny",
      subcategory: "absurd-travel-adventure",
      description: "Apocalypse calculator. What would happen to Earth's orbit if the sun instantly turned into a black hole of the same mass?",
      loader: () => import("@/components/calculators/Funny/BlackHoleSunImpactCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "time-travel-energy-requirement",
      title: "Time Travel Energy Requirement",
      category: "funny",
      subcategory: "absurd-travel-adventure",
      description: "Sci-fi physics. Estimate the immense energy required to travel back in time based on theoretical warp drive metrics.",
      loader: () => import("@/components/calculators/Funny/TimeTravelEnergyRequirementCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "medical-tourism-cost-saver",
      title: "Medical Tourism Cost Saver",
      category: "funny",
      subcategory: "absurd-travel-adventure",
      description: "Calculate savings on medical procedures. Compare the cost of surgery abroad versus domestic prices (plus a recovery vacation).",
      loader: () => import("@/components/calculators/Funny/MedicalTourismCostSaverCalculator"),
      urlStyle: "flat"
    },
  {
      slug: "crinkle-crankle-wall-brick-saver",
      title: "Crinkle Crankle Wall Brick Saver",
      category: "funny",
      subcategory: "absurd-travel-adventure",
      description: "Optimize brick usage. Calculate how many bricks you save by building a wavy 'crinkle crankle' wall instead of a straight one.",
      loader: () => import("@/components/calculators/Funny/CrinkleCrankleWallBrickSaverCalculator"),
      urlStyle: "flat"
    }
];
